// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// AffinityConfigurationApplyConfiguration represents a declarative configuration of the AffinityConfiguration type for use
// with apply.
//
// AffinityConfiguration contains the info we need to create the
// affinity rules for Pods
type AffinityConfigurationApplyConfiguration struct {
	// Activates anti-affinity for the pods. The operator will define pods
	// anti-affinity unless this field is explicitly set to false
	EnablePodAntiAffinity *bool `json:"enablePodAntiAffinity,omitempty"`
	// TopologyKey to use for anti-affinity configuration. See k8s documentation
	// for more info on that
	TopologyKey *string `json:"topologyKey,omitempty"`
	// NodeSelector is map of key-value pairs used to define the nodes on which
	// the pods can run.
	// More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// NodeAffinity describes node affinity scheduling rules for the pod.
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
	NodeAffinity *corev1.NodeAffinity `json:"nodeAffinity,omitempty"`
	// Tolerations is a list of Tolerations that should be set for all the pods, in order to allow them to run
	// on tainted nodes.
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`
	// PodAntiAffinityType allows the user to decide whether pod anti-affinity between cluster instance has to be
	// considered a strong requirement during scheduling or not. Allowed values are: "preferred" (default if empty) or
	// "required". Setting it to "required", could lead to instances remaining pending until new kubernetes nodes are
	// added if all the existing nodes don't match the required pod anti-affinity rule.
	// More info:
	// https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
	PodAntiAffinityType *string `json:"podAntiAffinityType,omitempty"`
	// AdditionalPodAntiAffinity allows to specify pod anti-affinity terms to be added to the ones generated
	// by the operator if EnablePodAntiAffinity is set to true (default) or to be used exclusively if set to false.
	AdditionalPodAntiAffinity *corev1.PodAntiAffinity `json:"additionalPodAntiAffinity,omitempty"`
	// AdditionalPodAffinity allows to specify pod affinity terms to be passed to all the cluster's pods.
	AdditionalPodAffinity *corev1.PodAffinity `json:"additionalPodAffinity,omitempty"`
}

// AffinityConfigurationApplyConfiguration constructs a declarative configuration of the AffinityConfiguration type for use with
// apply.
func AffinityConfiguration() *AffinityConfigurationApplyConfiguration {
	return &AffinityConfigurationApplyConfiguration{}
}

// WithEnablePodAntiAffinity sets the EnablePodAntiAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnablePodAntiAffinity field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithEnablePodAntiAffinity(value bool) *AffinityConfigurationApplyConfiguration {
	b.EnablePodAntiAffinity = &value
	return b
}

// WithTopologyKey sets the TopologyKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyKey field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithTopologyKey(value string) *AffinityConfigurationApplyConfiguration {
	b.TopologyKey = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *AffinityConfigurationApplyConfiguration) WithNodeSelector(entries map[string]string) *AffinityConfigurationApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithNodeAffinity sets the NodeAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeAffinity field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithNodeAffinity(value corev1.NodeAffinity) *AffinityConfigurationApplyConfiguration {
	b.NodeAffinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *AffinityConfigurationApplyConfiguration) WithTolerations(values ...corev1.Toleration) *AffinityConfigurationApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithPodAntiAffinityType sets the PodAntiAffinityType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodAntiAffinityType field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithPodAntiAffinityType(value string) *AffinityConfigurationApplyConfiguration {
	b.PodAntiAffinityType = &value
	return b
}

// WithAdditionalPodAntiAffinity sets the AdditionalPodAntiAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdditionalPodAntiAffinity field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithAdditionalPodAntiAffinity(value corev1.PodAntiAffinity) *AffinityConfigurationApplyConfiguration {
	b.AdditionalPodAntiAffinity = &value
	return b
}

// WithAdditionalPodAffinity sets the AdditionalPodAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdditionalPodAffinity field is set to the value of the last call.
func (b *AffinityConfigurationApplyConfiguration) WithAdditionalPodAffinity(value corev1.PodAffinity) *AffinityConfigurationApplyConfiguration {
	b.AdditionalPodAffinity = &value
	return b
}
