// Code generated by controller-gen. DO NOT EDIT.

package v1

// AvailableArchitectureApplyConfiguration represents a declarative configuration of the AvailableArchitecture type for use
// with apply.
//
// AvailableArchitecture represents the state of a cluster's architecture
type AvailableArchitectureApplyConfiguration struct {
	// GoArch is the name of the executable architecture
	GoArch *string `json:"goArch,omitempty"`
	// Hash is the hash of the executable
	Hash *string `json:"hash,omitempty"`
}

// AvailableArchitectureApplyConfiguration constructs a declarative configuration of the AvailableArchitecture type for use with
// apply.
func AvailableArchitecture() *AvailableArchitectureApplyConfiguration {
	return &AvailableArchitectureApplyConfiguration{}
}

// WithGoArch sets the GoArch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GoArch field is set to the value of the last call.
func (b *AvailableArchitectureApplyConfiguration) WithGoArch(value string) *AvailableArchitectureApplyConfiguration {
	b.GoArch = &value
	return b
}

// WithHash sets the Hash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hash field is set to the value of the last call.
func (b *AvailableArchitectureApplyConfiguration) WithHash(value string) *AvailableArchitectureApplyConfiguration {
	b.Hash = &value
	return b
}
