// Code generated by controller-gen. DO NOT EDIT.

package v1

// BackupSnapshotElementStatusApplyConfiguration represents a declarative configuration of the BackupSnapshotElementStatus type for use
// with apply.
//
// BackupSnapshotElementStatus is a volume snapshot that is part of a volume snapshot method backup
type BackupSnapshotElementStatusApplyConfiguration struct {
	// Name is the snapshot resource name
	Name *string `json:"name,omitempty"`
	// Type is tho role of the snapshot in the cluster, such as PG_DATA, PG_WAL and PG_TABLESPACE
	Type *string `json:"type,omitempty"`
	// TablespaceName is the name of the snapshotted tablespace. Only set
	// when type is PG_TABLESPACE
	TablespaceName *string `json:"tablespaceName,omitempty"`
}

// BackupSnapshotElementStatusApplyConfiguration constructs a declarative configuration of the BackupSnapshotElementStatus type for use with
// apply.
func BackupSnapshotElementStatus() *BackupSnapshotElementStatusApplyConfiguration {
	return &BackupSnapshotElementStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackupSnapshotElementStatusApplyConfiguration) WithName(value string) *BackupSnapshotElementStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BackupSnapshotElementStatusApplyConfiguration) WithType(value string) *BackupSnapshotElementStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithTablespaceName sets the TablespaceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TablespaceName field is set to the value of the last call.
func (b *BackupSnapshotElementStatusApplyConfiguration) WithTablespaceName(value string) *BackupSnapshotElementStatusApplyConfiguration {
	b.TablespaceName = &value
	return b
}
