// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// BackupSourceApplyConfiguration represents a declarative configuration of the BackupSource type for use
// with apply.
//
// BackupSource contains the backup we need to restore from, plus some
// information that could be needed to correctly restore it.
type BackupSourceApplyConfiguration struct {
	corev1.LocalObjectReferenceApplyConfiguration `json:",inline"`
	// EndpointCA store the CA bundle of the barman endpoint.
	// Useful when using self-signed certificates to avoid
	// errors with certificate issuer and barman-cloud-wal-archive.
	EndpointCA *api.SecretKeySelector `json:"endpointCA,omitempty"`
}

// BackupSourceApplyConfiguration constructs a declarative configuration of the BackupSource type for use with
// apply.
func BackupSource() *BackupSourceApplyConfiguration {
	return &BackupSourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackupSourceApplyConfiguration) WithName(value string) *BackupSourceApplyConfiguration {
	b.LocalObjectReferenceApplyConfiguration.Name = &value
	return b
}

// WithEndpointCA sets the EndpointCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointCA field is set to the value of the last call.
func (b *BackupSourceApplyConfiguration) WithEndpointCA(value api.SecretKeySelector) *BackupSourceApplyConfiguration {
	b.EndpointCA = &value
	return b
}
