// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// BackupSpecApplyConfiguration represents a declarative configuration of the BackupSpec type for use
// with apply.
//
// BackupSpec defines the desired state of Backup
type BackupSpecApplyConfiguration struct {
	// The cluster to backup
	Cluster *corev1.LocalObjectReferenceApplyConfiguration `json:"cluster,omitempty"`
	// The policy to decide which instance should perform this backup. If empty,
	// it defaults to `cluster.spec.backup.target`.
	// Available options are empty string, `primary` and `prefer-standby`.
	// `primary` to have backups run always on primary instances,
	// `prefer-standby` to have backups run preferably on the most updated
	// standby, if available.
	Target *apiv1.BackupTarget `json:"target,omitempty"`
	// The backup method to be used, possible options are `barmanObjectStore`,
	// `volumeSnapshot`, `plugin` or `pgBackRest`. Defaults to: `pgBackRest`.
	Method *apiv1.BackupMethod `json:"method,omitempty"`
	// The pgBackRest backup type. Possible values are `full`, `diff` (differential),
	// or `incr` (incremental). Defaults to `full`. Only used when method is `pgBackRest`.
	PgBackRestBackupType *apiv1.PgBackRestBackupType `json:"pgBackRestBackupType,omitempty"`
	// Configuration parameters passed to the plugin managing this backup
	PluginConfiguration *BackupPluginConfigurationApplyConfiguration `json:"pluginConfiguration,omitempty"`
	// Whether the default type of backup with volume snapshots is
	// online/hot (`true`, default) or offline/cold (`false`)
	// Overrides the default setting specified in the cluster field '.spec.backup.volumeSnapshot.online'
	Online *bool `json:"online,omitempty"`
	// Configuration parameters to control the online/hot backup with volume snapshots
	// Overrides the default settings specified in the cluster '.backup.volumeSnapshot.onlineConfiguration' stanza
	OnlineConfiguration *OnlineConfigurationApplyConfiguration `json:"onlineConfiguration,omitempty"`
}

// BackupSpecApplyConfiguration constructs a declarative configuration of the BackupSpec type for use with
// apply.
func BackupSpec() *BackupSpecApplyConfiguration {
	return &BackupSpecApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithCluster(value *corev1.LocalObjectReferenceApplyConfiguration) *BackupSpecApplyConfiguration {
	b.Cluster = value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithTarget(value apiv1.BackupTarget) *BackupSpecApplyConfiguration {
	b.Target = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithMethod(value apiv1.BackupMethod) *BackupSpecApplyConfiguration {
	b.Method = &value
	return b
}

// WithPgBackRestBackupType sets the PgBackRestBackupType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBackRestBackupType field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithPgBackRestBackupType(value apiv1.PgBackRestBackupType) *BackupSpecApplyConfiguration {
	b.PgBackRestBackupType = &value
	return b
}

// WithPluginConfiguration sets the PluginConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PluginConfiguration field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithPluginConfiguration(value *BackupPluginConfigurationApplyConfiguration) *BackupSpecApplyConfiguration {
	b.PluginConfiguration = value
	return b
}

// WithOnline sets the Online field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Online field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithOnline(value bool) *BackupSpecApplyConfiguration {
	b.Online = &value
	return b
}

// WithOnlineConfiguration sets the OnlineConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnlineConfiguration field is set to the value of the last call.
func (b *BackupSpecApplyConfiguration) WithOnlineConfiguration(value *OnlineConfigurationApplyConfiguration) *BackupSpecApplyConfiguration {
	b.OnlineConfiguration = value
	return b
}
