// Code generated by controller-gen. DO NOT EDIT.

package v1

// BackupPluginConfigurationApplyConfiguration represents a declarative configuration of the BackupPluginConfiguration type for use
// with apply.
//
// BackupPluginConfiguration contains the backup configuration used by
// the backup plugin
type BackupPluginConfigurationApplyConfiguration struct {
	// Name is the name of the plugin managing this backup
	Name *string `json:"name,omitempty"`
	// Parameters are the configuration parameters passed to the backup
	// plugin for this backup
	Parameters map[string]string `json:"parameters,omitempty"`
}

// BackupPluginConfigurationApplyConfiguration constructs a declarative configuration of the BackupPluginConfiguration type for use with
// apply.
func BackupPluginConfiguration() *BackupPluginConfigurationApplyConfiguration {
	return &BackupPluginConfigurationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackupPluginConfigurationApplyConfiguration) WithName(value string) *BackupPluginConfigurationApplyConfiguration {
	b.Name = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *BackupPluginConfigurationApplyConfiguration) WithParameters(entries map[string]string) *BackupPluginConfigurationApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}
