// Code generated by controller-gen. DO NOT EDIT.

package v1

// BackupSnapshotStatusApplyConfiguration represents a declarative configuration of the BackupSnapshotStatus type for use
// with apply.
//
// BackupSnapshotStatus the fields exclusive to the volumeSnapshot method backup
type BackupSnapshotStatusApplyConfiguration struct {
	// The elements list, populated with the gathered volume snapshots
	Elements []BackupSnapshotElementStatusApplyConfiguration `json:"elements,omitempty"`
}

// BackupSnapshotStatusApplyConfiguration constructs a declarative configuration of the BackupSnapshotStatus type for use with
// apply.
func BackupSnapshotStatus() *BackupSnapshotStatusApplyConfiguration {
	return &BackupSnapshotStatusApplyConfiguration{}
}

// WithElements adds the given value to the Elements field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Elements field.
func (b *BackupSnapshotStatusApplyConfiguration) WithElements(values ...*BackupSnapshotElementStatusApplyConfiguration) *BackupSnapshotStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithElements")
		}
		b.Elements = append(b.Elements, *values[i])
	}
	return b
}
