// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// BootstrapInitDBApplyConfiguration represents a declarative configuration of the BootstrapInitDB type for use
// with apply.
//
// BootstrapInitDB is the configuration of the bootstrap process when
// initdb is used
// Refer to the Bootstrap page of the documentation for more information.
type BootstrapInitDBApplyConfiguration struct {
	// Name of the database used by the application. Default: `app`.
	Database *string `json:"database,omitempty"`
	// Name of the owner of the database in the instance to be used
	// by applications. Defaults to the value of the `database` key.
	Owner *string `json:"owner,omitempty"`
	// Name of the secret containing the initial credentials for the
	// owner of the user database. If empty a new secret will be
	// created from scratch
	Secret *corev1.LocalObjectReferenceApplyConfiguration `json:"secret,omitempty"`
	// The list of options that must be passed to initdb when creating the cluster.
	//
	// Deprecated: This could lead to inconsistent configurations,
	// please use the explicit provided parameters instead.
	// If defined, explicit values will be ignored.
	Options []string `json:"options,omitempty"`
	// Whether the `-k` option should be passed to initdb,
	// enabling checksums on data pages (default: `false`)
	DataChecksums *bool `json:"dataChecksums,omitempty"`
	// The value to be passed as option `--encoding` for initdb (default:`UTF8`)
	Encoding *string `json:"encoding,omitempty"`
	// The value to be passed as option `--lc-collate` for initdb (default:`C`)
	LocaleCollate *string `json:"localeCollate,omitempty"`
	// The value to be passed as option `--lc-ctype` for initdb (default:`C`)
	LocaleCType *string `json:"localeCType,omitempty"`
	// Sets the default collation order and character classification in the new database.
	Locale *string `json:"locale,omitempty"`
	// This option sets the locale provider for databases created in the new cluster.
	// Available from PostgreSQL 16.
	LocaleProvider *string `json:"localeProvider,omitempty"`
	// Specifies the ICU locale when the ICU provider is used.
	// This option requires `localeProvider` to be set to `icu`.
	// Available from PostgreSQL 15.
	IcuLocale *string `json:"icuLocale,omitempty"`
	// Specifies additional collation rules to customize the behavior of the default collation.
	// This option requires `localeProvider` to be set to `icu`.
	// Available from PostgreSQL 16.
	IcuRules *string `json:"icuRules,omitempty"`
	// Specifies the locale name when the builtin provider is used.
	// This option requires `localeProvider` to be set to `builtin`.
	// Available from PostgreSQL 17.
	BuiltinLocale *string `json:"builtinLocale,omitempty"`
	// The value in megabytes (1 to 1024) to be passed to the `--wal-segsize`
	// option for initdb (default: empty, resulting in PostgreSQL default: 16MB)
	WalSegmentSize *int `json:"walSegmentSize,omitempty"`
	// List of SQL queries to be executed as a superuser in the `postgres`
	// database right after the cluster has been created - to be used with extreme care
	// (by default empty)
	PostInitSQL []string `json:"postInitSQL,omitempty"`
	// List of SQL queries to be executed as a superuser in the application
	// database right after the cluster has been created - to be used with extreme care
	// (by default empty)
	PostInitApplicationSQL []string `json:"postInitApplicationSQL,omitempty"`
	// List of SQL queries to be executed as a superuser in the `template1`
	// database right after the cluster has been created - to be used with extreme care
	// (by default empty)
	PostInitTemplateSQL []string `json:"postInitTemplateSQL,omitempty"`
	// Bootstraps the new cluster by importing data from an existing PostgreSQL
	// instance using logical backup (`pg_dump` and `pg_restore`)
	Import *ImportApplyConfiguration `json:"import,omitempty"`
	// List of references to ConfigMaps or Secrets containing SQL files
	// to be executed as a superuser in the application database right after
	// the cluster has been created. The references are processed in a specific order:
	// first, all Secrets are processed, followed by all ConfigMaps.
	// Within each group, the processing order follows the sequence specified
	// in their respective arrays.
	// (by default empty)
	PostInitApplicationSQLRefs *SQLRefsApplyConfiguration `json:"postInitApplicationSQLRefs,omitempty"`
	// List of references to ConfigMaps or Secrets containing SQL files
	// to be executed as a superuser in the `template1` database right after
	// the cluster has been created. The references are processed in a specific order:
	// first, all Secrets are processed, followed by all ConfigMaps.
	// Within each group, the processing order follows the sequence specified
	// in their respective arrays.
	// (by default empty)
	PostInitTemplateSQLRefs *SQLRefsApplyConfiguration `json:"postInitTemplateSQLRefs,omitempty"`
	// List of references to ConfigMaps or Secrets containing SQL files
	// to be executed as a superuser in the `postgres` database right after
	// the cluster has been created. The references are processed in a specific order:
	// first, all Secrets are processed, followed by all ConfigMaps.
	// Within each group, the processing order follows the sequence specified
	// in their respective arrays.
	// (by default empty)
	PostInitSQLRefs *SQLRefsApplyConfiguration `json:"postInitSQLRefs,omitempty"`
}

// BootstrapInitDBApplyConfiguration constructs a declarative configuration of the BootstrapInitDB type for use with
// apply.
func BootstrapInitDB() *BootstrapInitDBApplyConfiguration {
	return &BootstrapInitDBApplyConfiguration{}
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithDatabase(value string) *BootstrapInitDBApplyConfiguration {
	b.Database = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithOwner(value string) *BootstrapInitDBApplyConfiguration {
	b.Owner = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *BootstrapInitDBApplyConfiguration {
	b.Secret = value
	return b
}

// WithOptions adds the given value to the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Options field.
func (b *BootstrapInitDBApplyConfiguration) WithOptions(values ...string) *BootstrapInitDBApplyConfiguration {
	for i := range values {
		b.Options = append(b.Options, values[i])
	}
	return b
}

// WithDataChecksums sets the DataChecksums field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataChecksums field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithDataChecksums(value bool) *BootstrapInitDBApplyConfiguration {
	b.DataChecksums = &value
	return b
}

// WithEncoding sets the Encoding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encoding field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithEncoding(value string) *BootstrapInitDBApplyConfiguration {
	b.Encoding = &value
	return b
}

// WithLocaleCollate sets the LocaleCollate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocaleCollate field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithLocaleCollate(value string) *BootstrapInitDBApplyConfiguration {
	b.LocaleCollate = &value
	return b
}

// WithLocaleCType sets the LocaleCType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocaleCType field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithLocaleCType(value string) *BootstrapInitDBApplyConfiguration {
	b.LocaleCType = &value
	return b
}

// WithLocale sets the Locale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Locale field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithLocale(value string) *BootstrapInitDBApplyConfiguration {
	b.Locale = &value
	return b
}

// WithLocaleProvider sets the LocaleProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocaleProvider field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithLocaleProvider(value string) *BootstrapInitDBApplyConfiguration {
	b.LocaleProvider = &value
	return b
}

// WithIcuLocale sets the IcuLocale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcuLocale field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithIcuLocale(value string) *BootstrapInitDBApplyConfiguration {
	b.IcuLocale = &value
	return b
}

// WithIcuRules sets the IcuRules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcuRules field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithIcuRules(value string) *BootstrapInitDBApplyConfiguration {
	b.IcuRules = &value
	return b
}

// WithBuiltinLocale sets the BuiltinLocale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BuiltinLocale field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithBuiltinLocale(value string) *BootstrapInitDBApplyConfiguration {
	b.BuiltinLocale = &value
	return b
}

// WithWalSegmentSize sets the WalSegmentSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WalSegmentSize field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithWalSegmentSize(value int) *BootstrapInitDBApplyConfiguration {
	b.WalSegmentSize = &value
	return b
}

// WithPostInitSQL adds the given value to the PostInitSQL field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PostInitSQL field.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitSQL(values ...string) *BootstrapInitDBApplyConfiguration {
	for i := range values {
		b.PostInitSQL = append(b.PostInitSQL, values[i])
	}
	return b
}

// WithPostInitApplicationSQL adds the given value to the PostInitApplicationSQL field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PostInitApplicationSQL field.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitApplicationSQL(values ...string) *BootstrapInitDBApplyConfiguration {
	for i := range values {
		b.PostInitApplicationSQL = append(b.PostInitApplicationSQL, values[i])
	}
	return b
}

// WithPostInitTemplateSQL adds the given value to the PostInitTemplateSQL field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PostInitTemplateSQL field.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitTemplateSQL(values ...string) *BootstrapInitDBApplyConfiguration {
	for i := range values {
		b.PostInitTemplateSQL = append(b.PostInitTemplateSQL, values[i])
	}
	return b
}

// WithImport sets the Import field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Import field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithImport(value *ImportApplyConfiguration) *BootstrapInitDBApplyConfiguration {
	b.Import = value
	return b
}

// WithPostInitApplicationSQLRefs sets the PostInitApplicationSQLRefs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostInitApplicationSQLRefs field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitApplicationSQLRefs(value *SQLRefsApplyConfiguration) *BootstrapInitDBApplyConfiguration {
	b.PostInitApplicationSQLRefs = value
	return b
}

// WithPostInitTemplateSQLRefs sets the PostInitTemplateSQLRefs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostInitTemplateSQLRefs field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitTemplateSQLRefs(value *SQLRefsApplyConfiguration) *BootstrapInitDBApplyConfiguration {
	b.PostInitTemplateSQLRefs = value
	return b
}

// WithPostInitSQLRefs sets the PostInitSQLRefs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostInitSQLRefs field is set to the value of the last call.
func (b *BootstrapInitDBApplyConfiguration) WithPostInitSQLRefs(value *SQLRefsApplyConfiguration) *BootstrapInitDBApplyConfiguration {
	b.PostInitSQLRefs = value
	return b
}
