// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// BootstrapPgBaseBackupApplyConfiguration represents a declarative configuration of the BootstrapPgBaseBackup type for use
// with apply.
//
// BootstrapPgBaseBackup contains the configuration required to take
// a physical backup of an existing PostgreSQL cluster
type BootstrapPgBaseBackupApplyConfiguration struct {
	// The name of the server of which we need to take a physical backup
	Source *string `json:"source,omitempty"`
	// Name of the database used by the application. Default: `app`.
	Database *string `json:"database,omitempty"`
	// Name of the owner of the database in the instance to be used
	// by applications. Defaults to the value of the `database` key.
	Owner *string `json:"owner,omitempty"`
	// Name of the secret containing the initial credentials for the
	// owner of the user database. If empty a new secret will be
	// created from scratch
	Secret *corev1.LocalObjectReferenceApplyConfiguration `json:"secret,omitempty"`
}

// BootstrapPgBaseBackupApplyConfiguration constructs a declarative configuration of the BootstrapPgBaseBackup type for use with
// apply.
func BootstrapPgBaseBackup() *BootstrapPgBaseBackupApplyConfiguration {
	return &BootstrapPgBaseBackupApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *BootstrapPgBaseBackupApplyConfiguration) WithSource(value string) *BootstrapPgBaseBackupApplyConfiguration {
	b.Source = &value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *BootstrapPgBaseBackupApplyConfiguration) WithDatabase(value string) *BootstrapPgBaseBackupApplyConfiguration {
	b.Database = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *BootstrapPgBaseBackupApplyConfiguration) WithOwner(value string) *BootstrapPgBaseBackupApplyConfiguration {
	b.Owner = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BootstrapPgBaseBackupApplyConfiguration) WithSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *BootstrapPgBaseBackupApplyConfiguration {
	b.Secret = value
	return b
}
