// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// BootstrapConfigurationApplyConfiguration represents a declarative configuration of the BootstrapConfiguration type for use
// with apply.
//
// BootstrapConfiguration contains information about how to create the PostgreSQL
// cluster. Only a single bootstrap method can be defined among the supported
// ones. `initdb` will be used as the bootstrap method if left
// unspecified. Refer to the Bootstrap page of the documentation for more
// information.
type BootstrapConfigurationApplyConfiguration struct {
	// Bootstrap the cluster via initdb
	InitDB *BootstrapInitDBApplyConfiguration `json:"initdb,omitempty"`
	// Bootstrap the cluster from a backup
	Recovery *BootstrapRecoveryApplyConfiguration `json:"recovery,omitempty"`
	// Bootstrap the cluster taking a physical backup of another compatible
	// PostgreSQL instance
	PgBaseBackup *BootstrapPgBaseBackupApplyConfiguration `json:"pg_basebackup,omitempty"`
	// Skip bootstrap entirely. The instance manager will wait for PGDATA
	// to appear from an external source (e.g. NVMe-oF mount).
	Noop *apiv1.BootstrapNoop `json:"noop,omitempty"`
}

// BootstrapConfigurationApplyConfiguration constructs a declarative configuration of the BootstrapConfiguration type for use with
// apply.
func BootstrapConfiguration() *BootstrapConfigurationApplyConfiguration {
	return &BootstrapConfigurationApplyConfiguration{}
}

// WithInitDB sets the InitDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitDB field is set to the value of the last call.
func (b *BootstrapConfigurationApplyConfiguration) WithInitDB(value *BootstrapInitDBApplyConfiguration) *BootstrapConfigurationApplyConfiguration {
	b.InitDB = value
	return b
}

// WithRecovery sets the Recovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Recovery field is set to the value of the last call.
func (b *BootstrapConfigurationApplyConfiguration) WithRecovery(value *BootstrapRecoveryApplyConfiguration) *BootstrapConfigurationApplyConfiguration {
	b.Recovery = value
	return b
}

// WithPgBaseBackup sets the PgBaseBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBaseBackup field is set to the value of the last call.
func (b *BootstrapConfigurationApplyConfiguration) WithPgBaseBackup(value *BootstrapPgBaseBackupApplyConfiguration) *BootstrapConfigurationApplyConfiguration {
	b.PgBaseBackup = value
	return b
}

// WithNoop sets the Noop field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Noop field is set to the value of the last call.
func (b *BootstrapConfigurationApplyConfiguration) WithNoop(value apiv1.BootstrapNoop) *BootstrapConfigurationApplyConfiguration {
	b.Noop = &value
	return b
}
