// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// BootstrapRecoveryApplyConfiguration represents a declarative configuration of the BootstrapRecovery type for use
// with apply.
//
// BootstrapRecovery contains the configuration required to restore
// from an existing cluster using 3 methodologies: external cluster,
// volume snapshots or backup objects. Full recovery and Point-In-Time
// Recovery are supported.
// The method can be also be used to create clusters in continuous recovery
// (replica clusters), also supporting cascading replication when `instances` >
// 1. Once the cluster exits recovery, the password for the superuser
// will be changed through the provided secret.
// Refer to the Bootstrap page of the documentation for more information.
type BootstrapRecoveryApplyConfiguration struct {
	// The backup object containing the physical base backup from which to
	// initiate the recovery procedure.
	// Mutually exclusive with `source` and `volumeSnapshots`.
	Backup *BackupSourceApplyConfiguration `json:"backup,omitempty"`
	// The external cluster whose backup we will restore. This is also
	// used as the name of the folder under which the backup is stored,
	// so it must be set to the name of the source cluster
	// Mutually exclusive with `backup`.
	Source *string `json:"source,omitempty"`
	// The static PVC data source(s) from which to initiate the
	// recovery procedure. Currently supporting `VolumeSnapshot`
	// and `PersistentVolumeClaim` resources that map an existing
	// PVC group, compatible with CloudNativePG, and taken with
	// a cold backup copy on a fenced Postgres instance (limitation
	// which will be removed in the future when online backup
	// will be implemented).
	// Mutually exclusive with `backup`.
	VolumeSnapshots *DataSourceApplyConfiguration `json:"volumeSnapshots,omitempty"`
	// By default, the recovery process applies all the available
	// WAL files in the archive (full recovery). However, you can also
	// end the recovery as soon as a consistent state is reached or
	// recover to a point-in-time (PITR) by specifying a `RecoveryTarget` object,
	// as expected by PostgreSQL (i.e., timestamp, transaction Id, LSN, ...).
	// More info: https://www.postgresql.org/docs/current/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET
	RecoveryTarget *RecoveryTargetApplyConfiguration `json:"recoveryTarget,omitempty"`
	// Name of the database used by the application. Default: `app`.
	Database *string `json:"database,omitempty"`
	// Name of the owner of the database in the instance to be used
	// by applications. Defaults to the value of the `database` key.
	Owner *string `json:"owner,omitempty"`
	// Name of the secret containing the initial credentials for the
	// owner of the user database. If empty a new secret will be
	// created from scratch
	Secret *corev1.LocalObjectReferenceApplyConfiguration `json:"secret,omitempty"`
}

// BootstrapRecoveryApplyConfiguration constructs a declarative configuration of the BootstrapRecovery type for use with
// apply.
func BootstrapRecovery() *BootstrapRecoveryApplyConfiguration {
	return &BootstrapRecoveryApplyConfiguration{}
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithBackup(value *BackupSourceApplyConfiguration) *BootstrapRecoveryApplyConfiguration {
	b.Backup = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithSource(value string) *BootstrapRecoveryApplyConfiguration {
	b.Source = &value
	return b
}

// WithVolumeSnapshots sets the VolumeSnapshots field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSnapshots field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithVolumeSnapshots(value *DataSourceApplyConfiguration) *BootstrapRecoveryApplyConfiguration {
	b.VolumeSnapshots = value
	return b
}

// WithRecoveryTarget sets the RecoveryTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryTarget field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithRecoveryTarget(value *RecoveryTargetApplyConfiguration) *BootstrapRecoveryApplyConfiguration {
	b.RecoveryTarget = value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithDatabase(value string) *BootstrapRecoveryApplyConfiguration {
	b.Database = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithOwner(value string) *BootstrapRecoveryApplyConfiguration {
	b.Owner = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BootstrapRecoveryApplyConfiguration) WithSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *BootstrapRecoveryApplyConfiguration {
	b.Secret = value
	return b
}
