// Code generated by controller-gen. DO NOT EDIT.

package v1

// CertificatesConfigurationApplyConfiguration represents a declarative configuration of the CertificatesConfiguration type for use
// with apply.
//
// CertificatesConfiguration contains the needed configurations to handle server certificates.
type CertificatesConfigurationApplyConfiguration struct {
	// The secret containing the Server CA certificate. If not defined, a new secret will be created
	// with a self-signed CA and will be used to generate the TLS certificate ServerTLSSecret.<br />
	// <br />
	// Contains:<br />
	// <br />
	// - `ca.crt`: CA that should be used to validate the server certificate,
	// used as `sslrootcert` in client connection strings.<br />
	// - `ca.key`: key used to generate Server SSL certs, if ServerTLSSecret is provided,
	// this can be omitted.<br />
	ServerCASecret *string `json:"serverCASecret,omitempty"`
	// The secret of type kubernetes.io/tls containing the server TLS certificate and key that will be set as
	// `ssl_cert_file` and `ssl_key_file` so that clients can connect to postgres securely.
	// If not defined, ServerCASecret must provide also `ca.key` and a new secret will be
	// created using the provided CA.
	ServerTLSSecret *string `json:"serverTLSSecret,omitempty"`
	// The secret of type kubernetes.io/tls containing the client certificate to authenticate as
	// the `streaming_replica` user.
	// If not defined, ClientCASecret must provide also `ca.key`, and a new secret will be
	// created using the provided CA.
	ReplicationTLSSecret *string `json:"replicationTLSSecret,omitempty"`
	// The secret containing the Client CA certificate. If not defined, a new secret will be created
	// with a self-signed CA and will be used to generate all the client certificates.<br />
	// <br />
	// Contains:<br />
	// <br />
	// - `ca.crt`: CA that should be used to validate the client certificates,
	// used as `ssl_ca_file` of all the instances.<br />
	// - `ca.key`: key used to generate client certificates, if ReplicationTLSSecret is provided,
	// this can be omitted.<br />
	ClientCASecret *string `json:"clientCASecret,omitempty"`
	// The list of the server alternative DNS names to be added to the generated server TLS certificates, when required.
	ServerAltDNSNames []string `json:"serverAltDNSNames,omitempty"`
}

// CertificatesConfigurationApplyConfiguration constructs a declarative configuration of the CertificatesConfiguration type for use with
// apply.
func CertificatesConfiguration() *CertificatesConfigurationApplyConfiguration {
	return &CertificatesConfigurationApplyConfiguration{}
}

// WithServerCASecret sets the ServerCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerCASecret field is set to the value of the last call.
func (b *CertificatesConfigurationApplyConfiguration) WithServerCASecret(value string) *CertificatesConfigurationApplyConfiguration {
	b.ServerCASecret = &value
	return b
}

// WithServerTLSSecret sets the ServerTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerTLSSecret field is set to the value of the last call.
func (b *CertificatesConfigurationApplyConfiguration) WithServerTLSSecret(value string) *CertificatesConfigurationApplyConfiguration {
	b.ServerTLSSecret = &value
	return b
}

// WithReplicationTLSSecret sets the ReplicationTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicationTLSSecret field is set to the value of the last call.
func (b *CertificatesConfigurationApplyConfiguration) WithReplicationTLSSecret(value string) *CertificatesConfigurationApplyConfiguration {
	b.ReplicationTLSSecret = &value
	return b
}

// WithClientCASecret sets the ClientCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCASecret field is set to the value of the last call.
func (b *CertificatesConfigurationApplyConfiguration) WithClientCASecret(value string) *CertificatesConfigurationApplyConfiguration {
	b.ClientCASecret = &value
	return b
}

// WithServerAltDNSNames adds the given value to the ServerAltDNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServerAltDNSNames field.
func (b *CertificatesConfigurationApplyConfiguration) WithServerAltDNSNames(values ...string) *CertificatesConfigurationApplyConfiguration {
	for i := range values {
		b.ServerAltDNSNames = append(b.ServerAltDNSNames, values[i])
	}
	return b
}
