// Code generated by controller-gen. DO NOT EDIT.

package v1

// CertificatesStatusApplyConfiguration represents a declarative configuration of the CertificatesStatus type for use
// with apply.
//
// CertificatesStatus contains configuration certificates and related expiration dates.
type CertificatesStatusApplyConfiguration struct {
	// Needed configurations to handle server certificates, initialized with default values, if needed.
	CertificatesConfigurationApplyConfiguration `json:",inline"`
	// Expiration dates for all certificates.
	Expirations map[string]string `json:"expirations,omitempty"`
}

// CertificatesStatusApplyConfiguration constructs a declarative configuration of the CertificatesStatus type for use with
// apply.
func CertificatesStatus() *CertificatesStatusApplyConfiguration {
	return &CertificatesStatusApplyConfiguration{}
}

// WithServerCASecret sets the ServerCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerCASecret field is set to the value of the last call.
func (b *CertificatesStatusApplyConfiguration) WithServerCASecret(value string) *CertificatesStatusApplyConfiguration {
	b.CertificatesConfigurationApplyConfiguration.ServerCASecret = &value
	return b
}

// WithServerTLSSecret sets the ServerTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerTLSSecret field is set to the value of the last call.
func (b *CertificatesStatusApplyConfiguration) WithServerTLSSecret(value string) *CertificatesStatusApplyConfiguration {
	b.CertificatesConfigurationApplyConfiguration.ServerTLSSecret = &value
	return b
}

// WithReplicationTLSSecret sets the ReplicationTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicationTLSSecret field is set to the value of the last call.
func (b *CertificatesStatusApplyConfiguration) WithReplicationTLSSecret(value string) *CertificatesStatusApplyConfiguration {
	b.CertificatesConfigurationApplyConfiguration.ReplicationTLSSecret = &value
	return b
}

// WithClientCASecret sets the ClientCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCASecret field is set to the value of the last call.
func (b *CertificatesStatusApplyConfiguration) WithClientCASecret(value string) *CertificatesStatusApplyConfiguration {
	b.CertificatesConfigurationApplyConfiguration.ClientCASecret = &value
	return b
}

// WithServerAltDNSNames adds the given value to the ServerAltDNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServerAltDNSNames field.
func (b *CertificatesStatusApplyConfiguration) WithServerAltDNSNames(values ...string) *CertificatesStatusApplyConfiguration {
	for i := range values {
		b.CertificatesConfigurationApplyConfiguration.ServerAltDNSNames = append(b.CertificatesConfigurationApplyConfiguration.ServerAltDNSNames, values[i])
	}
	return b
}

// WithExpirations puts the entries into the Expirations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Expirations field,
// overwriting an existing map entries in Expirations field with the same key.
func (b *CertificatesStatusApplyConfiguration) WithExpirations(entries map[string]string) *CertificatesStatusApplyConfiguration {
	if b.Expirations == nil && len(entries) > 0 {
		b.Expirations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Expirations[k] = v
	}
	return b
}
