// Code generated by controller-gen. DO NOT EDIT.

package v1

// ClusterMonitoringTLSConfigurationApplyConfiguration represents a declarative configuration of the ClusterMonitoringTLSConfiguration type for use
// with apply.
//
// ClusterMonitoringTLSConfiguration is the type containing the TLS configuration
// for the cluster's monitoring
type ClusterMonitoringTLSConfigurationApplyConfiguration struct {
	// Enable TLS for the monitoring endpoint.
	// Changing this option will force a rollout of all instances.
	Enabled *bool `json:"enabled,omitempty"`
}

// ClusterMonitoringTLSConfigurationApplyConfiguration constructs a declarative configuration of the ClusterMonitoringTLSConfiguration type for use with
// apply.
func ClusterMonitoringTLSConfiguration() *ClusterMonitoringTLSConfigurationApplyConfiguration {
	return &ClusterMonitoringTLSConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ClusterMonitoringTLSConfigurationApplyConfiguration) WithEnabled(value bool) *ClusterMonitoringTLSConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}
