// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterStatusApplyConfiguration represents a declarative configuration of the ClusterStatus type for use
// with apply.
//
// ClusterStatus defines the observed state of a PostgreSQL cluster managed by
// CloudNativePG.
type ClusterStatusApplyConfiguration struct {
	// The total number of PVC Groups detected in the cluster. It may differ from the number of existing instance pods.
	Instances *int `json:"instances,omitempty"`
	// The total number of ready instances in the cluster. It is equal to the number of ready instance pods.
	ReadyInstances *int `json:"readyInstances,omitempty"`
	// InstancesStatus indicates in which status the instances are
	InstancesStatus map[apiv1.PodStatus][]string `json:"instancesStatus,omitempty"`
	// The reported state of the instances during the last reconciliation loop
	InstancesReportedState map[apiv1.PodName]InstanceReportedStateApplyConfiguration `json:"instancesReportedState,omitempty"`
	// ManagedRolesStatus reports the state of the managed roles in the cluster
	ManagedRolesStatus *ManagedRolesApplyConfiguration `json:"managedRolesStatus,omitempty"`
	// TablespacesStatus reports the state of the declarative tablespaces in the cluster
	TablespacesStatus []TablespaceStateApplyConfiguration `json:"tablespacesStatus,omitempty"`
	// The timeline of the Postgres cluster
	TimelineID *int `json:"timelineID,omitempty"`
	// Instances topology.
	Topology *TopologyApplyConfiguration `json:"topology,omitempty"`
	// ID of the latest generated node (used to avoid node name clashing)
	LatestGeneratedNode *int `json:"latestGeneratedNode,omitempty"`
	// Current primary instance
	CurrentPrimary *string `json:"currentPrimary,omitempty"`
	// Target primary instance, this is different from the previous one
	// during a switchover or a failover
	TargetPrimary *string `json:"targetPrimary,omitempty"`
	// LastPromotionToken is the last verified promotion token that
	// was used to promote a replica cluster
	LastPromotionToken *string `json:"lastPromotionToken,omitempty"`
	// How many PVCs have been created by this cluster
	PVCCount *int32 `json:"pvcCount,omitempty"`
	// How many Jobs have been created by this cluster
	JobCount *int32 `json:"jobCount,omitempty"`
	// List of all the PVCs created by this cluster and still available
	// which are not attached to a Pod
	DanglingPVC []string `json:"danglingPVC,omitempty"`
	// List of all the PVCs that have ResizingPVC condition.
	ResizingPVC []string `json:"resizingPVC,omitempty"`
	// List of all the PVCs that are being initialized by this cluster
	InitializingPVC []string `json:"initializingPVC,omitempty"`
	// List of all the PVCs not dangling nor initializing
	HealthyPVC []string `json:"healthyPVC,omitempty"`
	// List of all the PVCs that are unusable because another PVC is missing
	UnusablePVC []string `json:"unusablePVC,omitempty"`
	// Current write pod
	WriteService *string `json:"writeService,omitempty"`
	// Current list of read pods
	ReadService *string `json:"readService,omitempty"`
	// Current phase of the cluster
	Phase *string `json:"phase,omitempty"`
	// Reason for the current phase
	PhaseReason *string `json:"phaseReason,omitempty"`
	// The list of resource versions of the secrets
	// managed by the operator. Every change here is done in the
	// interest of the instance manager, which will refresh the
	// secret data
	SecretsResourceVersion *SecretsResourceVersionApplyConfiguration `json:"secretsResourceVersion,omitempty"`
	// The list of resource versions of the configmaps,
	// managed by the operator. Every change here is done in the
	// interest of the instance manager, which will refresh the
	// configmap data
	ConfigMapResourceVersion *ConfigMapResourceVersionApplyConfiguration `json:"configMapResourceVersion,omitempty"`
	// The configuration for the CA and related certificates, initialized with defaults.
	Certificates *CertificatesStatusApplyConfiguration `json:"certificates,omitempty"`
	// The first recoverability point, stored as a date in RFC3339 format.
	// This field is calculated from the content of FirstRecoverabilityPointByMethod.
	//
	// Deprecated: the field is not set for backup plugins.
	FirstRecoverabilityPoint *string `json:"firstRecoverabilityPoint,omitempty"`
	// The first recoverability point, stored as a date in RFC3339 format, per backup method type.
	//
	// Deprecated: the field is not set for backup plugins.
	FirstRecoverabilityPointByMethod map[apiv1.BackupMethod]metav1.Time `json:"firstRecoverabilityPointByMethod,omitempty"`
	// The latest point in time that can be recovered to, stored as a date
	// in RFC3339 format. Based on the last successfully archived WAL,
	// from pg_stat_archiver.last_archived_time on the primary instance.
	LastRecoverabilityPoint *string `json:"lastRecoverabilityPoint,omitempty"`
	// Last successful backup, stored as a date in RFC3339 format.
	// This field is calculated from the content of LastSuccessfulBackupByMethod.
	//
	// Deprecated: the field is not set for backup plugins.
	LastSuccessfulBackup *string `json:"lastSuccessfulBackup,omitempty"`
	// Last successful backup, stored as a date in RFC3339 format, per backup method type.
	//
	// Deprecated: the field is not set for backup plugins.
	LastSuccessfulBackupByMethod map[apiv1.BackupMethod]metav1.Time `json:"lastSuccessfulBackupByMethod,omitempty"`
	// Last failed backup, stored as a date in RFC3339 format.
	//
	// Deprecated: the field is not set for backup plugins.
	LastFailedBackup *string `json:"lastFailedBackup,omitempty"`
	// The commit hash number of which this operator running
	CommitHash *string `json:"cloudNativePGCommitHash,omitempty"`
	// The timestamp when the last actual promotion to primary has occurred
	CurrentPrimaryTimestamp *string `json:"currentPrimaryTimestamp,omitempty"`
	// The timestamp when the primary was detected to be unhealthy
	// This field is reported when `.spec.failoverDelay` is populated or during online upgrades
	CurrentPrimaryFailingSinceTimestamp *string `json:"currentPrimaryFailingSinceTimestamp,omitempty"`
	// The timestamp when the last request for a new primary has occurred
	TargetPrimaryTimestamp *string `json:"targetPrimaryTimestamp,omitempty"`
	// The integration needed by poolers referencing the cluster
	PoolerIntegrations *PoolerIntegrationsApplyConfiguration `json:"poolerIntegrations,omitempty"`
	// The hash of the binary of the operator
	OperatorHash *string `json:"cloudNativePGOperatorHash,omitempty"`
	// AvailableArchitectures reports the available architectures of a cluster
	AvailableArchitectures []AvailableArchitectureApplyConfiguration `json:"availableArchitectures,omitempty"`
	// Conditions for cluster object
	Conditions []applyconfigurationsmetav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// List of instance names in the cluster
	InstanceNames []string `json:"instanceNames,omitempty"`
	// OnlineUpdateEnabled shows if the online upgrade is enabled inside the cluster
	OnlineUpdateEnabled *bool `json:"onlineUpdateEnabled,omitempty"`
	// Image contains the image name used by the pods
	Image *string `json:"image,omitempty"`
	// PGDataImageInfo contains the details of the latest image that has run on the current data directory.
	PGDataImageInfo *ImageInfoApplyConfiguration `json:"pgDataImageInfo,omitempty"`
	// PluginStatus is the status of the loaded plugins
	PluginStatus []PluginStatusApplyConfiguration `json:"pluginStatus,omitempty"`
	// SwitchReplicaClusterStatus is the status of the switch to replica cluster
	SwitchReplicaClusterStatus *SwitchReplicaClusterStatusApplyConfiguration `json:"switchReplicaClusterStatus,omitempty"`
	// DemotionToken is a JSON token containing the information
	// from pg_controldata such as Database system identifier, Latest checkpoint's
	// TimeLineID, Latest checkpoint's REDO location, Latest checkpoint's REDO
	// WAL file, and Time of latest checkpoint
	DemotionToken *string `json:"demotionToken,omitempty"`
	// SystemID is the latest detected PostgreSQL SystemID
	SystemID *string `json:"systemID,omitempty"`
}

// ClusterStatusApplyConfiguration constructs a declarative configuration of the ClusterStatus type for use with
// apply.
func ClusterStatus() *ClusterStatusApplyConfiguration {
	return &ClusterStatusApplyConfiguration{}
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithInstances(value int) *ClusterStatusApplyConfiguration {
	b.Instances = &value
	return b
}

// WithReadyInstances sets the ReadyInstances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyInstances field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithReadyInstances(value int) *ClusterStatusApplyConfiguration {
	b.ReadyInstances = &value
	return b
}

// WithInstancesStatus puts the entries into the InstancesStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InstancesStatus field,
// overwriting an existing map entries in InstancesStatus field with the same key.
func (b *ClusterStatusApplyConfiguration) WithInstancesStatus(entries map[apiv1.PodStatus][]string) *ClusterStatusApplyConfiguration {
	if b.InstancesStatus == nil && len(entries) > 0 {
		b.InstancesStatus = make(map[apiv1.PodStatus][]string, len(entries))
	}
	for k, v := range entries {
		b.InstancesStatus[k] = v
	}
	return b
}

// WithInstancesReportedState puts the entries into the InstancesReportedState field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InstancesReportedState field,
// overwriting an existing map entries in InstancesReportedState field with the same key.
func (b *ClusterStatusApplyConfiguration) WithInstancesReportedState(entries map[apiv1.PodName]InstanceReportedStateApplyConfiguration) *ClusterStatusApplyConfiguration {
	if b.InstancesReportedState == nil && len(entries) > 0 {
		b.InstancesReportedState = make(map[apiv1.PodName]InstanceReportedStateApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.InstancesReportedState[k] = v
	}
	return b
}

// WithManagedRolesStatus sets the ManagedRolesStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagedRolesStatus field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithManagedRolesStatus(value *ManagedRolesApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.ManagedRolesStatus = value
	return b
}

// WithTablespacesStatus adds the given value to the TablespacesStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TablespacesStatus field.
func (b *ClusterStatusApplyConfiguration) WithTablespacesStatus(values ...*TablespaceStateApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTablespacesStatus")
		}
		b.TablespacesStatus = append(b.TablespacesStatus, *values[i])
	}
	return b
}

// WithTimelineID sets the TimelineID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimelineID field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithTimelineID(value int) *ClusterStatusApplyConfiguration {
	b.TimelineID = &value
	return b
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithTopology(value *TopologyApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.Topology = value
	return b
}

// WithLatestGeneratedNode sets the LatestGeneratedNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LatestGeneratedNode field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLatestGeneratedNode(value int) *ClusterStatusApplyConfiguration {
	b.LatestGeneratedNode = &value
	return b
}

// WithCurrentPrimary sets the CurrentPrimary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentPrimary field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithCurrentPrimary(value string) *ClusterStatusApplyConfiguration {
	b.CurrentPrimary = &value
	return b
}

// WithTargetPrimary sets the TargetPrimary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPrimary field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithTargetPrimary(value string) *ClusterStatusApplyConfiguration {
	b.TargetPrimary = &value
	return b
}

// WithLastPromotionToken sets the LastPromotionToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastPromotionToken field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLastPromotionToken(value string) *ClusterStatusApplyConfiguration {
	b.LastPromotionToken = &value
	return b
}

// WithPVCCount sets the PVCCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVCCount field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPVCCount(value int32) *ClusterStatusApplyConfiguration {
	b.PVCCount = &value
	return b
}

// WithJobCount sets the JobCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobCount field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithJobCount(value int32) *ClusterStatusApplyConfiguration {
	b.JobCount = &value
	return b
}

// WithDanglingPVC adds the given value to the DanglingPVC field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DanglingPVC field.
func (b *ClusterStatusApplyConfiguration) WithDanglingPVC(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.DanglingPVC = append(b.DanglingPVC, values[i])
	}
	return b
}

// WithResizingPVC adds the given value to the ResizingPVC field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResizingPVC field.
func (b *ClusterStatusApplyConfiguration) WithResizingPVC(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.ResizingPVC = append(b.ResizingPVC, values[i])
	}
	return b
}

// WithInitializingPVC adds the given value to the InitializingPVC field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitializingPVC field.
func (b *ClusterStatusApplyConfiguration) WithInitializingPVC(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.InitializingPVC = append(b.InitializingPVC, values[i])
	}
	return b
}

// WithHealthyPVC adds the given value to the HealthyPVC field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HealthyPVC field.
func (b *ClusterStatusApplyConfiguration) WithHealthyPVC(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.HealthyPVC = append(b.HealthyPVC, values[i])
	}
	return b
}

// WithUnusablePVC adds the given value to the UnusablePVC field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UnusablePVC field.
func (b *ClusterStatusApplyConfiguration) WithUnusablePVC(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.UnusablePVC = append(b.UnusablePVC, values[i])
	}
	return b
}

// WithWriteService sets the WriteService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WriteService field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithWriteService(value string) *ClusterStatusApplyConfiguration {
	b.WriteService = &value
	return b
}

// WithReadService sets the ReadService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadService field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithReadService(value string) *ClusterStatusApplyConfiguration {
	b.ReadService = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPhase(value string) *ClusterStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPhaseReason sets the PhaseReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PhaseReason field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPhaseReason(value string) *ClusterStatusApplyConfiguration {
	b.PhaseReason = &value
	return b
}

// WithSecretsResourceVersion sets the SecretsResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretsResourceVersion field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithSecretsResourceVersion(value *SecretsResourceVersionApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.SecretsResourceVersion = value
	return b
}

// WithConfigMapResourceVersion sets the ConfigMapResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapResourceVersion field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithConfigMapResourceVersion(value *ConfigMapResourceVersionApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.ConfigMapResourceVersion = value
	return b
}

// WithCertificates sets the Certificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificates field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithCertificates(value *CertificatesStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.Certificates = value
	return b
}

// WithFirstRecoverabilityPoint sets the FirstRecoverabilityPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirstRecoverabilityPoint field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithFirstRecoverabilityPoint(value string) *ClusterStatusApplyConfiguration {
	b.FirstRecoverabilityPoint = &value
	return b
}

// WithFirstRecoverabilityPointByMethod puts the entries into the FirstRecoverabilityPointByMethod field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the FirstRecoverabilityPointByMethod field,
// overwriting an existing map entries in FirstRecoverabilityPointByMethod field with the same key.
func (b *ClusterStatusApplyConfiguration) WithFirstRecoverabilityPointByMethod(entries map[apiv1.BackupMethod]metav1.Time) *ClusterStatusApplyConfiguration {
	if b.FirstRecoverabilityPointByMethod == nil && len(entries) > 0 {
		b.FirstRecoverabilityPointByMethod = make(map[apiv1.BackupMethod]metav1.Time, len(entries))
	}
	for k, v := range entries {
		b.FirstRecoverabilityPointByMethod[k] = v
	}
	return b
}

// WithLastRecoverabilityPoint sets the LastRecoverabilityPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRecoverabilityPoint field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLastRecoverabilityPoint(value string) *ClusterStatusApplyConfiguration {
	b.LastRecoverabilityPoint = &value
	return b
}

// WithLastSuccessfulBackup sets the LastSuccessfulBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulBackup field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLastSuccessfulBackup(value string) *ClusterStatusApplyConfiguration {
	b.LastSuccessfulBackup = &value
	return b
}

// WithLastSuccessfulBackupByMethod puts the entries into the LastSuccessfulBackupByMethod field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the LastSuccessfulBackupByMethod field,
// overwriting an existing map entries in LastSuccessfulBackupByMethod field with the same key.
func (b *ClusterStatusApplyConfiguration) WithLastSuccessfulBackupByMethod(entries map[apiv1.BackupMethod]metav1.Time) *ClusterStatusApplyConfiguration {
	if b.LastSuccessfulBackupByMethod == nil && len(entries) > 0 {
		b.LastSuccessfulBackupByMethod = make(map[apiv1.BackupMethod]metav1.Time, len(entries))
	}
	for k, v := range entries {
		b.LastSuccessfulBackupByMethod[k] = v
	}
	return b
}

// WithLastFailedBackup sets the LastFailedBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastFailedBackup field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLastFailedBackup(value string) *ClusterStatusApplyConfiguration {
	b.LastFailedBackup = &value
	return b
}

// WithCommitHash sets the CommitHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitHash field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithCommitHash(value string) *ClusterStatusApplyConfiguration {
	b.CommitHash = &value
	return b
}

// WithCurrentPrimaryTimestamp sets the CurrentPrimaryTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentPrimaryTimestamp field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithCurrentPrimaryTimestamp(value string) *ClusterStatusApplyConfiguration {
	b.CurrentPrimaryTimestamp = &value
	return b
}

// WithCurrentPrimaryFailingSinceTimestamp sets the CurrentPrimaryFailingSinceTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentPrimaryFailingSinceTimestamp field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithCurrentPrimaryFailingSinceTimestamp(value string) *ClusterStatusApplyConfiguration {
	b.CurrentPrimaryFailingSinceTimestamp = &value
	return b
}

// WithTargetPrimaryTimestamp sets the TargetPrimaryTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPrimaryTimestamp field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithTargetPrimaryTimestamp(value string) *ClusterStatusApplyConfiguration {
	b.TargetPrimaryTimestamp = &value
	return b
}

// WithPoolerIntegrations sets the PoolerIntegrations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolerIntegrations field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPoolerIntegrations(value *PoolerIntegrationsApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.PoolerIntegrations = value
	return b
}

// WithOperatorHash sets the OperatorHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatorHash field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithOperatorHash(value string) *ClusterStatusApplyConfiguration {
	b.OperatorHash = &value
	return b
}

// WithAvailableArchitectures adds the given value to the AvailableArchitectures field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailableArchitectures field.
func (b *ClusterStatusApplyConfiguration) WithAvailableArchitectures(values ...*AvailableArchitectureApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAvailableArchitectures")
		}
		b.AvailableArchitectures = append(b.AvailableArchitectures, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterStatusApplyConfiguration) WithConditions(values ...*applyconfigurationsmetav1.ConditionApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithInstanceNames adds the given value to the InstanceNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InstanceNames field.
func (b *ClusterStatusApplyConfiguration) WithInstanceNames(values ...string) *ClusterStatusApplyConfiguration {
	for i := range values {
		b.InstanceNames = append(b.InstanceNames, values[i])
	}
	return b
}

// WithOnlineUpdateEnabled sets the OnlineUpdateEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnlineUpdateEnabled field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithOnlineUpdateEnabled(value bool) *ClusterStatusApplyConfiguration {
	b.OnlineUpdateEnabled = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithImage(value string) *ClusterStatusApplyConfiguration {
	b.Image = &value
	return b
}

// WithPGDataImageInfo sets the PGDataImageInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PGDataImageInfo field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPGDataImageInfo(value *ImageInfoApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.PGDataImageInfo = value
	return b
}

// WithPluginStatus adds the given value to the PluginStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PluginStatus field.
func (b *ClusterStatusApplyConfiguration) WithPluginStatus(values ...*PluginStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPluginStatus")
		}
		b.PluginStatus = append(b.PluginStatus, *values[i])
	}
	return b
}

// WithSwitchReplicaClusterStatus sets the SwitchReplicaClusterStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchReplicaClusterStatus field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithSwitchReplicaClusterStatus(value *SwitchReplicaClusterStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.SwitchReplicaClusterStatus = value
	return b
}

// WithDemotionToken sets the DemotionToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemotionToken field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithDemotionToken(value string) *ClusterStatusApplyConfiguration {
	b.DemotionToken = &value
	return b
}

// WithSystemID sets the SystemID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemID field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithSystemID(value string) *ClusterStatusApplyConfiguration {
	b.SystemID = &value
	return b
}
