// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/api/core/v1"
	applyconfigurationscorev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ClusterSpecApplyConfiguration represents a declarative configuration of the ClusterSpec type for use
// with apply.
//
// ClusterSpec defines the desired state of a PostgreSQL cluster managed by
// CloudNativePG.
type ClusterSpecApplyConfiguration struct {
	// Description of this PostgreSQL cluster
	Description *string `json:"description,omitempty"`
	// Metadata that will be inherited by all objects related to the Cluster
	InheritedMetadata *EmbeddedObjectMetadataApplyConfiguration `json:"inheritedMetadata,omitempty"`
	// Name of the container image, supporting both tags (`<image>:<tag>`)
	// and digests for deterministic and repeatable deployments
	// (`<image>:<tag>@sha256:<digestValue>`)
	ImageName *string `json:"imageName,omitempty"`
	// Defines the major PostgreSQL version we want to use within an ImageCatalog
	ImageCatalogRef *ImageCatalogRefApplyConfiguration `json:"imageCatalogRef,omitempty"`
	// Image pull policy.
	// One of `Always`, `Never` or `IfNotPresent`.
	// If not defined, it defaults to `IfNotPresent`.
	// Cannot be updated.
	// More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
	ImagePullPolicy *corev1.PullPolicy `json:"imagePullPolicy,omitempty"`
	// If specified, the pod will be dispatched by specified Kubernetes
	// scheduler. If not specified, the pod will be dispatched by the default
	// scheduler. More info:
	// https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/
	SchedulerName *string `json:"schedulerName,omitempty"`
	// The UID of the `postgres` user inside the image, defaults to `26`
	PostgresUID *int64 `json:"postgresUID,omitempty"`
	// The GID of the `postgres` user inside the image, defaults to `26`
	PostgresGID *int64 `json:"postgresGID,omitempty"`
	// Number of instances required in the cluster
	Instances *int `json:"instances,omitempty"`
	// Minimum number of instances required in synchronous replication with the
	// primary. Undefined or 0 allow writes to complete when no standby is
	// available.
	MinSyncReplicas *int `json:"minSyncReplicas,omitempty"`
	// The target value for the synchronous replication quorum, that can be
	// decreased if the number of ready standbys is lower than this.
	// Undefined or 0 disable synchronous replication.
	MaxSyncReplicas *int `json:"maxSyncReplicas,omitempty"`
	// Configuration of the PostgreSQL server
	PostgresConfiguration *PostgresConfigurationApplyConfiguration `json:"postgresql,omitempty"`
	// Replication slots management configuration
	ReplicationSlots *ReplicationSlotsConfigurationApplyConfiguration `json:"replicationSlots,omitempty"`
	// Instructions to bootstrap this cluster
	Bootstrap *BootstrapConfigurationApplyConfiguration `json:"bootstrap,omitempty"`
	// Replica cluster configuration
	ReplicaCluster *ReplicaClusterConfigurationApplyConfiguration `json:"replica,omitempty"`
	// The secret containing the superuser password. If not defined a new
	// secret will be created with a randomly generated password
	SuperuserSecret *applyconfigurationscorev1.LocalObjectReferenceApplyConfiguration `json:"superuserSecret,omitempty"`
	// When this option is enabled, the operator will use the `SuperuserSecret`
	// to update the `postgres` user password (if the secret is
	// not present, the operator will automatically create one). When this
	// option is disabled, the operator will ignore the `SuperuserSecret` content, delete
	// it when automatically created, and then blank the password of the `postgres`
	// user by setting it to `NULL`. Disabled by default.
	EnableSuperuserAccess *bool `json:"enableSuperuserAccess,omitempty"`
	// The configuration for the CA and related certificates
	Certificates *CertificatesConfigurationApplyConfiguration `json:"certificates,omitempty"`
	// The list of pull secrets to be used to pull the images
	ImagePullSecrets []applyconfigurationscorev1.LocalObjectReferenceApplyConfiguration `json:"imagePullSecrets,omitempty"`
	// Configuration of the storage of the instances
	StorageConfiguration *StorageConfigurationApplyConfiguration `json:"storage,omitempty"`
	// Configure the generation of the service account
	ServiceAccountTemplate *ServiceAccountTemplateApplyConfiguration `json:"serviceAccountTemplate,omitempty"`
	// Name of an existing ServiceAccount in the same namespace to use for the cluster.
	// When specified, the operator will not create a new ServiceAccount
	// but will use the provided one. This is useful for sharing a single
	// ServiceAccount across multiple clusters (e.g., for cloud IAM configurations).
	// If not specified, a ServiceAccount will be created with the cluster name.
	// Mutually exclusive with ServiceAccountTemplate.
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// Configuration of the storage for PostgreSQL WAL (Write-Ahead Log)
	WalStorage *StorageConfigurationApplyConfiguration `json:"walStorage,omitempty"`
	// EphemeralVolumeSource allows the user to configure the source of ephemeral volumes.
	EphemeralVolumeSource *corev1.EphemeralVolumeSource `json:"ephemeralVolumeSource,omitempty"`
	// The time in seconds that is allowed for a PostgreSQL instance to
	// successfully start up (default 3600).
	// The startup probe failure threshold is derived from this value using the formula:
	// ceiling(startDelay / 10).
	MaxStartDelay *int32 `json:"startDelay,omitempty"`
	// The time in seconds that is allowed for a PostgreSQL instance to
	// gracefully shutdown (default 1800)
	MaxStopDelay *int32 `json:"stopDelay,omitempty"`
	// The time in seconds that controls the window of time reserved for the smart shutdown of Postgres to complete.
	// Make sure you reserve enough time for the operator to request a fast shutdown of Postgres
	// (that is: `stopDelay` - `smartShutdownTimeout`). Default is 180 seconds.
	SmartShutdownTimeout *int32 `json:"smartShutdownTimeout,omitempty"`
	// The time in seconds that is allowed for a primary PostgreSQL instance
	// to gracefully shutdown during a switchover.
	// Default value is 3600 seconds (1 hour).
	MaxSwitchoverDelay *int32 `json:"switchoverDelay,omitempty"`
	// The amount of time (in seconds) to wait before triggering a failover
	// after the primary PostgreSQL instance in the cluster was detected
	// to be unhealthy
	FailoverDelay *int32 `json:"failoverDelay,omitempty"`
	// LivenessProbeTimeout is the time (in seconds) that is allowed for a PostgreSQL instance
	// to successfully respond to the liveness probe (default 30).
	// The Liveness probe failure threshold is derived from this value using the formula:
	// ceiling(livenessProbe / 10).
	LivenessProbeTimeout *int32 `json:"livenessProbeTimeout,omitempty"`
	// Affinity/Anti-affinity rules for Pods
	Affinity *AffinityConfigurationApplyConfiguration `json:"affinity,omitempty"`
	// TopologySpreadConstraints specifies how to spread matching pods among the given topology.
	// More info:
	// https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
	TopologySpreadConstraints []corev1.TopologySpreadConstraint `json:"topologySpreadConstraints,omitempty"`
	// Resources requirements of every generated Pod. Please refer to
	// https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	// for more information.
	Resources *corev1.ResourceRequirements `json:"resources,omitempty"`
	// EphemeralVolumesSizeLimit allows the user to set the limits for the ephemeral
	// volumes
	EphemeralVolumesSizeLimit *EphemeralVolumesSizeLimitConfigurationApplyConfiguration `json:"ephemeralVolumesSizeLimit,omitempty"`
	// Name of the priority class which will be used in every generated Pod, if the PriorityClass
	// specified does not exist, the pod will not be able to schedule.  Please refer to
	// https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
	// for more information
	PriorityClassName *string `json:"priorityClassName,omitempty"`
	// Deployment strategy to follow to upgrade the primary server during a rolling
	// update procedure, after all replicas have been successfully updated:
	// it can be automated (`unsupervised` - default) or manual (`supervised`)
	PrimaryUpdateStrategy *apiv1.PrimaryUpdateStrategy `json:"primaryUpdateStrategy,omitempty"`
	// Method to follow to upgrade the primary server during a rolling
	// update procedure, after all replicas have been successfully updated:
	// it can be with a switchover (`switchover`) or in-place (`restart` - default).
	// Note: when using `switchover`, the operator will reject updates that change both
	// the image name and PostgreSQL configuration parameters simultaneously to avoid
	// configuration mismatches during the switchover process.
	PrimaryUpdateMethod *apiv1.PrimaryUpdateMethod `json:"primaryUpdateMethod,omitempty"`
	// The configuration to be used for backups
	Backup *BackupConfigurationApplyConfiguration `json:"backup,omitempty"`
	// Define a maintenance window for the Kubernetes nodes
	NodeMaintenanceWindow *NodeMaintenanceWindowApplyConfiguration `json:"nodeMaintenanceWindow,omitempty"`
	// The configuration of the monitoring infrastructure of this cluster
	Monitoring *MonitoringConfigurationApplyConfiguration `json:"monitoring,omitempty"`
	// The list of external clusters which are used in the configuration
	ExternalClusters []ExternalClusterApplyConfiguration `json:"externalClusters,omitempty"`
	// The instances' log level, one of the following values: error, warning, info (default), debug, trace
	LogLevel *string `json:"logLevel,omitempty"`
	// Template to be used to define projected volumes, projected volumes will be mounted
	// under `/projected` base folder
	ProjectedVolumeTemplate *corev1.ProjectedVolumeSource `json:"projectedVolumeTemplate,omitempty"`
	// Env follows the Env format to pass environment variables
	// to the pods created in the cluster
	Env []corev1.EnvVar `json:"env,omitempty"`
	// EnvFrom follows the EnvFrom format to pass environment variables
	// sources to the pods to be used by Env
	EnvFrom []corev1.EnvFromSource `json:"envFrom,omitempty"`
	// The configuration that is used by the portions of PostgreSQL that are managed by the instance manager
	Managed *ManagedConfigurationApplyConfiguration `json:"managed,omitempty"`
	// The SeccompProfile applied to every Pod and Container.
	// Defaults to: `RuntimeDefault`
	SeccompProfile *corev1.SeccompProfile `json:"seccompProfile,omitempty"`
	// Override the PodSecurityContext applied to every Pod of the cluster.
	// When set, this overrides the operator's default PodSecurityContext for the cluster.
	// If omitted, the operator defaults are used.
	// This field doesn't have any effect if SecurityContextConstraints are present.
	PodSecurityContext *corev1.PodSecurityContext `json:"podSecurityContext,omitempty"`
	// Override the SecurityContext applied to every Container in the Pod of the cluster.
	// When set, this overrides the operator's default Container SecurityContext.
	// If omitted, the operator defaults are used.
	SecurityContext *corev1.SecurityContext `json:"securityContext,omitempty"`
	// The tablespaces configuration
	Tablespaces []TablespaceConfigurationApplyConfiguration `json:"tablespaces,omitempty"`
	// Manage the `PodDisruptionBudget` resources within the cluster. When
	// configured as `true` (default setting), the pod disruption budgets
	// will safeguard the primary node from being terminated. Conversely,
	// setting it to `false` will result in the absence of any
	// `PodDisruptionBudget` resource, permitting the shutdown of all nodes
	// hosting the PostgreSQL cluster. This latter configuration is
	// advisable for any PostgreSQL cluster employed for
	// development/staging purposes.
	EnablePDB *bool `json:"enablePDB,omitempty"`
	// The plugins configuration, containing
	// any plugin to be loaded with the corresponding configuration
	Plugins []PluginConfigurationApplyConfiguration `json:"plugins,omitempty"`
	// The configuration of the probes to be injected
	// in the PostgreSQL Pods.
	Probes *ProbesConfigurationApplyConfiguration `json:"probes,omitempty"`
}

// ClusterSpecApplyConfiguration constructs a declarative configuration of the ClusterSpec type for use with
// apply.
func ClusterSpec() *ClusterSpecApplyConfiguration {
	return &ClusterSpecApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithDescription(value string) *ClusterSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithInheritedMetadata sets the InheritedMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InheritedMetadata field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithInheritedMetadata(value *EmbeddedObjectMetadataApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.InheritedMetadata = value
	return b
}

// WithImageName sets the ImageName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithImageName(value string) *ClusterSpecApplyConfiguration {
	b.ImageName = &value
	return b
}

// WithImageCatalogRef sets the ImageCatalogRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageCatalogRef field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithImageCatalogRef(value *ImageCatalogRefApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.ImageCatalogRef = value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithImagePullPolicy(value corev1.PullPolicy) *ClusterSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithSchedulerName sets the SchedulerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulerName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSchedulerName(value string) *ClusterSpecApplyConfiguration {
	b.SchedulerName = &value
	return b
}

// WithPostgresUID sets the PostgresUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostgresUID field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPostgresUID(value int64) *ClusterSpecApplyConfiguration {
	b.PostgresUID = &value
	return b
}

// WithPostgresGID sets the PostgresGID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostgresGID field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPostgresGID(value int64) *ClusterSpecApplyConfiguration {
	b.PostgresGID = &value
	return b
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithInstances(value int) *ClusterSpecApplyConfiguration {
	b.Instances = &value
	return b
}

// WithMinSyncReplicas sets the MinSyncReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSyncReplicas field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMinSyncReplicas(value int) *ClusterSpecApplyConfiguration {
	b.MinSyncReplicas = &value
	return b
}

// WithMaxSyncReplicas sets the MaxSyncReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSyncReplicas field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMaxSyncReplicas(value int) *ClusterSpecApplyConfiguration {
	b.MaxSyncReplicas = &value
	return b
}

// WithPostgresConfiguration sets the PostgresConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostgresConfiguration field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPostgresConfiguration(value *PostgresConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.PostgresConfiguration = value
	return b
}

// WithReplicationSlots sets the ReplicationSlots field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicationSlots field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithReplicationSlots(value *ReplicationSlotsConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.ReplicationSlots = value
	return b
}

// WithBootstrap sets the Bootstrap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bootstrap field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithBootstrap(value *BootstrapConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Bootstrap = value
	return b
}

// WithReplicaCluster sets the ReplicaCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicaCluster field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithReplicaCluster(value *ReplicaClusterConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.ReplicaCluster = value
	return b
}

// WithSuperuserSecret sets the SuperuserSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuperuserSecret field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSuperuserSecret(value *applyconfigurationscorev1.LocalObjectReferenceApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.SuperuserSecret = value
	return b
}

// WithEnableSuperuserAccess sets the EnableSuperuserAccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableSuperuserAccess field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithEnableSuperuserAccess(value bool) *ClusterSpecApplyConfiguration {
	b.EnableSuperuserAccess = &value
	return b
}

// WithCertificates sets the Certificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificates field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithCertificates(value *CertificatesConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Certificates = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *ClusterSpecApplyConfiguration) WithImagePullSecrets(values ...*applyconfigurationscorev1.LocalObjectReferenceApplyConfiguration) *ClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.ImagePullSecrets = append(b.ImagePullSecrets, *values[i])
	}
	return b
}

// WithStorageConfiguration sets the StorageConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageConfiguration field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithStorageConfiguration(value *StorageConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.StorageConfiguration = value
	return b
}

// WithServiceAccountTemplate sets the ServiceAccountTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountTemplate field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithServiceAccountTemplate(value *ServiceAccountTemplateApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.ServiceAccountTemplate = value
	return b
}

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithServiceAccountName(value string) *ClusterSpecApplyConfiguration {
	b.ServiceAccountName = &value
	return b
}

// WithWalStorage sets the WalStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WalStorage field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithWalStorage(value *StorageConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.WalStorage = value
	return b
}

// WithEphemeralVolumeSource sets the EphemeralVolumeSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralVolumeSource field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithEphemeralVolumeSource(value corev1.EphemeralVolumeSource) *ClusterSpecApplyConfiguration {
	b.EphemeralVolumeSource = &value
	return b
}

// WithMaxStartDelay sets the MaxStartDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStartDelay field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMaxStartDelay(value int32) *ClusterSpecApplyConfiguration {
	b.MaxStartDelay = &value
	return b
}

// WithMaxStopDelay sets the MaxStopDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStopDelay field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMaxStopDelay(value int32) *ClusterSpecApplyConfiguration {
	b.MaxStopDelay = &value
	return b
}

// WithSmartShutdownTimeout sets the SmartShutdownTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SmartShutdownTimeout field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSmartShutdownTimeout(value int32) *ClusterSpecApplyConfiguration {
	b.SmartShutdownTimeout = &value
	return b
}

// WithMaxSwitchoverDelay sets the MaxSwitchoverDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSwitchoverDelay field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMaxSwitchoverDelay(value int32) *ClusterSpecApplyConfiguration {
	b.MaxSwitchoverDelay = &value
	return b
}

// WithFailoverDelay sets the FailoverDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailoverDelay field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithFailoverDelay(value int32) *ClusterSpecApplyConfiguration {
	b.FailoverDelay = &value
	return b
}

// WithLivenessProbeTimeout sets the LivenessProbeTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LivenessProbeTimeout field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithLivenessProbeTimeout(value int32) *ClusterSpecApplyConfiguration {
	b.LivenessProbeTimeout = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithAffinity(value *AffinityConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Affinity = value
	return b
}

// WithTopologySpreadConstraints adds the given value to the TopologySpreadConstraints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopologySpreadConstraints field.
func (b *ClusterSpecApplyConfiguration) WithTopologySpreadConstraints(values ...corev1.TopologySpreadConstraint) *ClusterSpecApplyConfiguration {
	for i := range values {
		b.TopologySpreadConstraints = append(b.TopologySpreadConstraints, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithResources(value corev1.ResourceRequirements) *ClusterSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithEphemeralVolumesSizeLimit sets the EphemeralVolumesSizeLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralVolumesSizeLimit field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithEphemeralVolumesSizeLimit(value *EphemeralVolumesSizeLimitConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.EphemeralVolumesSizeLimit = value
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPriorityClassName(value string) *ClusterSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithPrimaryUpdateStrategy sets the PrimaryUpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryUpdateStrategy field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPrimaryUpdateStrategy(value apiv1.PrimaryUpdateStrategy) *ClusterSpecApplyConfiguration {
	b.PrimaryUpdateStrategy = &value
	return b
}

// WithPrimaryUpdateMethod sets the PrimaryUpdateMethod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryUpdateMethod field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPrimaryUpdateMethod(value apiv1.PrimaryUpdateMethod) *ClusterSpecApplyConfiguration {
	b.PrimaryUpdateMethod = &value
	return b
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithBackup(value *BackupConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Backup = value
	return b
}

// WithNodeMaintenanceWindow sets the NodeMaintenanceWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeMaintenanceWindow field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithNodeMaintenanceWindow(value *NodeMaintenanceWindowApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.NodeMaintenanceWindow = value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithMonitoring(value *MonitoringConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Monitoring = value
	return b
}

// WithExternalClusters adds the given value to the ExternalClusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalClusters field.
func (b *ClusterSpecApplyConfiguration) WithExternalClusters(values ...*ExternalClusterApplyConfiguration) *ClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalClusters")
		}
		b.ExternalClusters = append(b.ExternalClusters, *values[i])
	}
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithLogLevel(value string) *ClusterSpecApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithProjectedVolumeTemplate sets the ProjectedVolumeTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectedVolumeTemplate field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithProjectedVolumeTemplate(value corev1.ProjectedVolumeSource) *ClusterSpecApplyConfiguration {
	b.ProjectedVolumeTemplate = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *ClusterSpecApplyConfiguration) WithEnv(values ...corev1.EnvVar) *ClusterSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithEnvFrom adds the given value to the EnvFrom field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EnvFrom field.
func (b *ClusterSpecApplyConfiguration) WithEnvFrom(values ...corev1.EnvFromSource) *ClusterSpecApplyConfiguration {
	for i := range values {
		b.EnvFrom = append(b.EnvFrom, values[i])
	}
	return b
}

// WithManaged sets the Managed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Managed field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithManaged(value *ManagedConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Managed = value
	return b
}

// WithSeccompProfile sets the SeccompProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeccompProfile field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSeccompProfile(value corev1.SeccompProfile) *ClusterSpecApplyConfiguration {
	b.SeccompProfile = &value
	return b
}

// WithPodSecurityContext sets the PodSecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSecurityContext field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithPodSecurityContext(value corev1.PodSecurityContext) *ClusterSpecApplyConfiguration {
	b.PodSecurityContext = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithSecurityContext(value corev1.SecurityContext) *ClusterSpecApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithTablespaces adds the given value to the Tablespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tablespaces field.
func (b *ClusterSpecApplyConfiguration) WithTablespaces(values ...*TablespaceConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTablespaces")
		}
		b.Tablespaces = append(b.Tablespaces, *values[i])
	}
	return b
}

// WithEnablePDB sets the EnablePDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnablePDB field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithEnablePDB(value bool) *ClusterSpecApplyConfiguration {
	b.EnablePDB = &value
	return b
}

// WithPlugins adds the given value to the Plugins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Plugins field.
func (b *ClusterSpecApplyConfiguration) WithPlugins(values ...*PluginConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPlugins")
		}
		b.Plugins = append(b.Plugins, *values[i])
	}
	return b
}

// WithProbes sets the Probes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Probes field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithProbes(value *ProbesConfigurationApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.Probes = value
	return b
}
