// Code generated by controller-gen. DO NOT EDIT.

package v1

// ConfigMapResourceVersionApplyConfiguration represents a declarative configuration of the ConfigMapResourceVersion type for use
// with apply.
//
// ConfigMapResourceVersion is the resource versions of the secrets
// managed by the operator
type ConfigMapResourceVersionApplyConfiguration struct {
	// A map with the versions of all the config maps used to pass metrics.
	// Map keys are the config map names, map values are the versions
	Metrics map[string]string `json:"metrics,omitempty"`
}

// ConfigMapResourceVersionApplyConfiguration constructs a declarative configuration of the ConfigMapResourceVersion type for use with
// apply.
func ConfigMapResourceVersion() *ConfigMapResourceVersionApplyConfiguration {
	return &ConfigMapResourceVersionApplyConfiguration{}
}

// WithMetrics puts the entries into the Metrics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Metrics field,
// overwriting an existing map entries in Metrics field with the same key.
func (b *ConfigMapResourceVersionApplyConfiguration) WithMetrics(entries map[string]string) *ConfigMapResourceVersionApplyConfiguration {
	if b.Metrics == nil && len(entries) > 0 {
		b.Metrics = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Metrics[k] = v
	}
	return b
}
