// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// DataSourceApplyConfiguration represents a declarative configuration of the DataSource type for use
// with apply.
//
// DataSource contains the configuration required to bootstrap a
// PostgreSQL cluster from an existing storage
type DataSourceApplyConfiguration struct {
	// Configuration of the storage of the instances
	Storage *corev1.TypedLocalObjectReferenceApplyConfiguration `json:"storage,omitempty"`
	// Configuration of the storage for PostgreSQL WAL (Write-Ahead Log)
	WalStorage *corev1.TypedLocalObjectReferenceApplyConfiguration `json:"walStorage,omitempty"`
	// Configuration of the storage for PostgreSQL tablespaces
	TablespaceStorage map[string]corev1.TypedLocalObjectReferenceApplyConfiguration `json:"tablespaceStorage,omitempty"`
}

// DataSourceApplyConfiguration constructs a declarative configuration of the DataSource type for use with
// apply.
func DataSource() *DataSourceApplyConfiguration {
	return &DataSourceApplyConfiguration{}
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *DataSourceApplyConfiguration) WithStorage(value *corev1.TypedLocalObjectReferenceApplyConfiguration) *DataSourceApplyConfiguration {
	b.Storage = value
	return b
}

// WithWalStorage sets the WalStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WalStorage field is set to the value of the last call.
func (b *DataSourceApplyConfiguration) WithWalStorage(value *corev1.TypedLocalObjectReferenceApplyConfiguration) *DataSourceApplyConfiguration {
	b.WalStorage = value
	return b
}

// WithTablespaceStorage puts the entries into the TablespaceStorage field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the TablespaceStorage field,
// overwriting an existing map entries in TablespaceStorage field with the same key.
func (b *DataSourceApplyConfiguration) WithTablespaceStorage(entries map[string]corev1.TypedLocalObjectReferenceApplyConfiguration) *DataSourceApplyConfiguration {
	if b.TablespaceStorage == nil && len(entries) > 0 {
		b.TablespaceStorage = make(map[string]corev1.TypedLocalObjectReferenceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.TablespaceStorage[k] = v
	}
	return b
}
