// Code generated by controller-gen. DO NOT EDIT.

package v1

// DatabaseRoleRefApplyConfiguration represents a declarative configuration of the DatabaseRoleRef type for use
// with apply.
//
// DatabaseRoleRef is a reference an a role available inside PostgreSQL
type DatabaseRoleRefApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// DatabaseRoleRefApplyConfiguration constructs a declarative configuration of the DatabaseRoleRef type for use with
// apply.
func DatabaseRoleRef() *DatabaseRoleRefApplyConfiguration {
	return &DatabaseRoleRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabaseRoleRefApplyConfiguration) WithName(value string) *DatabaseRoleRefApplyConfiguration {
	b.Name = &value
	return b
}
