// Code generated by controller-gen. DO NOT EDIT.

package v1

// DatabaseStatusApplyConfiguration represents a declarative configuration of the DatabaseStatus type for use
// with apply.
//
// DatabaseStatus defines the observed state of Database
type DatabaseStatusApplyConfiguration struct {
	// A sequence number representing the latest
	// desired state that was synchronized
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Applied is true if the database was reconciled correctly
	Applied *bool `json:"applied,omitempty"`
	// Message is the reconciliation output message
	Message *string `json:"message,omitempty"`
	// Schemas is the status of the managed schemas
	Schemas []DatabaseObjectStatusApplyConfiguration `json:"schemas,omitempty"`
	// Extensions is the status of the managed extensions
	Extensions []DatabaseObjectStatusApplyConfiguration `json:"extensions,omitempty"`
	// FDWs is the status of the managed FDWs
	FDWs []DatabaseObjectStatusApplyConfiguration `json:"fdws,omitempty"`
	// Servers is the status of the managed servers
	Servers []DatabaseObjectStatusApplyConfiguration `json:"servers,omitempty"`
}

// DatabaseStatusApplyConfiguration constructs a declarative configuration of the DatabaseStatus type for use with
// apply.
func DatabaseStatus() *DatabaseStatusApplyConfiguration {
	return &DatabaseStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DatabaseStatusApplyConfiguration) WithObservedGeneration(value int64) *DatabaseStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithApplied sets the Applied field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Applied field is set to the value of the last call.
func (b *DatabaseStatusApplyConfiguration) WithApplied(value bool) *DatabaseStatusApplyConfiguration {
	b.Applied = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DatabaseStatusApplyConfiguration) WithMessage(value string) *DatabaseStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithSchemas adds the given value to the Schemas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Schemas field.
func (b *DatabaseStatusApplyConfiguration) WithSchemas(values ...*DatabaseObjectStatusApplyConfiguration) *DatabaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSchemas")
		}
		b.Schemas = append(b.Schemas, *values[i])
	}
	return b
}

// WithExtensions adds the given value to the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Extensions field.
func (b *DatabaseStatusApplyConfiguration) WithExtensions(values ...*DatabaseObjectStatusApplyConfiguration) *DatabaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExtensions")
		}
		b.Extensions = append(b.Extensions, *values[i])
	}
	return b
}

// WithFDWs adds the given value to the FDWs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FDWs field.
func (b *DatabaseStatusApplyConfiguration) WithFDWs(values ...*DatabaseObjectStatusApplyConfiguration) *DatabaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFDWs")
		}
		b.FDWs = append(b.FDWs, *values[i])
	}
	return b
}

// WithServers adds the given value to the Servers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Servers field.
func (b *DatabaseStatusApplyConfiguration) WithServers(values ...*DatabaseObjectStatusApplyConfiguration) *DatabaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServers")
		}
		b.Servers = append(b.Servers, *values[i])
	}
	return b
}
