// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/api/core/v1"
)

// DatabaseSpecApplyConfiguration represents a declarative configuration of the DatabaseSpec type for use
// with apply.
//
// DatabaseSpec is the specification of a Postgresql Database, built around the
// `CREATE DATABASE`, `ALTER DATABASE`, and `DROP DATABASE` SQL commands of
// PostgreSQL.
type DatabaseSpecApplyConfiguration struct {
	// The name of the PostgreSQL cluster hosting the database.
	ClusterRef *corev1.LocalObjectReference `json:"cluster,omitempty"`
	// Ensure the PostgreSQL database is `present` or `absent` - defaults to "present".
	Ensure *apiv1.EnsureOption `json:"ensure,omitempty"`
	// The name of the database to create inside PostgreSQL. This setting cannot be changed.
	Name *string `json:"name,omitempty"`
	// Maps to the `OWNER` parameter of `CREATE DATABASE`.
	// Maps to the `OWNER TO` command of `ALTER DATABASE`.
	// The role name of the user who owns the database inside PostgreSQL.
	Owner *string `json:"owner,omitempty"`
	// Maps to the `TEMPLATE` parameter of `CREATE DATABASE`. This setting
	// cannot be changed. The name of the template from which to create
	// this database.
	Template *string `json:"template,omitempty"`
	// Maps to the `ENCODING` parameter of `CREATE DATABASE`. This setting
	// cannot be changed. Character set encoding to use in the database.
	Encoding *string `json:"encoding,omitempty"`
	// Maps to the `LOCALE` parameter of `CREATE DATABASE`. This setting
	// cannot be changed. Sets the default collation order and character
	// classification in the new database.
	Locale *string `json:"locale,omitempty"`
	// Maps to the `LOCALE_PROVIDER` parameter of `CREATE DATABASE`. This
	// setting cannot be changed. This option sets the locale provider for
	// databases created in the new cluster. Available from PostgreSQL 16.
	LocaleProvider *string `json:"localeProvider,omitempty"`
	// Maps to the `LC_COLLATE` parameter of `CREATE DATABASE`. This
	// setting cannot be changed.
	LcCollate *string `json:"localeCollate,omitempty"`
	// Maps to the `LC_CTYPE` parameter of `CREATE DATABASE`. This setting
	// cannot be changed.
	LcCtype *string `json:"localeCType,omitempty"`
	// Maps to the `ICU_LOCALE` parameter of `CREATE DATABASE`. This
	// setting cannot be changed. Specifies the ICU locale when the ICU
	// provider is used. This option requires `localeProvider` to be set to
	// `icu`. Available from PostgreSQL 15.
	IcuLocale *string `json:"icuLocale,omitempty"`
	// Maps to the `ICU_RULES` parameter of `CREATE DATABASE`. This setting
	// cannot be changed. Specifies additional collation rules to customize
	// the behavior of the default collation. This option requires
	// `localeProvider` to be set to `icu`. Available from PostgreSQL 16.
	IcuRules *string `json:"icuRules,omitempty"`
	// Maps to the `BUILTIN_LOCALE` parameter of `CREATE DATABASE`. This
	// setting cannot be changed. Specifies the locale name when the
	// builtin provider is used. This option requires `localeProvider` to
	// be set to `builtin`. Available from PostgreSQL 17.
	BuiltinLocale *string `json:"builtinLocale,omitempty"`
	// Maps to the `COLLATION_VERSION` parameter of `CREATE DATABASE`. This
	// setting cannot be changed.
	CollationVersion *string `json:"collationVersion,omitempty"`
	// Maps to the `IS_TEMPLATE` parameter of `CREATE DATABASE` and `ALTER
	// DATABASE`. If true, this database is considered a template and can
	// be cloned by any user with `CREATEDB` privileges.
	IsTemplate *bool `json:"isTemplate,omitempty"`
	// Maps to the `ALLOW_CONNECTIONS` parameter of `CREATE DATABASE` and
	// `ALTER DATABASE`. If false then no one can connect to this database.
	AllowConnections *bool `json:"allowConnections,omitempty"`
	// Maps to the `CONNECTION LIMIT` clause of `CREATE DATABASE` and
	// `ALTER DATABASE`. How many concurrent connections can be made to
	// this database. -1 (the default) means no limit.
	ConnectionLimit *int `json:"connectionLimit,omitempty"`
	// Maps to the `TABLESPACE` parameter of `CREATE DATABASE`.
	// Maps to the `SET TABLESPACE` command of `ALTER DATABASE`.
	// The name of the tablespace (in PostgreSQL) that will be associated
	// with the new database. This tablespace will be the default
	// tablespace used for objects created in this database.
	Tablespace *string `json:"tablespace,omitempty"`
	// The policy for end-of-life maintenance of this database.
	ReclaimPolicy *apiv1.DatabaseReclaimPolicy `json:"databaseReclaimPolicy,omitempty"`
	// The list of schemas to be managed in the database
	Schemas []SchemaSpecApplyConfiguration `json:"schemas,omitempty"`
	// The list of extensions to be managed in the database
	Extensions []ExtensionSpecApplyConfiguration `json:"extensions,omitempty"`
	// The list of foreign data wrappers to be managed in the database
	FDWs []FDWSpecApplyConfiguration `json:"fdws,omitempty"`
	// The list of foreign servers to be managed in the database
	Servers []ServerSpecApplyConfiguration `json:"servers,omitempty"`
}

// DatabaseSpecApplyConfiguration constructs a declarative configuration of the DatabaseSpec type for use with
// apply.
func DatabaseSpec() *DatabaseSpecApplyConfiguration {
	return &DatabaseSpecApplyConfiguration{}
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithClusterRef(value corev1.LocalObjectReference) *DatabaseSpecApplyConfiguration {
	b.ClusterRef = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *DatabaseSpecApplyConfiguration {
	b.Ensure = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithName(value string) *DatabaseSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithOwner(value string) *DatabaseSpecApplyConfiguration {
	b.Owner = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithTemplate(value string) *DatabaseSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithEncoding sets the Encoding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encoding field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithEncoding(value string) *DatabaseSpecApplyConfiguration {
	b.Encoding = &value
	return b
}

// WithLocale sets the Locale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Locale field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithLocale(value string) *DatabaseSpecApplyConfiguration {
	b.Locale = &value
	return b
}

// WithLocaleProvider sets the LocaleProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocaleProvider field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithLocaleProvider(value string) *DatabaseSpecApplyConfiguration {
	b.LocaleProvider = &value
	return b
}

// WithLcCollate sets the LcCollate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LcCollate field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithLcCollate(value string) *DatabaseSpecApplyConfiguration {
	b.LcCollate = &value
	return b
}

// WithLcCtype sets the LcCtype field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LcCtype field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithLcCtype(value string) *DatabaseSpecApplyConfiguration {
	b.LcCtype = &value
	return b
}

// WithIcuLocale sets the IcuLocale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcuLocale field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithIcuLocale(value string) *DatabaseSpecApplyConfiguration {
	b.IcuLocale = &value
	return b
}

// WithIcuRules sets the IcuRules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IcuRules field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithIcuRules(value string) *DatabaseSpecApplyConfiguration {
	b.IcuRules = &value
	return b
}

// WithBuiltinLocale sets the BuiltinLocale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BuiltinLocale field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithBuiltinLocale(value string) *DatabaseSpecApplyConfiguration {
	b.BuiltinLocale = &value
	return b
}

// WithCollationVersion sets the CollationVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollationVersion field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithCollationVersion(value string) *DatabaseSpecApplyConfiguration {
	b.CollationVersion = &value
	return b
}

// WithIsTemplate sets the IsTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsTemplate field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithIsTemplate(value bool) *DatabaseSpecApplyConfiguration {
	b.IsTemplate = &value
	return b
}

// WithAllowConnections sets the AllowConnections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowConnections field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithAllowConnections(value bool) *DatabaseSpecApplyConfiguration {
	b.AllowConnections = &value
	return b
}

// WithConnectionLimit sets the ConnectionLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionLimit field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithConnectionLimit(value int) *DatabaseSpecApplyConfiguration {
	b.ConnectionLimit = &value
	return b
}

// WithTablespace sets the Tablespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tablespace field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithTablespace(value string) *DatabaseSpecApplyConfiguration {
	b.Tablespace = &value
	return b
}

// WithReclaimPolicy sets the ReclaimPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReclaimPolicy field is set to the value of the last call.
func (b *DatabaseSpecApplyConfiguration) WithReclaimPolicy(value apiv1.DatabaseReclaimPolicy) *DatabaseSpecApplyConfiguration {
	b.ReclaimPolicy = &value
	return b
}

// WithSchemas adds the given value to the Schemas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Schemas field.
func (b *DatabaseSpecApplyConfiguration) WithSchemas(values ...*SchemaSpecApplyConfiguration) *DatabaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSchemas")
		}
		b.Schemas = append(b.Schemas, *values[i])
	}
	return b
}

// WithExtensions adds the given value to the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Extensions field.
func (b *DatabaseSpecApplyConfiguration) WithExtensions(values ...*ExtensionSpecApplyConfiguration) *DatabaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExtensions")
		}
		b.Extensions = append(b.Extensions, *values[i])
	}
	return b
}

// WithFDWs adds the given value to the FDWs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FDWs field.
func (b *DatabaseSpecApplyConfiguration) WithFDWs(values ...*FDWSpecApplyConfiguration) *DatabaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFDWs")
		}
		b.FDWs = append(b.FDWs, *values[i])
	}
	return b
}

// WithServers adds the given value to the Servers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Servers field.
func (b *DatabaseSpecApplyConfiguration) WithServers(values ...*ServerSpecApplyConfiguration) *DatabaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServers")
		}
		b.Servers = append(b.Servers, *values[i])
	}
	return b
}
