// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// DatabaseObjectSpecApplyConfiguration represents a declarative configuration of the DatabaseObjectSpec type for use
// with apply.
//
// DatabaseObjectSpec contains the fields which are common to every
// database object
type DatabaseObjectSpecApplyConfiguration struct {
	// Name of the object (extension, schema, FDW, server)
	Name *string `json:"name,omitempty"`
	// Specifies whether an object (e.g schema) should be present or absent
	// in the database. If set to `present`, the object will be created if
	// it does not exist. If set to `absent`, the extension/schema will be
	// removed if it exists.
	Ensure *apiv1.EnsureOption `json:"ensure,omitempty"`
}

// DatabaseObjectSpecApplyConfiguration constructs a declarative configuration of the DatabaseObjectSpec type for use with
// apply.
func DatabaseObjectSpec() *DatabaseObjectSpecApplyConfiguration {
	return &DatabaseObjectSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabaseObjectSpecApplyConfiguration) WithName(value string) *DatabaseObjectSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *DatabaseObjectSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *DatabaseObjectSpecApplyConfiguration {
	b.Ensure = &value
	return b
}
