// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// EphemeralVolumesSizeLimitConfigurationApplyConfiguration represents a declarative configuration of the EphemeralVolumesSizeLimitConfiguration type for use
// with apply.
//
// EphemeralVolumesSizeLimitConfiguration contains the configuration of the ephemeral
// storage
type EphemeralVolumesSizeLimitConfigurationApplyConfiguration struct {
	// Shm is the size limit of the shared memory volume
	Shm *resource.Quantity `json:"shm,omitempty"`
	// TemporaryData is the size limit of the temporary data volume
	TemporaryData *resource.Quantity `json:"temporaryData,omitempty"`
}

// EphemeralVolumesSizeLimitConfigurationApplyConfiguration constructs a declarative configuration of the EphemeralVolumesSizeLimitConfiguration type for use with
// apply.
func EphemeralVolumesSizeLimitConfiguration() *EphemeralVolumesSizeLimitConfigurationApplyConfiguration {
	return &EphemeralVolumesSizeLimitConfigurationApplyConfiguration{}
}

// WithShm sets the Shm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shm field is set to the value of the last call.
func (b *EphemeralVolumesSizeLimitConfigurationApplyConfiguration) WithShm(value resource.Quantity) *EphemeralVolumesSizeLimitConfigurationApplyConfiguration {
	b.Shm = &value
	return b
}

// WithTemporaryData sets the TemporaryData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemporaryData field is set to the value of the last call.
func (b *EphemeralVolumesSizeLimitConfigurationApplyConfiguration) WithTemporaryData(value resource.Quantity) *EphemeralVolumesSizeLimitConfigurationApplyConfiguration {
	b.TemporaryData = &value
	return b
}
