// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// ExtensionConfigurationApplyConfiguration represents a declarative configuration of the ExtensionConfiguration type for use
// with apply.
//
// ExtensionConfiguration is the configuration used to add
// PostgreSQL extensions to the Cluster.
type ExtensionConfigurationApplyConfiguration struct {
	// The name of the extension, required
	Name *string `json:"name,omitempty"`
	// The image containing the extension, required
	ImageVolumeSource *corev1.ImageVolumeSource `json:"image,omitempty"`
	// The list of directories inside the image which should be added to extension_control_path.
	// If not defined, defaults to "/share".
	ExtensionControlPath []string `json:"extension_control_path,omitempty"`
	// The list of directories inside the image which should be added to dynamic_library_path.
	// If not defined, defaults to "/lib".
	DynamicLibraryPath []string `json:"dynamic_library_path,omitempty"`
	// The list of directories inside the image which should be added to ld_library_path.
	LdLibraryPath []string `json:"ld_library_path,omitempty"`
}

// ExtensionConfigurationApplyConfiguration constructs a declarative configuration of the ExtensionConfiguration type for use with
// apply.
func ExtensionConfiguration() *ExtensionConfigurationApplyConfiguration {
	return &ExtensionConfigurationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ExtensionConfigurationApplyConfiguration) WithName(value string) *ExtensionConfigurationApplyConfiguration {
	b.Name = &value
	return b
}

// WithImageVolumeSource sets the ImageVolumeSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageVolumeSource field is set to the value of the last call.
func (b *ExtensionConfigurationApplyConfiguration) WithImageVolumeSource(value corev1.ImageVolumeSource) *ExtensionConfigurationApplyConfiguration {
	b.ImageVolumeSource = &value
	return b
}

// WithExtensionControlPath adds the given value to the ExtensionControlPath field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtensionControlPath field.
func (b *ExtensionConfigurationApplyConfiguration) WithExtensionControlPath(values ...string) *ExtensionConfigurationApplyConfiguration {
	for i := range values {
		b.ExtensionControlPath = append(b.ExtensionControlPath, values[i])
	}
	return b
}

// WithDynamicLibraryPath adds the given value to the DynamicLibraryPath field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DynamicLibraryPath field.
func (b *ExtensionConfigurationApplyConfiguration) WithDynamicLibraryPath(values ...string) *ExtensionConfigurationApplyConfiguration {
	for i := range values {
		b.DynamicLibraryPath = append(b.DynamicLibraryPath, values[i])
	}
	return b
}

// WithLdLibraryPath adds the given value to the LdLibraryPath field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LdLibraryPath field.
func (b *ExtensionConfigurationApplyConfiguration) WithLdLibraryPath(values ...string) *ExtensionConfigurationApplyConfiguration {
	for i := range values {
		b.LdLibraryPath = append(b.LdLibraryPath, values[i])
	}
	return b
}
