// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/barman-cloud/pkg/api"
	corev1 "k8s.io/api/core/v1"
)

// ExternalClusterApplyConfiguration represents a declarative configuration of the ExternalCluster type for use
// with apply.
//
// ExternalCluster represents the connection parameters to an
// external cluster which is used in the other sections of the configuration
type ExternalClusterApplyConfiguration struct {
	// The server name, required
	Name *string `json:"name,omitempty"`
	// The list of connection parameters, such as dbname, host, username, etc
	ConnectionParameters map[string]string `json:"connectionParameters,omitempty"`
	// The reference to an SSL certificate to be used to connect to this
	// instance
	SSLCert *corev1.SecretKeySelector `json:"sslCert,omitempty"`
	// The reference to an SSL private key to be used to connect to this
	// instance
	SSLKey *corev1.SecretKeySelector `json:"sslKey,omitempty"`
	// The reference to an SSL CA public key to be used to connect to this
	// instance
	SSLRootCert *corev1.SecretKeySelector `json:"sslRootCert,omitempty"`
	// The reference to the password to be used to connect to the server.
	// If a password is provided, CloudNativePG creates a PostgreSQL
	// passfile at `/controller/external/NAME/pass` (where "NAME" is the
	// cluster's name). This passfile is automatically referenced in the
	// connection string when establishing a connection to the remote
	// PostgreSQL server from the current PostgreSQL `Cluster`. This ensures
	// secure and efficient password management for external clusters.
	Password *corev1.SecretKeySelector `json:"password,omitempty"`
	// The configuration for the barman-cloud tool suite
	BarmanObjectStore *api.BarmanObjectStoreConfiguration `json:"barmanObjectStore,omitempty"`
	// The configuration of the plugin that is taking care
	// of WAL archiving and backups for this external cluster
	PluginConfiguration *PluginConfigurationApplyConfiguration `json:"plugin,omitempty"`
}

// ExternalClusterApplyConfiguration constructs a declarative configuration of the ExternalCluster type for use with
// apply.
func ExternalCluster() *ExternalClusterApplyConfiguration {
	return &ExternalClusterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithName(value string) *ExternalClusterApplyConfiguration {
	b.Name = &value
	return b
}

// WithConnectionParameters puts the entries into the ConnectionParameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ConnectionParameters field,
// overwriting an existing map entries in ConnectionParameters field with the same key.
func (b *ExternalClusterApplyConfiguration) WithConnectionParameters(entries map[string]string) *ExternalClusterApplyConfiguration {
	if b.ConnectionParameters == nil && len(entries) > 0 {
		b.ConnectionParameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ConnectionParameters[k] = v
	}
	return b
}

// WithSSLCert sets the SSLCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLCert field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithSSLCert(value corev1.SecretKeySelector) *ExternalClusterApplyConfiguration {
	b.SSLCert = &value
	return b
}

// WithSSLKey sets the SSLKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLKey field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithSSLKey(value corev1.SecretKeySelector) *ExternalClusterApplyConfiguration {
	b.SSLKey = &value
	return b
}

// WithSSLRootCert sets the SSLRootCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLRootCert field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithSSLRootCert(value corev1.SecretKeySelector) *ExternalClusterApplyConfiguration {
	b.SSLRootCert = &value
	return b
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithPassword(value corev1.SecretKeySelector) *ExternalClusterApplyConfiguration {
	b.Password = &value
	return b
}

// WithBarmanObjectStore sets the BarmanObjectStore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BarmanObjectStore field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithBarmanObjectStore(value api.BarmanObjectStoreConfiguration) *ExternalClusterApplyConfiguration {
	b.BarmanObjectStore = &value
	return b
}

// WithPluginConfiguration sets the PluginConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PluginConfiguration field is set to the value of the last call.
func (b *ExternalClusterApplyConfiguration) WithPluginConfiguration(value *PluginConfigurationApplyConfiguration) *ExternalClusterApplyConfiguration {
	b.PluginConfiguration = value
	return b
}
