// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ExtensionSpecApplyConfiguration represents a declarative configuration of the ExtensionSpec type for use
// with apply.
//
// ExtensionSpec configures an extension in a database
type ExtensionSpecApplyConfiguration struct {
	// Common fields
	DatabaseObjectSpecApplyConfiguration `json:",inline"`
	// The version of the extension to install. If empty, the operator will
	// install the default version (whatever is specified in the
	// extension's control file)
	Version *string `json:"version,omitempty"`
	// The name of the schema in which to install the extension's objects,
	// in case the extension allows its contents to be relocated. If not
	// specified (default), and the extension's control file does not
	// specify a schema either, the current default object creation schema
	// is used.
	Schema *string `json:"schema,omitempty"`
}

// ExtensionSpecApplyConfiguration constructs a declarative configuration of the ExtensionSpec type for use with
// apply.
func ExtensionSpec() *ExtensionSpecApplyConfiguration {
	return &ExtensionSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ExtensionSpecApplyConfiguration) WithName(value string) *ExtensionSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Name = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *ExtensionSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *ExtensionSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Ensure = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ExtensionSpecApplyConfiguration) WithVersion(value string) *ExtensionSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *ExtensionSpecApplyConfiguration) WithSchema(value string) *ExtensionSpecApplyConfiguration {
	b.Schema = &value
	return b
}
