// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ImageCatalogRefApplyConfiguration represents a declarative configuration of the ImageCatalogRef type for use
// with apply.
//
// ImageCatalogRef defines the reference to a major version in an ImageCatalog
type ImageCatalogRefApplyConfiguration struct {
	corev1.TypedLocalObjectReferenceApplyConfiguration `json:",inline"`
	// The major version of PostgreSQL we want to use from the ImageCatalog
	Major *int `json:"major,omitempty"`
}

// ImageCatalogRefApplyConfiguration constructs a declarative configuration of the ImageCatalogRef type for use with
// apply.
func ImageCatalogRef() *ImageCatalogRefApplyConfiguration {
	return &ImageCatalogRefApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *ImageCatalogRefApplyConfiguration) WithAPIGroup(value string) *ImageCatalogRefApplyConfiguration {
	b.TypedLocalObjectReferenceApplyConfiguration.APIGroup = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ImageCatalogRefApplyConfiguration) WithKind(value string) *ImageCatalogRefApplyConfiguration {
	b.TypedLocalObjectReferenceApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImageCatalogRefApplyConfiguration) WithName(value string) *ImageCatalogRefApplyConfiguration {
	b.TypedLocalObjectReferenceApplyConfiguration.Name = &value
	return b
}

// WithMajor sets the Major field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Major field is set to the value of the last call.
func (b *ImageCatalogRefApplyConfiguration) WithMajor(value int) *ImageCatalogRefApplyConfiguration {
	b.Major = &value
	return b
}
