// Code generated by controller-gen. DO NOT EDIT.

package v1

// ImageInfoApplyConfiguration represents a declarative configuration of the ImageInfo type for use
// with apply.
//
// ImageInfo contains the information about a PostgreSQL image
type ImageInfoApplyConfiguration struct {
	// Image is the image name
	Image *string `json:"image,omitempty"`
	// MajorVersion is the major version of the image
	MajorVersion *int `json:"majorVersion,omitempty"`
}

// ImageInfoApplyConfiguration constructs a declarative configuration of the ImageInfo type for use with
// apply.
func ImageInfo() *ImageInfoApplyConfiguration {
	return &ImageInfoApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ImageInfoApplyConfiguration) WithImage(value string) *ImageInfoApplyConfiguration {
	b.Image = &value
	return b
}

// WithMajorVersion sets the MajorVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MajorVersion field is set to the value of the last call.
func (b *ImageInfoApplyConfiguration) WithMajorVersion(value int) *ImageInfoApplyConfiguration {
	b.MajorVersion = &value
	return b
}
