// Code generated by controller-gen. DO NOT EDIT.

package v1

// ImageCatalogSpecApplyConfiguration represents a declarative configuration of the ImageCatalogSpec type for use
// with apply.
//
// ImageCatalogSpec defines the desired ImageCatalog
type ImageCatalogSpecApplyConfiguration struct {
	// List of CatalogImages available in the catalog
	Images []CatalogImageApplyConfiguration `json:"images,omitempty"`
}

// ImageCatalogSpecApplyConfiguration constructs a declarative configuration of the ImageCatalogSpec type for use with
// apply.
func ImageCatalogSpec() *ImageCatalogSpecApplyConfiguration {
	return &ImageCatalogSpecApplyConfiguration{}
}

// WithImages adds the given value to the Images field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Images field.
func (b *ImageCatalogSpecApplyConfiguration) WithImages(values ...*CatalogImageApplyConfiguration) *ImageCatalogSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImages")
		}
		b.Images = append(b.Images, *values[i])
	}
	return b
}
