// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ImportApplyConfiguration represents a declarative configuration of the Import type for use
// with apply.
//
// Import contains the configuration to init a database from a logic snapshot of an externalCluster
type ImportApplyConfiguration struct {
	// The source of the import
	Source *ImportSourceApplyConfiguration `json:"source,omitempty"`
	// The import type. Can be `microservice` or `monolith`.
	Type *apiv1.SnapshotType `json:"type,omitempty"`
	// The databases to import
	Databases []string `json:"databases,omitempty"`
	// The roles to import
	Roles []string `json:"roles,omitempty"`
	// List of SQL queries to be executed as a superuser in the application
	// database right after is imported - to be used with extreme care
	// (by default empty). Only available in microservice type.
	PostImportApplicationSQL []string `json:"postImportApplicationSQL,omitempty"`
	// When set to true, only the `pre-data` and `post-data` sections of
	// `pg_restore` are invoked, avoiding data import. Default: `false`.
	SchemaOnly *bool `json:"schemaOnly,omitempty"`
	// List of custom options to pass to the `pg_dump` command.
	//
	// IMPORTANT: Use with caution. The operator does not validate these options,
	// and certain flags may interfere with its intended functionality or design.
	// You are responsible for ensuring that the provided options are compatible
	// with your environment and desired behavior.
	PgDumpExtraOptions []string `json:"pgDumpExtraOptions,omitempty"`
	// List of custom options to pass to the `pg_restore` command.
	//
	// IMPORTANT: Use with caution. The operator does not validate these options,
	// and certain flags may interfere with its intended functionality or design.
	// You are responsible for ensuring that the provided options are compatible
	// with your environment and desired behavior.
	PgRestoreExtraOptions []string `json:"pgRestoreExtraOptions,omitempty"`
	// Custom options to pass to the `pg_restore` command during the `pre-data`
	// section. This setting overrides the generic `pgRestoreExtraOptions` value.
	//
	// IMPORTANT: Use with caution. The operator does not validate these options,
	// and certain flags may interfere with its intended functionality or design.
	// You are responsible for ensuring that the provided options are compatible
	// with your environment and desired behavior.
	PgRestorePredataOptions []string `json:"pgRestorePredataOptions,omitempty"`
	// Custom options to pass to the `pg_restore` command during the `data`
	// section. This setting overrides the generic `pgRestoreExtraOptions` value.
	//
	// IMPORTANT: Use with caution. The operator does not validate these options,
	// and certain flags may interfere with its intended functionality or design.
	// You are responsible for ensuring that the provided options are compatible
	// with your environment and desired behavior.
	PgRestoreDataOptions []string `json:"pgRestoreDataOptions,omitempty"`
	// Custom options to pass to the `pg_restore` command during the `post-data`
	// section. This setting overrides the generic `pgRestoreExtraOptions` value.
	//
	// IMPORTANT: Use with caution. The operator does not validate these options,
	// and certain flags may interfere with its intended functionality or design.
	// You are responsible for ensuring that the provided options are compatible
	// with your environment and desired behavior.
	PgRestorePostdataOptions []string `json:"pgRestorePostdataOptions,omitempty"`
}

// ImportApplyConfiguration constructs a declarative configuration of the Import type for use with
// apply.
func Import() *ImportApplyConfiguration {
	return &ImportApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ImportApplyConfiguration) WithSource(value *ImportSourceApplyConfiguration) *ImportApplyConfiguration {
	b.Source = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ImportApplyConfiguration) WithType(value apiv1.SnapshotType) *ImportApplyConfiguration {
	b.Type = &value
	return b
}

// WithDatabases adds the given value to the Databases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Databases field.
func (b *ImportApplyConfiguration) WithDatabases(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.Databases = append(b.Databases, values[i])
	}
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *ImportApplyConfiguration) WithRoles(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.Roles = append(b.Roles, values[i])
	}
	return b
}

// WithPostImportApplicationSQL adds the given value to the PostImportApplicationSQL field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PostImportApplicationSQL field.
func (b *ImportApplyConfiguration) WithPostImportApplicationSQL(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PostImportApplicationSQL = append(b.PostImportApplicationSQL, values[i])
	}
	return b
}

// WithSchemaOnly sets the SchemaOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchemaOnly field is set to the value of the last call.
func (b *ImportApplyConfiguration) WithSchemaOnly(value bool) *ImportApplyConfiguration {
	b.SchemaOnly = &value
	return b
}

// WithPgDumpExtraOptions adds the given value to the PgDumpExtraOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgDumpExtraOptions field.
func (b *ImportApplyConfiguration) WithPgDumpExtraOptions(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PgDumpExtraOptions = append(b.PgDumpExtraOptions, values[i])
	}
	return b
}

// WithPgRestoreExtraOptions adds the given value to the PgRestoreExtraOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgRestoreExtraOptions field.
func (b *ImportApplyConfiguration) WithPgRestoreExtraOptions(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PgRestoreExtraOptions = append(b.PgRestoreExtraOptions, values[i])
	}
	return b
}

// WithPgRestorePredataOptions adds the given value to the PgRestorePredataOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgRestorePredataOptions field.
func (b *ImportApplyConfiguration) WithPgRestorePredataOptions(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PgRestorePredataOptions = append(b.PgRestorePredataOptions, values[i])
	}
	return b
}

// WithPgRestoreDataOptions adds the given value to the PgRestoreDataOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgRestoreDataOptions field.
func (b *ImportApplyConfiguration) WithPgRestoreDataOptions(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PgRestoreDataOptions = append(b.PgRestoreDataOptions, values[i])
	}
	return b
}

// WithPgRestorePostdataOptions adds the given value to the PgRestorePostdataOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgRestorePostdataOptions field.
func (b *ImportApplyConfiguration) WithPgRestorePostdataOptions(values ...string) *ImportApplyConfiguration {
	for i := range values {
		b.PgRestorePostdataOptions = append(b.PgRestorePostdataOptions, values[i])
	}
	return b
}
