// Code generated by controller-gen. DO NOT EDIT.

package v1

// InstanceReportedStateApplyConfiguration represents a declarative configuration of the InstanceReportedState type for use
// with apply.
//
// InstanceReportedState describes the last reported state of an instance during a reconciliation loop
type InstanceReportedStateApplyConfiguration struct {
	// indicates if an instance is the primary one
	IsPrimary *bool `json:"isPrimary,omitempty"`
	// indicates on which TimelineId the instance is
	TimeLineID *int `json:"timeLineID,omitempty"`
	// IP address of the instance
	IP *string `json:"ip,omitempty"`
}

// InstanceReportedStateApplyConfiguration constructs a declarative configuration of the InstanceReportedState type for use with
// apply.
func InstanceReportedState() *InstanceReportedStateApplyConfiguration {
	return &InstanceReportedStateApplyConfiguration{}
}

// WithIsPrimary sets the IsPrimary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsPrimary field is set to the value of the last call.
func (b *InstanceReportedStateApplyConfiguration) WithIsPrimary(value bool) *InstanceReportedStateApplyConfiguration {
	b.IsPrimary = &value
	return b
}

// WithTimeLineID sets the TimeLineID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeLineID field is set to the value of the last call.
func (b *InstanceReportedStateApplyConfiguration) WithTimeLineID(value int) *InstanceReportedStateApplyConfiguration {
	b.TimeLineID = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *InstanceReportedStateApplyConfiguration) WithIP(value string) *InstanceReportedStateApplyConfiguration {
	b.IP = &value
	return b
}
