// Code generated by controller-gen. DO NOT EDIT.

package v1

// IsolationCheckConfigurationApplyConfiguration represents a declarative configuration of the IsolationCheckConfiguration type for use
// with apply.
//
// IsolationCheckConfiguration contains the configuration for the isolation check
// functionality in the liveness probe
type IsolationCheckConfigurationApplyConfiguration struct {
	// Whether primary isolation checking is enabled for the liveness probe
	Enabled *bool `json:"enabled,omitempty"`
	// Timeout in milliseconds for requests during the primary isolation check
	RequestTimeout *int `json:"requestTimeout,omitempty"`
	// Timeout in milliseconds for connections during the primary isolation check
	ConnectionTimeout *int `json:"connectionTimeout,omitempty"`
}

// IsolationCheckConfigurationApplyConfiguration constructs a declarative configuration of the IsolationCheckConfiguration type for use with
// apply.
func IsolationCheckConfiguration() *IsolationCheckConfigurationApplyConfiguration {
	return &IsolationCheckConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *IsolationCheckConfigurationApplyConfiguration) WithEnabled(value bool) *IsolationCheckConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithRequestTimeout sets the RequestTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestTimeout field is set to the value of the last call.
func (b *IsolationCheckConfigurationApplyConfiguration) WithRequestTimeout(value int) *IsolationCheckConfigurationApplyConfiguration {
	b.RequestTimeout = &value
	return b
}

// WithConnectionTimeout sets the ConnectionTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionTimeout field is set to the value of the last call.
func (b *IsolationCheckConfigurationApplyConfiguration) WithConnectionTimeout(value int) *IsolationCheckConfigurationApplyConfiguration {
	b.ConnectionTimeout = &value
	return b
}
