// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// LDAPConfigApplyConfiguration represents a declarative configuration of the LDAPConfig type for use
// with apply.
//
// LDAPConfig contains the parameters needed for LDAP authentication
type LDAPConfigApplyConfiguration struct {
	// LDAP hostname or IP address
	Server *string `json:"server,omitempty"`
	// LDAP server port
	Port *int `json:"port,omitempty"`
	// LDAP schema to be used, possible options are `ldap` and `ldaps`
	Scheme *apiv1.LDAPScheme `json:"scheme,omitempty"`
	// Bind as authentication configuration
	BindAsAuth *LDAPBindAsAuthApplyConfiguration `json:"bindAsAuth,omitempty"`
	// Bind+Search authentication configuration
	BindSearchAuth *LDAPBindSearchAuthApplyConfiguration `json:"bindSearchAuth,omitempty"`
	// Set to 'true' to enable LDAP over TLS. 'false' is default
	TLS *bool `json:"tls,omitempty"`
}

// LDAPConfigApplyConfiguration constructs a declarative configuration of the LDAPConfig type for use with
// apply.
func LDAPConfig() *LDAPConfigApplyConfiguration {
	return &LDAPConfigApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithServer(value string) *LDAPConfigApplyConfiguration {
	b.Server = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithPort(value int) *LDAPConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithScheme sets the Scheme field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheme field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithScheme(value apiv1.LDAPScheme) *LDAPConfigApplyConfiguration {
	b.Scheme = &value
	return b
}

// WithBindAsAuth sets the BindAsAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindAsAuth field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithBindAsAuth(value *LDAPBindAsAuthApplyConfiguration) *LDAPConfigApplyConfiguration {
	b.BindAsAuth = value
	return b
}

// WithBindSearchAuth sets the BindSearchAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindSearchAuth field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithBindSearchAuth(value *LDAPBindSearchAuthApplyConfiguration) *LDAPConfigApplyConfiguration {
	b.BindSearchAuth = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *LDAPConfigApplyConfiguration) WithTLS(value bool) *LDAPConfigApplyConfiguration {
	b.TLS = &value
	return b
}
