// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// LDAPBindSearchAuthApplyConfiguration represents a declarative configuration of the LDAPBindSearchAuth type for use
// with apply.
//
// LDAPBindSearchAuth provides the required fields to use
// the bind+search LDAP authentication process
type LDAPBindSearchAuthApplyConfiguration struct {
	// Root DN to begin the user search
	BaseDN *string `json:"baseDN,omitempty"`
	// DN of the user to bind to the directory
	BindDN *string `json:"bindDN,omitempty"`
	// Secret with the password for the user to bind to the directory
	BindPassword *corev1.SecretKeySelector `json:"bindPassword,omitempty"`
	// Attribute to match against the username
	SearchAttribute *string `json:"searchAttribute,omitempty"`
	// Search filter to use when doing the search+bind authentication
	SearchFilter *string `json:"searchFilter,omitempty"`
}

// LDAPBindSearchAuthApplyConfiguration constructs a declarative configuration of the LDAPBindSearchAuth type for use with
// apply.
func LDAPBindSearchAuth() *LDAPBindSearchAuthApplyConfiguration {
	return &LDAPBindSearchAuthApplyConfiguration{}
}

// WithBaseDN sets the BaseDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDN field is set to the value of the last call.
func (b *LDAPBindSearchAuthApplyConfiguration) WithBaseDN(value string) *LDAPBindSearchAuthApplyConfiguration {
	b.BaseDN = &value
	return b
}

// WithBindDN sets the BindDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindDN field is set to the value of the last call.
func (b *LDAPBindSearchAuthApplyConfiguration) WithBindDN(value string) *LDAPBindSearchAuthApplyConfiguration {
	b.BindDN = &value
	return b
}

// WithBindPassword sets the BindPassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindPassword field is set to the value of the last call.
func (b *LDAPBindSearchAuthApplyConfiguration) WithBindPassword(value corev1.SecretKeySelector) *LDAPBindSearchAuthApplyConfiguration {
	b.BindPassword = &value
	return b
}

// WithSearchAttribute sets the SearchAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchAttribute field is set to the value of the last call.
func (b *LDAPBindSearchAuthApplyConfiguration) WithSearchAttribute(value string) *LDAPBindSearchAuthApplyConfiguration {
	b.SearchAttribute = &value
	return b
}

// WithSearchFilter sets the SearchFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchFilter field is set to the value of the last call.
func (b *LDAPBindSearchAuthApplyConfiguration) WithSearchFilter(value string) *LDAPBindSearchAuthApplyConfiguration {
	b.SearchFilter = &value
	return b
}
