// Code generated by controller-gen. DO NOT EDIT.

package v1

// LivenessProbeApplyConfiguration represents a declarative configuration of the LivenessProbe type for use
// with apply.
//
// LivenessProbe is the configuration of the liveness probe
type LivenessProbeApplyConfiguration struct {
	// Probe is the standard probe configuration
	ProbeApplyConfiguration `json:",inline"`
	// Configure the feature that extends the liveness probe for a primary
	// instance. In addition to the basic checks, this verifies whether the
	// primary is isolated from the Kubernetes API server and from its
	// replicas, ensuring that it can be safely shut down if network
	// partition or API unavailability is detected. Enabled by default.
	IsolationCheck *IsolationCheckConfigurationApplyConfiguration `json:"isolationCheck,omitempty"`
}

// LivenessProbeApplyConfiguration constructs a declarative configuration of the LivenessProbe type for use with
// apply.
func LivenessProbe() *LivenessProbeApplyConfiguration {
	return &LivenessProbeApplyConfiguration{}
}

// WithInitialDelaySeconds sets the InitialDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialDelaySeconds field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithInitialDelaySeconds(value int32) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.InitialDelaySeconds = &value
	return b
}

// WithTimeoutSeconds sets the TimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutSeconds field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithTimeoutSeconds(value int32) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.TimeoutSeconds = &value
	return b
}

// WithPeriodSeconds sets the PeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeriodSeconds field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithPeriodSeconds(value int32) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.PeriodSeconds = &value
	return b
}

// WithSuccessThreshold sets the SuccessThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessThreshold field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithSuccessThreshold(value int32) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.SuccessThreshold = &value
	return b
}

// WithFailureThreshold sets the FailureThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureThreshold field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithFailureThreshold(value int32) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.FailureThreshold = &value
	return b
}

// WithTerminationGracePeriodSeconds sets the TerminationGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationGracePeriodSeconds field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithTerminationGracePeriodSeconds(value int64) *LivenessProbeApplyConfiguration {
	b.ProbeApplyConfiguration.TerminationGracePeriodSeconds = &value
	return b
}

// WithIsolationCheck sets the IsolationCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsolationCheck field is set to the value of the last call.
func (b *LivenessProbeApplyConfiguration) WithIsolationCheck(value *IsolationCheckConfigurationApplyConfiguration) *LivenessProbeApplyConfiguration {
	b.IsolationCheck = value
	return b
}
