// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ManagedServiceApplyConfiguration represents a declarative configuration of the ManagedService type for use
// with apply.
//
// ManagedService represents a specific service managed by the cluster.
// It includes the type of service and its associated template specification.
type ManagedServiceApplyConfiguration struct {
	// SelectorType specifies the type of selectors that the service will have.
	// Valid values are "rw", "r", and "ro", representing read-write, read, and read-only services.
	SelectorType *apiv1.ServiceSelectorType `json:"selectorType,omitempty"`
	// UpdateStrategy describes how the service differences should be reconciled
	UpdateStrategy *apiv1.ServiceUpdateStrategy `json:"updateStrategy,omitempty"`
	// ServiceTemplate is the template specification for the service.
	ServiceTemplate *ServiceTemplateSpecApplyConfiguration `json:"serviceTemplate,omitempty"`
}

// ManagedServiceApplyConfiguration constructs a declarative configuration of the ManagedService type for use with
// apply.
func ManagedService() *ManagedServiceApplyConfiguration {
	return &ManagedServiceApplyConfiguration{}
}

// WithSelectorType sets the SelectorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectorType field is set to the value of the last call.
func (b *ManagedServiceApplyConfiguration) WithSelectorType(value apiv1.ServiceSelectorType) *ManagedServiceApplyConfiguration {
	b.SelectorType = &value
	return b
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *ManagedServiceApplyConfiguration) WithUpdateStrategy(value apiv1.ServiceUpdateStrategy) *ManagedServiceApplyConfiguration {
	b.UpdateStrategy = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *ManagedServiceApplyConfiguration) WithServiceTemplate(value *ServiceTemplateSpecApplyConfiguration) *ManagedServiceApplyConfiguration {
	b.ServiceTemplate = value
	return b
}
