// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ManagedServicesApplyConfiguration represents a declarative configuration of the ManagedServices type for use
// with apply.
//
// ManagedServices represents the services managed by the cluster.
type ManagedServicesApplyConfiguration struct {
	// DisabledDefaultServices is a list of service types that are disabled by default.
	// Valid values are "r", and "ro", representing read, and read-only services.
	DisabledDefaultServices []apiv1.ServiceSelectorType `json:"disabledDefaultServices,omitempty"`
	// Additional is a list of additional managed services specified by the user.
	Additional []ManagedServiceApplyConfiguration `json:"additional,omitempty"`
}

// ManagedServicesApplyConfiguration constructs a declarative configuration of the ManagedServices type for use with
// apply.
func ManagedServices() *ManagedServicesApplyConfiguration {
	return &ManagedServicesApplyConfiguration{}
}

// WithDisabledDefaultServices adds the given value to the DisabledDefaultServices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DisabledDefaultServices field.
func (b *ManagedServicesApplyConfiguration) WithDisabledDefaultServices(values ...apiv1.ServiceSelectorType) *ManagedServicesApplyConfiguration {
	for i := range values {
		b.DisabledDefaultServices = append(b.DisabledDefaultServices, values[i])
	}
	return b
}

// WithAdditional adds the given value to the Additional field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Additional field.
func (b *ManagedServicesApplyConfiguration) WithAdditional(values ...*ManagedServiceApplyConfiguration) *ManagedServicesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditional")
		}
		b.Additional = append(b.Additional, *values[i])
	}
	return b
}
