// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ManagedRolesApplyConfiguration represents a declarative configuration of the ManagedRoles type for use
// with apply.
//
// ManagedRoles tracks the status of a cluster's managed roles
type ManagedRolesApplyConfiguration struct {
	// ByStatus gives the list of roles in each state
	ByStatus map[apiv1.RoleStatus][]string `json:"byStatus,omitempty"`
	// CannotReconcile lists roles that cannot be reconciled in PostgreSQL,
	// with an explanation of the cause
	CannotReconcile map[string][]string `json:"cannotReconcile,omitempty"`
	// PasswordStatus gives the last transaction id and password secret version for each managed role
	PasswordStatus map[string]PasswordStateApplyConfiguration `json:"passwordStatus,omitempty"`
}

// ManagedRolesApplyConfiguration constructs a declarative configuration of the ManagedRoles type for use with
// apply.
func ManagedRoles() *ManagedRolesApplyConfiguration {
	return &ManagedRolesApplyConfiguration{}
}

// WithByStatus puts the entries into the ByStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ByStatus field,
// overwriting an existing map entries in ByStatus field with the same key.
func (b *ManagedRolesApplyConfiguration) WithByStatus(entries map[apiv1.RoleStatus][]string) *ManagedRolesApplyConfiguration {
	if b.ByStatus == nil && len(entries) > 0 {
		b.ByStatus = make(map[apiv1.RoleStatus][]string, len(entries))
	}
	for k, v := range entries {
		b.ByStatus[k] = v
	}
	return b
}

// WithCannotReconcile puts the entries into the CannotReconcile field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CannotReconcile field,
// overwriting an existing map entries in CannotReconcile field with the same key.
func (b *ManagedRolesApplyConfiguration) WithCannotReconcile(entries map[string][]string) *ManagedRolesApplyConfiguration {
	if b.CannotReconcile == nil && len(entries) > 0 {
		b.CannotReconcile = make(map[string][]string, len(entries))
	}
	for k, v := range entries {
		b.CannotReconcile[k] = v
	}
	return b
}

// WithPasswordStatus puts the entries into the PasswordStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PasswordStatus field,
// overwriting an existing map entries in PasswordStatus field with the same key.
func (b *ManagedRolesApplyConfiguration) WithPasswordStatus(entries map[string]PasswordStateApplyConfiguration) *ManagedRolesApplyConfiguration {
	if b.PasswordStatus == nil && len(entries) > 0 {
		b.PasswordStatus = make(map[string]PasswordStateApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.PasswordStatus[k] = v
	}
	return b
}
