// Code generated by controller-gen. DO NOT EDIT.

package v1

// ManagedConfigurationApplyConfiguration represents a declarative configuration of the ManagedConfiguration type for use
// with apply.
//
// ManagedConfiguration represents the portions of PostgreSQL that are managed
// by the instance manager
type ManagedConfigurationApplyConfiguration struct {
	// Database roles managed by the `Cluster`
	Roles []RoleConfigurationApplyConfiguration `json:"roles,omitempty"`
	// Services roles managed by the `Cluster`
	Services *ManagedServicesApplyConfiguration `json:"services,omitempty"`
}

// ManagedConfigurationApplyConfiguration constructs a declarative configuration of the ManagedConfiguration type for use with
// apply.
func ManagedConfiguration() *ManagedConfigurationApplyConfiguration {
	return &ManagedConfigurationApplyConfiguration{}
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *ManagedConfigurationApplyConfiguration) WithRoles(values ...*RoleConfigurationApplyConfiguration) *ManagedConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoles")
		}
		b.Roles = append(b.Roles, *values[i])
	}
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *ManagedConfigurationApplyConfiguration) WithServices(value *ManagedServicesApplyConfiguration) *ManagedConfigurationApplyConfiguration {
	b.Services = value
	return b
}
