// Code generated by controller-gen. DO NOT EDIT.

package v1

// NodeMaintenanceWindowApplyConfiguration represents a declarative configuration of the NodeMaintenanceWindow type for use
// with apply.
//
// NodeMaintenanceWindow contains information that the operator
// will use while upgrading the underlying node.
//
// This option is only useful when the chosen storage prevents the Pods
// from being freely moved across nodes.
type NodeMaintenanceWindowApplyConfiguration struct {
	// Reuse the existing PVC (wait for the node to come
	// up again) or not (recreate it elsewhere - when `instances` >1)
	ReusePVC *bool `json:"reusePVC,omitempty"`
	// Is there a node maintenance activity in progress?
	InProgress *bool `json:"inProgress,omitempty"`
}

// NodeMaintenanceWindowApplyConfiguration constructs a declarative configuration of the NodeMaintenanceWindow type for use with
// apply.
func NodeMaintenanceWindow() *NodeMaintenanceWindowApplyConfiguration {
	return &NodeMaintenanceWindowApplyConfiguration{}
}

// WithReusePVC sets the ReusePVC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReusePVC field is set to the value of the last call.
func (b *NodeMaintenanceWindowApplyConfiguration) WithReusePVC(value bool) *NodeMaintenanceWindowApplyConfiguration {
	b.ReusePVC = &value
	return b
}

// WithInProgress sets the InProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgress field is set to the value of the last call.
func (b *NodeMaintenanceWindowApplyConfiguration) WithInProgress(value bool) *NodeMaintenanceWindowApplyConfiguration {
	b.InProgress = &value
	return b
}
