// Code generated by controller-gen. DO NOT EDIT.

package v1

// OnlineConfigurationApplyConfiguration represents a declarative configuration of the OnlineConfiguration type for use
// with apply.
//
// OnlineConfiguration contains the configuration parameters for the online volume snapshot
type OnlineConfigurationApplyConfiguration struct {
	// If false, the function will return immediately after the backup is completed,
	// without waiting for WAL to be archived.
	// This behavior is only useful with backup software that independently monitors WAL archiving.
	// Otherwise, WAL required to make the backup consistent might be missing and make the backup useless.
	// By default, or when this parameter is true, pg_backup_stop will wait for WAL to be archived when archiving is
	// enabled.
	// On a standby, this means that it will wait only when archive_mode = always.
	// If write activity on the primary is low, it may be useful to run pg_switch_wal on the primary in order to trigger
	// an immediate segment switch.
	WaitForArchive *bool `json:"waitForArchive,omitempty"`
	// Control whether the I/O workload for the backup initial checkpoint will
	// be limited, according to the `checkpoint_completion_target` setting on
	// the PostgreSQL server. If set to true, an immediate checkpoint will be
	// used, meaning PostgreSQL will complete the checkpoint as soon as
	// possible. `false` by default.
	ImmediateCheckpoint *bool `json:"immediateCheckpoint,omitempty"`
}

// OnlineConfigurationApplyConfiguration constructs a declarative configuration of the OnlineConfiguration type for use with
// apply.
func OnlineConfiguration() *OnlineConfigurationApplyConfiguration {
	return &OnlineConfigurationApplyConfiguration{}
}

// WithWaitForArchive sets the WaitForArchive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WaitForArchive field is set to the value of the last call.
func (b *OnlineConfigurationApplyConfiguration) WithWaitForArchive(value bool) *OnlineConfigurationApplyConfiguration {
	b.WaitForArchive = &value
	return b
}

// WithImmediateCheckpoint sets the ImmediateCheckpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImmediateCheckpoint field is set to the value of the last call.
func (b *OnlineConfigurationApplyConfiguration) WithImmediateCheckpoint(value bool) *OnlineConfigurationApplyConfiguration {
	b.ImmediateCheckpoint = &value
	return b
}
