// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// OptionSpecApplyConfiguration represents a declarative configuration of the OptionSpec type for use
// with apply.
//
// OptionSpec holds the name, value and the ensure field for an option
type OptionSpecApplyConfiguration struct {
	// Name of the option
	Name *string `json:"name,omitempty"`
	// Value of the option
	Value *string `json:"value,omitempty"`
	// Specifies whether an option should be present or absent in
	// the database. If set to `present`, the option will be
	// created if it does not exist. If set to `absent`, the
	// option will be removed if it exists.
	Ensure *apiv1.EnsureOption `json:"ensure,omitempty"`
}

// OptionSpecApplyConfiguration constructs a declarative configuration of the OptionSpec type for use with
// apply.
func OptionSpec() *OptionSpecApplyConfiguration {
	return &OptionSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OptionSpecApplyConfiguration) WithName(value string) *OptionSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *OptionSpecApplyConfiguration) WithValue(value string) *OptionSpecApplyConfiguration {
	b.Value = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *OptionSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *OptionSpecApplyConfiguration {
	b.Ensure = &value
	return b
}
