// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
)

// PgBackRestGCSApplyConfiguration represents a declarative configuration of the PgBackRestGCS type for use
// with apply.
//
// PgBackRestGCS defines the Google Cloud Storage configuration for pgbackrest.
type PgBackRestGCSApplyConfiguration struct {
	// The GCS bucket name
	Bucket *string `json:"bucket,omitempty"`
	// KeyType selects the authentication method. "auto" uses Workload
	// Identity / Application Default Credentials (the GKE path). "service"
	// reads a service account JSON key from KeyRef. "token" uses a bearer
	// token from KeyRef.
	KeyType *string `json:"keyType,omitempty"`
	// The GCS endpoint, overriding the automatic endpoint discovery.
	// Rarely needed, mostly for testing against GCS emulators.
	Endpoint *string `json:"endpoint,omitempty"`
	// The reference to a Secret holding the service account JSON key when
	// keyType is "service", or a bearer token when keyType is "token".
	// Required for those key types, must be unset for "auto".
	KeyRef *api.SecretKeySelector `json:"keyRef,omitempty"`
}

// PgBackRestGCSApplyConfiguration constructs a declarative configuration of the PgBackRestGCS type for use with
// apply.
func PgBackRestGCS() *PgBackRestGCSApplyConfiguration {
	return &PgBackRestGCSApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PgBackRestGCSApplyConfiguration) WithBucket(value string) *PgBackRestGCSApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithKeyType sets the KeyType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyType field is set to the value of the last call.
func (b *PgBackRestGCSApplyConfiguration) WithKeyType(value string) *PgBackRestGCSApplyConfiguration {
	b.KeyType = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PgBackRestGCSApplyConfiguration) WithEndpoint(value string) *PgBackRestGCSApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithKeyRef sets the KeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyRef field is set to the value of the last call.
func (b *PgBackRestGCSApplyConfiguration) WithKeyRef(value api.SecretKeySelector) *PgBackRestGCSApplyConfiguration {
	b.KeyRef = &value
	return b
}
