// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
)

// PgBackRestCipherApplyConfiguration represents a declarative configuration of the PgBackRestCipher type for use
// with apply.
//
// PgBackRestCipher defines client-side encryption for a pgbackrest repository.
type PgBackRestCipherApplyConfiguration struct {
	// Type is the cipher used by pgbackrest.
	Type *string `json:"type,omitempty"`
	// Passphrase references the Secret key that contains the repository passphrase.
	Passphrase *api.SecretKeySelector `json:"passphrase,omitempty"`
}

// PgBackRestCipherApplyConfiguration constructs a declarative configuration of the PgBackRestCipher type for use with
// apply.
func PgBackRestCipher() *PgBackRestCipherApplyConfiguration {
	return &PgBackRestCipherApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PgBackRestCipherApplyConfiguration) WithType(value string) *PgBackRestCipherApplyConfiguration {
	b.Type = &value
	return b
}

// WithPassphrase sets the Passphrase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passphrase field is set to the value of the last call.
func (b *PgBackRestCipherApplyConfiguration) WithPassphrase(value api.SecretKeySelector) *PgBackRestCipherApplyConfiguration {
	b.Passphrase = &value
	return b
}
