// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
)

// PgBackRestAzureApplyConfiguration represents a declarative configuration of the PgBackRestAzure type for use
// with apply.
//
// PgBackRestAzure defines the Azure Blob Storage configuration for pgbackrest.
type PgBackRestAzureApplyConfiguration struct {
	// The Azure storage account name
	Account *string `json:"account,omitempty"`
	// The Azure Blob Storage container name
	Container *string `json:"container,omitempty"`
	// KeyType selects the authentication method. "auto" requests a
	// managed-identity token from instance metadata (the AKS path,
	// pgbackrest >= 2.58). "shared" reads the storage account shared key
	// from KeyRef. "sas" reads a shared access signature token from KeyRef.
	KeyType *string `json:"keyType,omitempty"`
	// The Azure Blob Storage endpoint, overriding the default
	// <account>.blob.core.windows.net. Rarely needed, mostly for testing
	// against Azurite.
	Endpoint *string `json:"endpoint,omitempty"`
	// The reference to a Secret holding the storage account shared key when
	// keyType is "shared", or a SAS token when keyType is "sas". Required
	// for those key types, must be unset for "auto".
	KeyRef *api.SecretKeySelector `json:"keyRef,omitempty"`
}

// PgBackRestAzureApplyConfiguration constructs a declarative configuration of the PgBackRestAzure type for use with
// apply.
func PgBackRestAzure() *PgBackRestAzureApplyConfiguration {
	return &PgBackRestAzureApplyConfiguration{}
}

// WithAccount sets the Account field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Account field is set to the value of the last call.
func (b *PgBackRestAzureApplyConfiguration) WithAccount(value string) *PgBackRestAzureApplyConfiguration {
	b.Account = &value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *PgBackRestAzureApplyConfiguration) WithContainer(value string) *PgBackRestAzureApplyConfiguration {
	b.Container = &value
	return b
}

// WithKeyType sets the KeyType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyType field is set to the value of the last call.
func (b *PgBackRestAzureApplyConfiguration) WithKeyType(value string) *PgBackRestAzureApplyConfiguration {
	b.KeyType = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PgBackRestAzureApplyConfiguration) WithEndpoint(value string) *PgBackRestAzureApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithKeyRef sets the KeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyRef field is set to the value of the last call.
func (b *PgBackRestAzureApplyConfiguration) WithKeyRef(value api.SecretKeySelector) *PgBackRestAzureApplyConfiguration {
	b.KeyRef = &value
	return b
}
