// Code generated by controller-gen. DO NOT EDIT.

package v1

// PgBackRestConfigurationApplyConfiguration represents a declarative configuration of the PgBackRestConfiguration type for use
// with apply.
//
// PgBackRestConfiguration defines the backup configuration using pgbackrest.
type PgBackRestConfigurationApplyConfiguration struct {
	Repository *PgBackRestRepositoryApplyConfiguration `json:"repository,omitempty"`
	Options    *PgBackRestOptionsApplyConfiguration    `json:"options,omitempty"`
	// StanzaName is the pgbackrest stanza this cluster archives to. It is the
	// logical identity of the backup set in the repository (the repo layout is
	// <repoPath>/{archive,backup}/<stanza>/). When unset it defaults to the
	// cluster name.
	StanzaName *string `json:"stanzaName,omitempty"`
}

// PgBackRestConfigurationApplyConfiguration constructs a declarative configuration of the PgBackRestConfiguration type for use with
// apply.
func PgBackRestConfiguration() *PgBackRestConfigurationApplyConfiguration {
	return &PgBackRestConfigurationApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *PgBackRestConfigurationApplyConfiguration) WithRepository(value *PgBackRestRepositoryApplyConfiguration) *PgBackRestConfigurationApplyConfiguration {
	b.Repository = value
	return b
}

// WithOptions sets the Options field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Options field is set to the value of the last call.
func (b *PgBackRestConfigurationApplyConfiguration) WithOptions(value *PgBackRestOptionsApplyConfiguration) *PgBackRestConfigurationApplyConfiguration {
	b.Options = value
	return b
}

// WithStanzaName sets the StanzaName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StanzaName field is set to the value of the last call.
func (b *PgBackRestConfigurationApplyConfiguration) WithStanzaName(value string) *PgBackRestConfigurationApplyConfiguration {
	b.StanzaName = &value
	return b
}
