// Code generated by controller-gen. DO NOT EDIT.

package v1

// PgBackRestRetentionApplyConfiguration represents a declarative configuration of the PgBackRestRetention type for use
// with apply.
//
// PgBackRestRetention defines the backup retention policy for pgbackrest.
type PgBackRestRetentionApplyConfiguration struct {
	// Number of full backups to retain. Required.
	Full *int `json:"full,omitempty"`
	// Type of full backup retention: "count" (number of backups) or "time" (days).
	// Defaults to "count".
	FullType *string `json:"fullType,omitempty"`
	// Number of WAL archive sets to retain. If not set, pgbackrest will
	// use the full backup retention to determine WAL expiration.
	Archive *int `json:"archive,omitempty"`
}

// PgBackRestRetentionApplyConfiguration constructs a declarative configuration of the PgBackRestRetention type for use with
// apply.
func PgBackRestRetention() *PgBackRestRetentionApplyConfiguration {
	return &PgBackRestRetentionApplyConfiguration{}
}

// WithFull sets the Full field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Full field is set to the value of the last call.
func (b *PgBackRestRetentionApplyConfiguration) WithFull(value int) *PgBackRestRetentionApplyConfiguration {
	b.Full = &value
	return b
}

// WithFullType sets the FullType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullType field is set to the value of the last call.
func (b *PgBackRestRetentionApplyConfiguration) WithFullType(value string) *PgBackRestRetentionApplyConfiguration {
	b.FullType = &value
	return b
}

// WithArchive sets the Archive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Archive field is set to the value of the last call.
func (b *PgBackRestRetentionApplyConfiguration) WithArchive(value int) *PgBackRestRetentionApplyConfiguration {
	b.Archive = &value
	return b
}
