// Code generated by controller-gen. DO NOT EDIT.

package v1

// PgBackRestExternalClusterApplyConfiguration represents a declarative configuration of the PgBackRestExternalCluster type for use
// with apply.
//
// PgBackRestExternalCluster defines the pgbackrest configuration for an external cluster,
// used for restore operations. Contains the repository location and optional process-level
// settings (e.g. processMax, delta, priority).
type PgBackRestExternalClusterApplyConfiguration struct {
	Repository *PgBackRestRepositoryApplyConfiguration `json:"repository,omitempty"`
	Options    *PgBackRestOptionsApplyConfiguration    `json:"options,omitempty"`
}

// PgBackRestExternalClusterApplyConfiguration constructs a declarative configuration of the PgBackRestExternalCluster type for use with
// apply.
func PgBackRestExternalCluster() *PgBackRestExternalClusterApplyConfiguration {
	return &PgBackRestExternalClusterApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *PgBackRestExternalClusterApplyConfiguration) WithRepository(value *PgBackRestRepositoryApplyConfiguration) *PgBackRestExternalClusterApplyConfiguration {
	b.Repository = value
	return b
}

// WithOptions sets the Options field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Options field is set to the value of the last call.
func (b *PgBackRestExternalClusterApplyConfiguration) WithOptions(value *PgBackRestOptionsApplyConfiguration) *PgBackRestExternalClusterApplyConfiguration {
	b.Options = value
	return b
}
