// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
)

// PgBackRestS3ApplyConfiguration represents a declarative configuration of the PgBackRestS3 type for use
// with apply.
//
// PgBackRestS3 defines the S3-compatible storage configuration for pgbackrest.
type PgBackRestS3ApplyConfiguration struct {
	// The S3 bucket name
	Bucket *string `json:"bucket,omitempty"`
	// The S3 region
	Region *string `json:"region,omitempty"`
	// The S3 endpoint, overriding the automatic endpoint discovery.
	// Required for non-AWS S3-compatible storage (e.g. MinIO).
	Endpoint *string `json:"endpoint,omitempty"`
	// The reference to the access key id
	AccessKeyID *api.SecretKeySelector `json:"accessKeyId,omitempty"`
	// The reference to the secret access key
	SecretAccessKey *api.SecretKeySelector `json:"secretAccessKey,omitempty"`
	// Use IAM role-based authentication (e.g. IRSA, instance profile).
	// Sets pgbackrest repo1-s3-key-type=auto.
	InheritFromIAMRole *bool `json:"inheritFromIAMRole,omitempty"`
}

// PgBackRestS3ApplyConfiguration constructs a declarative configuration of the PgBackRestS3 type for use with
// apply.
func PgBackRestS3() *PgBackRestS3ApplyConfiguration {
	return &PgBackRestS3ApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithBucket(value string) *PgBackRestS3ApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithRegion(value string) *PgBackRestS3ApplyConfiguration {
	b.Region = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithEndpoint(value string) *PgBackRestS3ApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithAccessKeyID sets the AccessKeyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKeyID field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithAccessKeyID(value api.SecretKeySelector) *PgBackRestS3ApplyConfiguration {
	b.AccessKeyID = &value
	return b
}

// WithSecretAccessKey sets the SecretAccessKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretAccessKey field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithSecretAccessKey(value api.SecretKeySelector) *PgBackRestS3ApplyConfiguration {
	b.SecretAccessKey = &value
	return b
}

// WithInheritFromIAMRole sets the InheritFromIAMRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InheritFromIAMRole field is set to the value of the last call.
func (b *PgBackRestS3ApplyConfiguration) WithInheritFromIAMRole(value bool) *PgBackRestS3ApplyConfiguration {
	b.InheritFromIAMRole = &value
	return b
}
