// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// PgBackRestRepositoryApplyConfiguration represents a declarative configuration of the PgBackRestRepository type for use
// with apply.
//
// PgBackRestRepository defines the storage repository for pgbackrest.
// Exactly one of s3, gcs, or azure must be specified.
type PgBackRestRepositoryApplyConfiguration struct {
	S3    *PgBackRestS3ApplyConfiguration  `json:"s3,omitempty"`
	GCS   *PgBackRestGCSApplyConfiguration `json:"gcs,omitempty"`
	Azure *apiv1.PgBackRestAzure           `json:"azure,omitempty"`
	// Cipher configures client-side encryption for this repository.
	Cipher *PgBackRestCipherApplyConfiguration `json:"cipher,omitempty"`
}

// PgBackRestRepositoryApplyConfiguration constructs a declarative configuration of the PgBackRestRepository type for use with
// apply.
func PgBackRestRepository() *PgBackRestRepositoryApplyConfiguration {
	return &PgBackRestRepositoryApplyConfiguration{}
}

// WithS3 sets the S3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3 field is set to the value of the last call.
func (b *PgBackRestRepositoryApplyConfiguration) WithS3(value *PgBackRestS3ApplyConfiguration) *PgBackRestRepositoryApplyConfiguration {
	b.S3 = value
	return b
}

// WithGCS sets the GCS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCS field is set to the value of the last call.
func (b *PgBackRestRepositoryApplyConfiguration) WithGCS(value *PgBackRestGCSApplyConfiguration) *PgBackRestRepositoryApplyConfiguration {
	b.GCS = value
	return b
}

// WithAzure sets the Azure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Azure field is set to the value of the last call.
func (b *PgBackRestRepositoryApplyConfiguration) WithAzure(value apiv1.PgBackRestAzure) *PgBackRestRepositoryApplyConfiguration {
	b.Azure = &value
	return b
}

// WithCipher sets the Cipher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cipher field is set to the value of the last call.
func (b *PgBackRestRepositoryApplyConfiguration) WithCipher(value *PgBackRestCipherApplyConfiguration) *PgBackRestRepositoryApplyConfiguration {
	b.Cipher = value
	return b
}
