// Code generated by controller-gen. DO NOT EDIT.

package v1

// PgBackRestOptionsApplyConfiguration represents a declarative configuration of the PgBackRestOptions type for use
// with apply.
//
// PgBackRestOptions defines process-level settings for pgbackrest.
type PgBackRestOptionsApplyConfiguration struct {
	// Compression algorithm. Defaults to "lz4".
	CompressType *string `json:"compressType,omitempty"`
	// Compression level (0-9). The meaning depends on the algorithm.
	CompressLevel *int `json:"compressLevel,omitempty"`
	// Maximum number of parallel processes for backup/restore.
	ProcessMax *int `json:"processMax,omitempty"`
	// Force an immediate checkpoint at backup start instead of
	// waiting for the next scheduled checkpoint.
	StartFast *bool `json:"startFast,omitempty"`
	// Only restore files that have changed. Speeds up restores.
	Delta *bool `json:"delta,omitempty"`
	// Enable async WAL archiving for better throughput.
	ArchiveAsync *bool `json:"archiveAsync,omitempty"`
	// Max size of the WAL archive push queue when archiveAsync is enabled.
	// Uses pgbackrest size format (e.g. "1GiB", "256MiB").
	ArchivePushQueueMax *string `json:"archivePushQueueMax,omitempty"`
	// Max size of the WAL restore queue when archiveAsync is enabled.
	// Uses pgbackrest size format (e.g. "1GiB", "256MiB").
	ArchiveGetQueueMax *string `json:"archiveGetQueueMax,omitempty"`
	// Bundle small files together for more efficient object storage operations.
	// pgbackrest defaults: bundle-limit=2MiB (max file size eligible for bundling),
	// bundle-size=20MiB (target size per bundle). Files larger than bundle-limit
	// are stored individually.
	// TODO: consider exposing bundleLimit and bundleSize as tunable options
	Bundle *bool `json:"bundle,omitempty"`
	// Enable block-level incremental backup. Only changed blocks within files
	// are backed up instead of entire files. Requires Bundle to be true.
	// Requires pgbackrest 2.46+.
	BlockIncremental *bool `json:"blockIncremental,omitempty"`
	// Take backups from a standby instance instead of the primary,
	// reducing load on the primary.
	BackupStandby *bool `json:"backupStandby,omitempty"`
	// Allow for deprioritization when taking CPU (nice value), making sure we are
	// not impacting postgres TPS. If not set defaults to 0 - which means no
	// deprioritization. Do not go below 0 because that would make it more important than postgres
	Priority *int `json:"priority,omitempty"`
	// Backup retention policy.
	Retention *PgBackRestRetentionApplyConfiguration `json:"retention,omitempty"`
	// RepoPath is the pgbackrest repo1-path — the prefix in the storage
	// backend where backups and WAL archives are stored. When unset, it
	// defaults to /<clusterName>. Configure this to isolate a new cluster
	// incarnation from existing data under the default path, or to restore
	// from a custom path.
	RepoPath *string `json:"repoPath,omitempty"`
}

// PgBackRestOptionsApplyConfiguration constructs a declarative configuration of the PgBackRestOptions type for use with
// apply.
func PgBackRestOptions() *PgBackRestOptionsApplyConfiguration {
	return &PgBackRestOptionsApplyConfiguration{}
}

// WithCompressType sets the CompressType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompressType field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithCompressType(value string) *PgBackRestOptionsApplyConfiguration {
	b.CompressType = &value
	return b
}

// WithCompressLevel sets the CompressLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompressLevel field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithCompressLevel(value int) *PgBackRestOptionsApplyConfiguration {
	b.CompressLevel = &value
	return b
}

// WithProcessMax sets the ProcessMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessMax field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithProcessMax(value int) *PgBackRestOptionsApplyConfiguration {
	b.ProcessMax = &value
	return b
}

// WithStartFast sets the StartFast field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartFast field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithStartFast(value bool) *PgBackRestOptionsApplyConfiguration {
	b.StartFast = &value
	return b
}

// WithDelta sets the Delta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delta field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithDelta(value bool) *PgBackRestOptionsApplyConfiguration {
	b.Delta = &value
	return b
}

// WithArchiveAsync sets the ArchiveAsync field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchiveAsync field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithArchiveAsync(value bool) *PgBackRestOptionsApplyConfiguration {
	b.ArchiveAsync = &value
	return b
}

// WithArchivePushQueueMax sets the ArchivePushQueueMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchivePushQueueMax field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithArchivePushQueueMax(value string) *PgBackRestOptionsApplyConfiguration {
	b.ArchivePushQueueMax = &value
	return b
}

// WithArchiveGetQueueMax sets the ArchiveGetQueueMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArchiveGetQueueMax field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithArchiveGetQueueMax(value string) *PgBackRestOptionsApplyConfiguration {
	b.ArchiveGetQueueMax = &value
	return b
}

// WithBundle sets the Bundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bundle field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithBundle(value bool) *PgBackRestOptionsApplyConfiguration {
	b.Bundle = &value
	return b
}

// WithBlockIncremental sets the BlockIncremental field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockIncremental field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithBlockIncremental(value bool) *PgBackRestOptionsApplyConfiguration {
	b.BlockIncremental = &value
	return b
}

// WithBackupStandby sets the BackupStandby field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupStandby field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithBackupStandby(value bool) *PgBackRestOptionsApplyConfiguration {
	b.BackupStandby = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithPriority(value int) *PgBackRestOptionsApplyConfiguration {
	b.Priority = &value
	return b
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithRetention(value *PgBackRestRetentionApplyConfiguration) *PgBackRestOptionsApplyConfiguration {
	b.Retention = value
	return b
}

// WithRepoPath sets the RepoPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepoPath field is set to the value of the last call.
func (b *PgBackRestOptionsApplyConfiguration) WithRepoPath(value string) *PgBackRestOptionsApplyConfiguration {
	b.RepoPath = &value
	return b
}
