// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// PgBouncerSpecApplyConfiguration represents a declarative configuration of the PgBouncerSpec type for use
// with apply.
//
// PgBouncerSpec defines how to configure PgBouncer
type PgBouncerSpecApplyConfiguration struct {
	// The pool mode. Default: `session`.
	PoolMode *apiv1.PgBouncerPoolMode `json:"poolMode,omitempty"`
	// ServerTLSSecret, when pointing to a TLS secret, provides pgbouncer's
	// `server_tls_key_file` and `server_tls_cert_file`, used when
	// authenticating against PostgreSQL.
	ServerTLSSecret *corev1.LocalObjectReferenceApplyConfiguration `json:"serverTLSSecret,omitempty"`
	// ServerCASecret provides PgBouncer’s server_tls_ca_file, the root
	// CA for validating PostgreSQL certificates
	ServerCASecret *corev1.LocalObjectReferenceApplyConfiguration `json:"serverCASecret,omitempty"`
	// ClientCASecret provides PgBouncer’s client_tls_ca_file, the root
	// CA for validating client certificates
	ClientCASecret *corev1.LocalObjectReferenceApplyConfiguration `json:"clientCASecret,omitempty"`
	// ClientTLSSecret provides PgBouncer’s client_tls_key_file (private key)
	// and client_tls_cert_file (certificate) used to accept client connections
	ClientTLSSecret *corev1.LocalObjectReferenceApplyConfiguration `json:"clientTLSSecret,omitempty"`
	// The credentials of the user that need to be used for the authentication
	// query. In case it is specified, also an AuthQuery
	// (e.g. "SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1")
	// has to be specified and no automatic CNPG Cluster integration will be triggered.
	//
	// Deprecated.
	AuthQuerySecret *corev1.LocalObjectReferenceApplyConfiguration `json:"authQuerySecret,omitempty"`
	// The query that will be used to download the hash of the password
	// of a certain user. Default: "SELECT usename, passwd FROM public.user_search($1)".
	// In case it is specified, also an AuthQuerySecret has to be specified and
	// no automatic CNPG Cluster integration will be triggered.
	AuthQuery *string `json:"authQuery,omitempty"`
	// Additional parameters to be passed to PgBouncer - please check
	// the CNPG documentation for a list of options you can configure
	Parameters map[string]string `json:"parameters,omitempty"`
	// PostgreSQL Host Based Authentication rules (lines to be appended
	// to the pg_hba.conf file)
	PgHBA []string `json:"pg_hba,omitempty"`
	// When set to `true`, PgBouncer will disconnect from the PostgreSQL
	// server, first waiting for all queries to complete, and pause all new
	// client connections until this value is set to `false` (default). Internally,
	// the operator calls PgBouncer's `PAUSE` and `RESUME` commands.
	Paused *bool `json:"paused,omitempty"`
}

// PgBouncerSpecApplyConfiguration constructs a declarative configuration of the PgBouncerSpec type for use with
// apply.
func PgBouncerSpec() *PgBouncerSpecApplyConfiguration {
	return &PgBouncerSpecApplyConfiguration{}
}

// WithPoolMode sets the PoolMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolMode field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithPoolMode(value apiv1.PgBouncerPoolMode) *PgBouncerSpecApplyConfiguration {
	b.PoolMode = &value
	return b
}

// WithServerTLSSecret sets the ServerTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerTLSSecret field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithServerTLSSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *PgBouncerSpecApplyConfiguration {
	b.ServerTLSSecret = value
	return b
}

// WithServerCASecret sets the ServerCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerCASecret field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithServerCASecret(value *corev1.LocalObjectReferenceApplyConfiguration) *PgBouncerSpecApplyConfiguration {
	b.ServerCASecret = value
	return b
}

// WithClientCASecret sets the ClientCASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCASecret field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithClientCASecret(value *corev1.LocalObjectReferenceApplyConfiguration) *PgBouncerSpecApplyConfiguration {
	b.ClientCASecret = value
	return b
}

// WithClientTLSSecret sets the ClientTLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientTLSSecret field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithClientTLSSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *PgBouncerSpecApplyConfiguration {
	b.ClientTLSSecret = value
	return b
}

// WithAuthQuerySecret sets the AuthQuerySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthQuerySecret field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithAuthQuerySecret(value *corev1.LocalObjectReferenceApplyConfiguration) *PgBouncerSpecApplyConfiguration {
	b.AuthQuerySecret = value
	return b
}

// WithAuthQuery sets the AuthQuery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthQuery field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithAuthQuery(value string) *PgBouncerSpecApplyConfiguration {
	b.AuthQuery = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *PgBouncerSpecApplyConfiguration) WithParameters(entries map[string]string) *PgBouncerSpecApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}

// WithPgHBA adds the given value to the PgHBA field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PgHBA field.
func (b *PgBouncerSpecApplyConfiguration) WithPgHBA(values ...string) *PgBouncerSpecApplyConfiguration {
	for i := range values {
		b.PgHBA = append(b.PgHBA, values[i])
	}
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *PgBouncerSpecApplyConfiguration) WithPaused(value bool) *PgBouncerSpecApplyConfiguration {
	b.Paused = &value
	return b
}
