// Code generated by controller-gen. DO NOT EDIT.

package v1

// PgBouncerSecretsApplyConfiguration represents a declarative configuration of the PgBouncerSecrets type for use
// with apply.
//
// PgBouncerSecrets contains the versions of the secrets used
// by pgbouncer
type PgBouncerSecretsApplyConfiguration struct {
	// The auth query secret version
	AuthQuery *SecretVersionApplyConfiguration `json:"authQuery,omitempty"`
}

// PgBouncerSecretsApplyConfiguration constructs a declarative configuration of the PgBouncerSecrets type for use with
// apply.
func PgBouncerSecrets() *PgBouncerSecretsApplyConfiguration {
	return &PgBouncerSecretsApplyConfiguration{}
}

// WithAuthQuery sets the AuthQuery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthQuery field is set to the value of the last call.
func (b *PgBouncerSecretsApplyConfiguration) WithAuthQuery(value *SecretVersionApplyConfiguration) *PgBouncerSecretsApplyConfiguration {
	b.AuthQuery = value
	return b
}
