// Code generated by controller-gen. DO NOT EDIT.

package v1

// PluginConfigurationApplyConfiguration represents a declarative configuration of the PluginConfiguration type for use
// with apply.
//
// PluginConfiguration specifies a plugin that need to be loaded for this
// cluster to be reconciled
type PluginConfigurationApplyConfiguration struct {
	// Name is the plugin name
	Name *string `json:"name,omitempty"`
	// Enabled is true if this plugin will be used
	Enabled *bool `json:"enabled,omitempty"`
	// Marks the plugin as the WAL archiver. At most one plugin can be
	// designated as a WAL archiver. This cannot be enabled if the
	// `.spec.backup.barmanObjectStore` configuration is present.
	IsWALArchiver *bool `json:"isWALArchiver,omitempty"`
	// Parameters is the configuration of the plugin
	Parameters map[string]string `json:"parameters,omitempty"`
}

// PluginConfigurationApplyConfiguration constructs a declarative configuration of the PluginConfiguration type for use with
// apply.
func PluginConfiguration() *PluginConfigurationApplyConfiguration {
	return &PluginConfigurationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PluginConfigurationApplyConfiguration) WithName(value string) *PluginConfigurationApplyConfiguration {
	b.Name = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *PluginConfigurationApplyConfiguration) WithEnabled(value bool) *PluginConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithIsWALArchiver sets the IsWALArchiver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsWALArchiver field is set to the value of the last call.
func (b *PluginConfigurationApplyConfiguration) WithIsWALArchiver(value bool) *PluginConfigurationApplyConfiguration {
	b.IsWALArchiver = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *PluginConfigurationApplyConfiguration) WithParameters(entries map[string]string) *PluginConfigurationApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}
