// Code generated by controller-gen. DO NOT EDIT.

package v1

// PluginStatusApplyConfiguration represents a declarative configuration of the PluginStatus type for use
// with apply.
//
// PluginStatus is the status of a loaded plugin
type PluginStatusApplyConfiguration struct {
	// Name is the name of the plugin
	Name *string `json:"name,omitempty"`
	// Version is the version of the plugin loaded by the
	// latest reconciliation loop
	Version *string `json:"version,omitempty"`
	// Capabilities are the list of capabilities of the
	// plugin
	Capabilities []string `json:"capabilities,omitempty"`
	// OperatorCapabilities are the list of capabilities of the
	// plugin regarding the reconciler
	OperatorCapabilities []string `json:"operatorCapabilities,omitempty"`
	// WALCapabilities are the list of capabilities of the
	// plugin regarding the WAL management
	WALCapabilities []string `json:"walCapabilities,omitempty"`
	// BackupCapabilities are the list of capabilities of the
	// plugin regarding the Backup management
	BackupCapabilities []string `json:"backupCapabilities,omitempty"`
	// RestoreJobHookCapabilities are the list of capabilities of the
	// plugin regarding the RestoreJobHook management
	RestoreJobHookCapabilities []string `json:"restoreJobHookCapabilities,omitempty"`
	// Status contain the status reported by the plugin through the SetStatusInCluster interface
	Status *string `json:"status,omitempty"`
}

// PluginStatusApplyConfiguration constructs a declarative configuration of the PluginStatus type for use with
// apply.
func PluginStatus() *PluginStatusApplyConfiguration {
	return &PluginStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PluginStatusApplyConfiguration) WithName(value string) *PluginStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *PluginStatusApplyConfiguration) WithVersion(value string) *PluginStatusApplyConfiguration {
	b.Version = &value
	return b
}

// WithCapabilities adds the given value to the Capabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Capabilities field.
func (b *PluginStatusApplyConfiguration) WithCapabilities(values ...string) *PluginStatusApplyConfiguration {
	for i := range values {
		b.Capabilities = append(b.Capabilities, values[i])
	}
	return b
}

// WithOperatorCapabilities adds the given value to the OperatorCapabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OperatorCapabilities field.
func (b *PluginStatusApplyConfiguration) WithOperatorCapabilities(values ...string) *PluginStatusApplyConfiguration {
	for i := range values {
		b.OperatorCapabilities = append(b.OperatorCapabilities, values[i])
	}
	return b
}

// WithWALCapabilities adds the given value to the WALCapabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WALCapabilities field.
func (b *PluginStatusApplyConfiguration) WithWALCapabilities(values ...string) *PluginStatusApplyConfiguration {
	for i := range values {
		b.WALCapabilities = append(b.WALCapabilities, values[i])
	}
	return b
}

// WithBackupCapabilities adds the given value to the BackupCapabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BackupCapabilities field.
func (b *PluginStatusApplyConfiguration) WithBackupCapabilities(values ...string) *PluginStatusApplyConfiguration {
	for i := range values {
		b.BackupCapabilities = append(b.BackupCapabilities, values[i])
	}
	return b
}

// WithRestoreJobHookCapabilities adds the given value to the RestoreJobHookCapabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RestoreJobHookCapabilities field.
func (b *PluginStatusApplyConfiguration) WithRestoreJobHookCapabilities(values ...string) *PluginStatusApplyConfiguration {
	for i := range values {
		b.RestoreJobHookCapabilities = append(b.RestoreJobHookCapabilities, values[i])
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *PluginStatusApplyConfiguration) WithStatus(value string) *PluginStatusApplyConfiguration {
	b.Status = &value
	return b
}
