// Code generated by controller-gen. DO NOT EDIT.

package v1

// PoolerIntegrationsApplyConfiguration represents a declarative configuration of the PoolerIntegrations type for use
// with apply.
//
// PoolerIntegrations encapsulates the needed integration for the poolers referencing the cluster
type PoolerIntegrationsApplyConfiguration struct {
	PgBouncerIntegration *PgBouncerIntegrationStatusApplyConfiguration `json:"pgBouncerIntegration,omitempty"`
}

// PoolerIntegrationsApplyConfiguration constructs a declarative configuration of the PoolerIntegrations type for use with
// apply.
func PoolerIntegrations() *PoolerIntegrationsApplyConfiguration {
	return &PoolerIntegrationsApplyConfiguration{}
}

// WithPgBouncerIntegration sets the PgBouncerIntegration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBouncerIntegration field is set to the value of the last call.
func (b *PoolerIntegrationsApplyConfiguration) WithPgBouncerIntegration(value *PgBouncerIntegrationStatusApplyConfiguration) *PoolerIntegrationsApplyConfiguration {
	b.PgBouncerIntegration = value
	return b
}
