// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// PoolerSpecApplyConfiguration represents a declarative configuration of the PoolerSpec type for use
// with apply.
//
// PoolerSpec defines the desired state of Pooler
type PoolerSpecApplyConfiguration struct {
	// This is the cluster reference on which the Pooler will work.
	// Pooler name should never match with any cluster name within the same namespace.
	Cluster *corev1.LocalObjectReferenceApplyConfiguration `json:"cluster,omitempty"`
	// Type of service to forward traffic to. Default: `rw`.
	Type *apiv1.PoolerType `json:"type,omitempty"`
	// The number of replicas we want. Default: 1.
	Instances *int32 `json:"instances,omitempty"`
	// The template of the Pod to be created
	Template *PodTemplateSpecApplyConfiguration `json:"template,omitempty"`
	// The PgBouncer configuration
	PgBouncer *PgBouncerSpecApplyConfiguration `json:"pgbouncer,omitempty"`
	// The deployment strategy to use for pgbouncer to replace existing pods with new ones
	DeploymentStrategy *appsv1.DeploymentStrategy `json:"deploymentStrategy,omitempty"`
	// The configuration of the monitoring infrastructure of this pooler.
	//
	// Deprecated: This feature will be removed in an upcoming release. If
	// you need this functionality, you can create a PodMonitor manually.
	Monitoring *PoolerMonitoringConfigurationApplyConfiguration `json:"monitoring,omitempty"`
	// Template for the Service to be created
	ServiceTemplate *ServiceTemplateSpecApplyConfiguration `json:"serviceTemplate,omitempty"`
}

// PoolerSpecApplyConfiguration constructs a declarative configuration of the PoolerSpec type for use with
// apply.
func PoolerSpec() *PoolerSpecApplyConfiguration {
	return &PoolerSpecApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithCluster(value *corev1.LocalObjectReferenceApplyConfiguration) *PoolerSpecApplyConfiguration {
	b.Cluster = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithType(value apiv1.PoolerType) *PoolerSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithInstances(value int32) *PoolerSpecApplyConfiguration {
	b.Instances = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithTemplate(value *PodTemplateSpecApplyConfiguration) *PoolerSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithPgBouncer sets the PgBouncer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBouncer field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithPgBouncer(value *PgBouncerSpecApplyConfiguration) *PoolerSpecApplyConfiguration {
	b.PgBouncer = value
	return b
}

// WithDeploymentStrategy sets the DeploymentStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentStrategy field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithDeploymentStrategy(value appsv1.DeploymentStrategy) *PoolerSpecApplyConfiguration {
	b.DeploymentStrategy = &value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithMonitoring(value *PoolerMonitoringConfigurationApplyConfiguration) *PoolerSpecApplyConfiguration {
	b.Monitoring = value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *PoolerSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateSpecApplyConfiguration) *PoolerSpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}
