// Code generated by controller-gen. DO NOT EDIT.

package v1

// PoolerStatusApplyConfiguration represents a declarative configuration of the PoolerStatus type for use
// with apply.
//
// PoolerStatus defines the observed state of Pooler
type PoolerStatusApplyConfiguration struct {
	// The resource version of the config object
	Secrets *PoolerSecretsApplyConfiguration `json:"secrets,omitempty"`
	// The number of pods trying to be scheduled
	Instances *int32 `json:"instances,omitempty"`
}

// PoolerStatusApplyConfiguration constructs a declarative configuration of the PoolerStatus type for use with
// apply.
func PoolerStatus() *PoolerStatusApplyConfiguration {
	return &PoolerStatusApplyConfiguration{}
}

// WithSecrets sets the Secrets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secrets field is set to the value of the last call.
func (b *PoolerStatusApplyConfiguration) WithSecrets(value *PoolerSecretsApplyConfiguration) *PoolerStatusApplyConfiguration {
	b.Secrets = value
	return b
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *PoolerStatusApplyConfiguration) WithInstances(value int32) *PoolerStatusApplyConfiguration {
	b.Instances = &value
	return b
}
