// Code generated by controller-gen. DO NOT EDIT.

package v1

// PoolerSecretsApplyConfiguration represents a declarative configuration of the PoolerSecrets type for use
// with apply.
//
// PoolerSecrets contains the versions of all the secrets used
type PoolerSecretsApplyConfiguration struct {
	// The client TLS secret version
	ClientTLS *SecretVersionApplyConfiguration `json:"clientTLS,omitempty"`
	// The server TLS secret version
	ServerTLS *SecretVersionApplyConfiguration `json:"serverTLS,omitempty"`
	// The server CA secret version
	ServerCA *SecretVersionApplyConfiguration `json:"serverCA,omitempty"`
	// The client CA secret version
	ClientCA *SecretVersionApplyConfiguration `json:"clientCA,omitempty"`
	// The version of the secrets used by PgBouncer
	PgBouncerSecrets *PgBouncerSecretsApplyConfiguration `json:"pgBouncerSecrets,omitempty"`
}

// PoolerSecretsApplyConfiguration constructs a declarative configuration of the PoolerSecrets type for use with
// apply.
func PoolerSecrets() *PoolerSecretsApplyConfiguration {
	return &PoolerSecretsApplyConfiguration{}
}

// WithClientTLS sets the ClientTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientTLS field is set to the value of the last call.
func (b *PoolerSecretsApplyConfiguration) WithClientTLS(value *SecretVersionApplyConfiguration) *PoolerSecretsApplyConfiguration {
	b.ClientTLS = value
	return b
}

// WithServerTLS sets the ServerTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerTLS field is set to the value of the last call.
func (b *PoolerSecretsApplyConfiguration) WithServerTLS(value *SecretVersionApplyConfiguration) *PoolerSecretsApplyConfiguration {
	b.ServerTLS = value
	return b
}

// WithServerCA sets the ServerCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerCA field is set to the value of the last call.
func (b *PoolerSecretsApplyConfiguration) WithServerCA(value *SecretVersionApplyConfiguration) *PoolerSecretsApplyConfiguration {
	b.ServerCA = value
	return b
}

// WithClientCA sets the ClientCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCA field is set to the value of the last call.
func (b *PoolerSecretsApplyConfiguration) WithClientCA(value *SecretVersionApplyConfiguration) *PoolerSecretsApplyConfiguration {
	b.ClientCA = value
	return b
}

// WithPgBouncerSecrets sets the PgBouncerSecrets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBouncerSecrets field is set to the value of the last call.
func (b *PoolerSecretsApplyConfiguration) WithPgBouncerSecrets(value *PgBouncerSecretsApplyConfiguration) *PoolerSecretsApplyConfiguration {
	b.PgBouncerSecrets = value
	return b
}
