// Code generated by controller-gen. DO NOT EDIT.

package v1

// ProbesConfigurationApplyConfiguration represents a declarative configuration of the ProbesConfiguration type for use
// with apply.
//
// ProbesConfiguration represent the configuration for the probes
// to be injected in the PostgreSQL Pods
type ProbesConfigurationApplyConfiguration struct {
	// The startup probe configuration
	Startup *ProbeWithStrategyApplyConfiguration `json:"startup,omitempty"`
	// The liveness probe configuration
	Liveness *LivenessProbeApplyConfiguration `json:"liveness,omitempty"`
	// The readiness probe configuration
	Readiness *ProbeWithStrategyApplyConfiguration `json:"readiness,omitempty"`
}

// ProbesConfigurationApplyConfiguration constructs a declarative configuration of the ProbesConfiguration type for use with
// apply.
func ProbesConfiguration() *ProbesConfigurationApplyConfiguration {
	return &ProbesConfigurationApplyConfiguration{}
}

// WithStartup sets the Startup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Startup field is set to the value of the last call.
func (b *ProbesConfigurationApplyConfiguration) WithStartup(value *ProbeWithStrategyApplyConfiguration) *ProbesConfigurationApplyConfiguration {
	b.Startup = value
	return b
}

// WithLiveness sets the Liveness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Liveness field is set to the value of the last call.
func (b *ProbesConfigurationApplyConfiguration) WithLiveness(value *LivenessProbeApplyConfiguration) *ProbesConfigurationApplyConfiguration {
	b.Liveness = value
	return b
}

// WithReadiness sets the Readiness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Readiness field is set to the value of the last call.
func (b *ProbesConfigurationApplyConfiguration) WithReadiness(value *ProbeWithStrategyApplyConfiguration) *ProbesConfigurationApplyConfiguration {
	b.Readiness = value
	return b
}
