// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ProbeWithStrategyApplyConfiguration represents a declarative configuration of the ProbeWithStrategy type for use
// with apply.
//
// ProbeWithStrategy is the configuration of the startup probe
type ProbeWithStrategyApplyConfiguration struct {
	// Probe is the standard probe configuration
	ProbeApplyConfiguration `json:",inline"`
	// The probe strategy
	Type *apiv1.ProbeStrategyType `json:"type,omitempty"`
	// Lag limit. Used only for `streaming` strategy
	MaximumLag *resource.Quantity `json:"maximumLag,omitempty"`
}

// ProbeWithStrategyApplyConfiguration constructs a declarative configuration of the ProbeWithStrategy type for use with
// apply.
func ProbeWithStrategy() *ProbeWithStrategyApplyConfiguration {
	return &ProbeWithStrategyApplyConfiguration{}
}

// WithInitialDelaySeconds sets the InitialDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialDelaySeconds field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithInitialDelaySeconds(value int32) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.InitialDelaySeconds = &value
	return b
}

// WithTimeoutSeconds sets the TimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutSeconds field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithTimeoutSeconds(value int32) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.TimeoutSeconds = &value
	return b
}

// WithPeriodSeconds sets the PeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeriodSeconds field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithPeriodSeconds(value int32) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.PeriodSeconds = &value
	return b
}

// WithSuccessThreshold sets the SuccessThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessThreshold field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithSuccessThreshold(value int32) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.SuccessThreshold = &value
	return b
}

// WithFailureThreshold sets the FailureThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureThreshold field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithFailureThreshold(value int32) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.FailureThreshold = &value
	return b
}

// WithTerminationGracePeriodSeconds sets the TerminationGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationGracePeriodSeconds field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithTerminationGracePeriodSeconds(value int64) *ProbeWithStrategyApplyConfiguration {
	b.ProbeApplyConfiguration.TerminationGracePeriodSeconds = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithType(value apiv1.ProbeStrategyType) *ProbeWithStrategyApplyConfiguration {
	b.Type = &value
	return b
}

// WithMaximumLag sets the MaximumLag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaximumLag field is set to the value of the last call.
func (b *ProbeWithStrategyApplyConfiguration) WithMaximumLag(value resource.Quantity) *ProbeWithStrategyApplyConfiguration {
	b.MaximumLag = &value
	return b
}
