// Code generated by controller-gen. DO NOT EDIT.

package v1

// PublicationStatusApplyConfiguration represents a declarative configuration of the PublicationStatus type for use
// with apply.
//
// PublicationStatus defines the observed state of Publication
type PublicationStatusApplyConfiguration struct {
	// A sequence number representing the latest
	// desired state that was synchronized
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Applied is true if the publication was reconciled correctly
	Applied *bool `json:"applied,omitempty"`
	// Message is the reconciliation output message
	Message *string `json:"message,omitempty"`
}

// PublicationStatusApplyConfiguration constructs a declarative configuration of the PublicationStatus type for use with
// apply.
func PublicationStatus() *PublicationStatusApplyConfiguration {
	return &PublicationStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PublicationStatusApplyConfiguration) WithObservedGeneration(value int64) *PublicationStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithApplied sets the Applied field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Applied field is set to the value of the last call.
func (b *PublicationStatusApplyConfiguration) WithApplied(value bool) *PublicationStatusApplyConfiguration {
	b.Applied = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PublicationStatusApplyConfiguration) WithMessage(value string) *PublicationStatusApplyConfiguration {
	b.Message = &value
	return b
}
