// Code generated by controller-gen. DO NOT EDIT.

package v1

// PublicationTargetTableApplyConfiguration represents a declarative configuration of the PublicationTargetTable type for use
// with apply.
//
// PublicationTargetTable is a table to publish
type PublicationTargetTableApplyConfiguration struct {
	// Whether to limit to the table only or include all its descendants
	Only *bool `json:"only,omitempty"`
	// The table name
	Name *string `json:"name,omitempty"`
	// The schema name
	Schema *string `json:"schema,omitempty"`
	// The columns to publish
	Columns []string `json:"columns,omitempty"`
}

// PublicationTargetTableApplyConfiguration constructs a declarative configuration of the PublicationTargetTable type for use with
// apply.
func PublicationTargetTable() *PublicationTargetTableApplyConfiguration {
	return &PublicationTargetTableApplyConfiguration{}
}

// WithOnly sets the Only field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Only field is set to the value of the last call.
func (b *PublicationTargetTableApplyConfiguration) WithOnly(value bool) *PublicationTargetTableApplyConfiguration {
	b.Only = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PublicationTargetTableApplyConfiguration) WithName(value string) *PublicationTargetTableApplyConfiguration {
	b.Name = &value
	return b
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *PublicationTargetTableApplyConfiguration) WithSchema(value string) *PublicationTargetTableApplyConfiguration {
	b.Schema = &value
	return b
}

// WithColumns adds the given value to the Columns field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Columns field.
func (b *PublicationTargetTableApplyConfiguration) WithColumns(values ...string) *PublicationTargetTableApplyConfiguration {
	for i := range values {
		b.Columns = append(b.Columns, values[i])
	}
	return b
}
