// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/api/core/v1"
)

// PublicationSpecApplyConfiguration represents a declarative configuration of the PublicationSpec type for use
// with apply.
//
// PublicationSpec defines the desired state of Publication
type PublicationSpecApplyConfiguration struct {
	// The name of the PostgreSQL cluster that identifies the "publisher"
	ClusterRef *corev1.LocalObjectReference `json:"cluster,omitempty"`
	// The name of the publication inside PostgreSQL
	Name *string `json:"name,omitempty"`
	// The name of the database where the publication will be installed in
	// the "publisher" cluster
	DBName *string `json:"dbname,omitempty"`
	// Publication parameters part of the `WITH` clause as expected by
	// PostgreSQL `CREATE PUBLICATION` command
	Parameters map[string]string `json:"parameters,omitempty"`
	// Target of the publication as expected by PostgreSQL `CREATE PUBLICATION` command
	Target *PublicationTargetApplyConfiguration `json:"target,omitempty"`
	// The policy for end-of-life maintenance of this publication
	ReclaimPolicy *apiv1.PublicationReclaimPolicy `json:"publicationReclaimPolicy,omitempty"`
}

// PublicationSpecApplyConfiguration constructs a declarative configuration of the PublicationSpec type for use with
// apply.
func PublicationSpec() *PublicationSpecApplyConfiguration {
	return &PublicationSpecApplyConfiguration{}
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *PublicationSpecApplyConfiguration) WithClusterRef(value corev1.LocalObjectReference) *PublicationSpecApplyConfiguration {
	b.ClusterRef = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PublicationSpecApplyConfiguration) WithName(value string) *PublicationSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDBName sets the DBName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DBName field is set to the value of the last call.
func (b *PublicationSpecApplyConfiguration) WithDBName(value string) *PublicationSpecApplyConfiguration {
	b.DBName = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *PublicationSpecApplyConfiguration) WithParameters(entries map[string]string) *PublicationSpecApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *PublicationSpecApplyConfiguration) WithTarget(value *PublicationTargetApplyConfiguration) *PublicationSpecApplyConfiguration {
	b.Target = value
	return b
}

// WithReclaimPolicy sets the ReclaimPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReclaimPolicy field is set to the value of the last call.
func (b *PublicationSpecApplyConfiguration) WithReclaimPolicy(value apiv1.PublicationReclaimPolicy) *PublicationSpecApplyConfiguration {
	b.ReclaimPolicy = &value
	return b
}
