// Code generated by controller-gen. DO NOT EDIT.

package v1

// RecoveryTargetApplyConfiguration represents a declarative configuration of the RecoveryTarget type for use
// with apply.
//
// RecoveryTarget allows to configure the moment where the recovery process
// will stop. All the target options except TargetTLI are mutually exclusive.
type RecoveryTargetApplyConfiguration struct {
	// The ID of the backup from which to start the recovery process.
	// If empty (default) the operator will automatically detect the backup
	// based on targetTime or targetLSN if specified. Otherwise use the
	// latest available backup in chronological order.
	BackupID *string `json:"backupID,omitempty"`
	// The target timeline ("latest" or a positive integer)
	TargetTLI *string `json:"targetTLI,omitempty"`
	// The target transaction ID
	TargetXID *string `json:"targetXID,omitempty"`
	// The target name (to be previously created
	// with `pg_create_restore_point`)
	TargetName *string `json:"targetName,omitempty"`
	// The target LSN (Log Sequence Number)
	TargetLSN *string `json:"targetLSN,omitempty"`
	// The target time as a timestamp in the RFC3339 standard
	TargetTime *string `json:"targetTime,omitempty"`
	// End recovery as soon as a consistent state is reached
	TargetImmediate *bool `json:"targetImmediate,omitempty"`
	// Set the target to be exclusive. If omitted, defaults to false, so that
	// in Postgres, `recovery_target_inclusive` will be true
	Exclusive *bool `json:"exclusive,omitempty"`
}

// RecoveryTargetApplyConfiguration constructs a declarative configuration of the RecoveryTarget type for use with
// apply.
func RecoveryTarget() *RecoveryTargetApplyConfiguration {
	return &RecoveryTargetApplyConfiguration{}
}

// WithBackupID sets the BackupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupID field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithBackupID(value string) *RecoveryTargetApplyConfiguration {
	b.BackupID = &value
	return b
}

// WithTargetTLI sets the TargetTLI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetTLI field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetTLI(value string) *RecoveryTargetApplyConfiguration {
	b.TargetTLI = &value
	return b
}

// WithTargetXID sets the TargetXID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetXID field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetXID(value string) *RecoveryTargetApplyConfiguration {
	b.TargetXID = &value
	return b
}

// WithTargetName sets the TargetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetName field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetName(value string) *RecoveryTargetApplyConfiguration {
	b.TargetName = &value
	return b
}

// WithTargetLSN sets the TargetLSN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetLSN field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetLSN(value string) *RecoveryTargetApplyConfiguration {
	b.TargetLSN = &value
	return b
}

// WithTargetTime sets the TargetTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetTime field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetTime(value string) *RecoveryTargetApplyConfiguration {
	b.TargetTime = &value
	return b
}

// WithTargetImmediate sets the TargetImmediate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetImmediate field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithTargetImmediate(value bool) *RecoveryTargetApplyConfiguration {
	b.TargetImmediate = &value
	return b
}

// WithExclusive sets the Exclusive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exclusive field is set to the value of the last call.
func (b *RecoveryTargetApplyConfiguration) WithExclusive(value bool) *RecoveryTargetApplyConfiguration {
	b.Exclusive = &value
	return b
}
