// Code generated by controller-gen. DO NOT EDIT.

package v1

// ReplicationSlotsConfigurationApplyConfiguration represents a declarative configuration of the ReplicationSlotsConfiguration type for use
// with apply.
//
// ReplicationSlotsConfiguration encapsulates the configuration
// of replication slots
type ReplicationSlotsConfigurationApplyConfiguration struct {
	// Replication slots for high availability configuration
	HighAvailability *ReplicationSlotsHAConfigurationApplyConfiguration `json:"highAvailability,omitempty"`
	// Standby will update the status of the local replication slots
	// every `updateInterval` seconds (default 30).
	UpdateInterval *int `json:"updateInterval,omitempty"`
	// Configures the synchronization of the user defined physical replication slots
	SynchronizeReplicas *SynchronizeReplicasConfigurationApplyConfiguration `json:"synchronizeReplicas,omitempty"`
}

// ReplicationSlotsConfigurationApplyConfiguration constructs a declarative configuration of the ReplicationSlotsConfiguration type for use with
// apply.
func ReplicationSlotsConfiguration() *ReplicationSlotsConfigurationApplyConfiguration {
	return &ReplicationSlotsConfigurationApplyConfiguration{}
}

// WithHighAvailability sets the HighAvailability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighAvailability field is set to the value of the last call.
func (b *ReplicationSlotsConfigurationApplyConfiguration) WithHighAvailability(value *ReplicationSlotsHAConfigurationApplyConfiguration) *ReplicationSlotsConfigurationApplyConfiguration {
	b.HighAvailability = value
	return b
}

// WithUpdateInterval sets the UpdateInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateInterval field is set to the value of the last call.
func (b *ReplicationSlotsConfigurationApplyConfiguration) WithUpdateInterval(value int) *ReplicationSlotsConfigurationApplyConfiguration {
	b.UpdateInterval = &value
	return b
}

// WithSynchronizeReplicas sets the SynchronizeReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SynchronizeReplicas field is set to the value of the last call.
func (b *ReplicationSlotsConfigurationApplyConfiguration) WithSynchronizeReplicas(value *SynchronizeReplicasConfigurationApplyConfiguration) *ReplicationSlotsConfigurationApplyConfiguration {
	b.SynchronizeReplicas = value
	return b
}
