// Code generated by controller-gen. DO NOT EDIT.

package v1

// ReplicationSlotsHAConfigurationApplyConfiguration represents a declarative configuration of the ReplicationSlotsHAConfiguration type for use
// with apply.
//
// ReplicationSlotsHAConfiguration encapsulates the configuration
// of the replication slots that are automatically managed by
// the operator to control the streaming replication connections
// with the standby instances for high availability (HA) purposes.
// Replication slots are a PostgreSQL feature that makes sure
// that PostgreSQL automatically keeps WAL files in the primary
// when a streaming client (in this specific case a replica that
// is part of the HA cluster) gets disconnected.
type ReplicationSlotsHAConfigurationApplyConfiguration struct {
	// If enabled (default), the operator will automatically manage replication slots
	// on the primary instance and use them in streaming replication
	// connections with all the standby instances that are part of the HA
	// cluster. If disabled, the operator will not take advantage
	// of replication slots in streaming connections with the replicas.
	// This feature also controls replication slots in replica cluster,
	// from the designated primary to its cascading replicas.
	Enabled *bool `json:"enabled,omitempty"`
	// Prefix for replication slots managed by the operator for HA.
	// It may only contain lower case letters, numbers, and the underscore character.
	// This can only be set at creation time. By default set to `_cnpg_`.
	SlotPrefix *string `json:"slotPrefix,omitempty"`
	// When enabled, the operator automatically manages synchronization of logical
	// decoding (replication) slots across high-availability clusters.
	//
	// Requires one of the following conditions:
	// - PostgreSQL version 17 or later
	// - PostgreSQL version < 17 with pg_failover_slots extension enabled
	SynchronizeLogicalDecoding *bool `json:"synchronizeLogicalDecoding,omitempty"`
}

// ReplicationSlotsHAConfigurationApplyConfiguration constructs a declarative configuration of the ReplicationSlotsHAConfiguration type for use with
// apply.
func ReplicationSlotsHAConfiguration() *ReplicationSlotsHAConfigurationApplyConfiguration {
	return &ReplicationSlotsHAConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ReplicationSlotsHAConfigurationApplyConfiguration) WithEnabled(value bool) *ReplicationSlotsHAConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithSlotPrefix sets the SlotPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SlotPrefix field is set to the value of the last call.
func (b *ReplicationSlotsHAConfigurationApplyConfiguration) WithSlotPrefix(value string) *ReplicationSlotsHAConfigurationApplyConfiguration {
	b.SlotPrefix = &value
	return b
}

// WithSynchronizeLogicalDecoding sets the SynchronizeLogicalDecoding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SynchronizeLogicalDecoding field is set to the value of the last call.
func (b *ReplicationSlotsHAConfigurationApplyConfiguration) WithSynchronizeLogicalDecoding(value bool) *ReplicationSlotsHAConfigurationApplyConfiguration {
	b.SynchronizeLogicalDecoding = &value
	return b
}
