// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicaClusterConfigurationApplyConfiguration represents a declarative configuration of the ReplicaClusterConfiguration type for use
// with apply.
//
// ReplicaClusterConfiguration encapsulates the configuration of a replica
// cluster
type ReplicaClusterConfigurationApplyConfiguration struct {
	// Self defines the name of this cluster. It is used to determine if this is a primary
	// or a replica cluster, comparing it with `primary`
	Self *string `json:"self,omitempty"`
	// Primary defines which Cluster is defined to be the primary in the distributed PostgreSQL cluster, based on the
	// topology specified in externalClusters
	Primary *string `json:"primary,omitempty"`
	// The name of the external cluster which is the replication origin
	Source *string `json:"source,omitempty"`
	// If replica mode is enabled, this cluster will be a replica of an
	// existing cluster. Replica cluster can be created from a recovery
	// object store or via streaming through pg_basebackup.
	// Refer to the Replica clusters page of the documentation for more information.
	Enabled *bool `json:"enabled,omitempty"`
	// A demotion token generated by an external cluster used to
	// check if the promotion requirements are met.
	PromotionToken *string `json:"promotionToken,omitempty"`
	// When replica mode is enabled, this parameter allows you to replay
	// transactions only when the system time is at least the configured
	// time past the commit time. This provides an opportunity to correct
	// data loss errors. Note that when this parameter is set, a promotion
	// token cannot be used.
	MinApplyDelay *metav1.Duration `json:"minApplyDelay,omitempty"`
}

// ReplicaClusterConfigurationApplyConfiguration constructs a declarative configuration of the ReplicaClusterConfiguration type for use with
// apply.
func ReplicaClusterConfiguration() *ReplicaClusterConfigurationApplyConfiguration {
	return &ReplicaClusterConfigurationApplyConfiguration{}
}

// WithSelf sets the Self field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Self field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithSelf(value string) *ReplicaClusterConfigurationApplyConfiguration {
	b.Self = &value
	return b
}

// WithPrimary sets the Primary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Primary field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithPrimary(value string) *ReplicaClusterConfigurationApplyConfiguration {
	b.Primary = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithSource(value string) *ReplicaClusterConfigurationApplyConfiguration {
	b.Source = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithEnabled(value bool) *ReplicaClusterConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithPromotionToken sets the PromotionToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionToken field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithPromotionToken(value string) *ReplicaClusterConfigurationApplyConfiguration {
	b.PromotionToken = &value
	return b
}

// WithMinApplyDelay sets the MinApplyDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinApplyDelay field is set to the value of the last call.
func (b *ReplicaClusterConfigurationApplyConfiguration) WithMinApplyDelay(value metav1.Duration) *ReplicaClusterConfigurationApplyConfiguration {
	b.MinApplyDelay = &value
	return b
}
