// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// RoleConfigurationApplyConfiguration represents a declarative configuration of the RoleConfiguration type for use
// with apply.
//
// RoleConfiguration is the representation, in Kubernetes, of a PostgreSQL role
// with the additional field Ensure specifying whether to ensure the presence or
// absence of the role in the database
//
// The defaults of the CREATE ROLE command are applied
// Reference: https://www.postgresql.org/docs/current/sql-createrole.html
type RoleConfigurationApplyConfiguration struct {
	// Name of the role
	Name *string `json:"name,omitempty"`
	// Description of the role
	Comment *string `json:"comment,omitempty"`
	// Ensure the role is `present` or `absent` - defaults to "present"
	Ensure *apiv1.EnsureOption `json:"ensure,omitempty"`
	// Secret containing the password of the role (if present)
	// If null, the password will be ignored unless DisablePassword is set
	PasswordSecret *corev1.LocalObjectReferenceApplyConfiguration `json:"passwordSecret,omitempty"`
	// If the role can log in, this specifies how many concurrent
	// connections the role can make. `-1` (the default) means no limit.
	ConnectionLimit *int64 `json:"connectionLimit,omitempty"`
	// Date and time after which the role's password is no longer valid.
	// When omitted, the password will never expire (default).
	ValidUntil *metav1.Time `json:"validUntil,omitempty"`
	// List of one or more existing roles to which this role will be
	// immediately added as a new member. Default empty.
	InRoles []string `json:"inRoles,omitempty"`
	// Whether a role "inherits" the privileges of roles it is a member of.
	// Defaults is `true`.
	Inherit *bool `json:"inherit,omitempty"`
	// DisablePassword indicates that a role's password should be set to NULL in Postgres
	DisablePassword *bool `json:"disablePassword,omitempty"`
	// Whether the role is a `superuser` who can override all access
	// restrictions within the database - superuser status is dangerous and
	// should be used only when really needed. You must yourself be a
	// superuser to create a new superuser. Defaults is `false`.
	Superuser *bool `json:"superuser,omitempty"`
	// When set to `true`, the role being defined will be allowed to create
	// new databases. Specifying `false` (default) will deny a role the
	// ability to create databases.
	CreateDB *bool `json:"createdb,omitempty"`
	// Whether the role will be permitted to create, alter, drop, comment
	// on, change the security label for, and grant or revoke membership in
	// other roles. Default is `false`.
	CreateRole *bool `json:"createrole,omitempty"`
	// Whether the role is allowed to log in. A role having the `login`
	// attribute can be thought of as a user. Roles without this attribute
	// are useful for managing database privileges, but are not users in
	// the usual sense of the word. Default is `false`.
	Login *bool `json:"login,omitempty"`
	// Whether a role is a replication role. A role must have this
	// attribute (or be a superuser) in order to be able to connect to the
	// server in replication mode (physical or logical replication) and in
	// order to be able to create or drop replication slots. A role having
	// the `replication` attribute is a very highly privileged role, and
	// should only be used on roles actually used for replication. Default
	// is `false`.
	Replication *bool `json:"replication,omitempty"`
	// Whether a role bypasses every row-level security (RLS) policy.
	// Default is `false`.
	BypassRLS *bool `json:"bypassrls,omitempty"`
}

// RoleConfigurationApplyConfiguration constructs a declarative configuration of the RoleConfiguration type for use with
// apply.
func RoleConfiguration() *RoleConfigurationApplyConfiguration {
	return &RoleConfigurationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithName(value string) *RoleConfigurationApplyConfiguration {
	b.Name = &value
	return b
}

// WithComment sets the Comment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Comment field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithComment(value string) *RoleConfigurationApplyConfiguration {
	b.Comment = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *RoleConfigurationApplyConfiguration {
	b.Ensure = &value
	return b
}

// WithPasswordSecret sets the PasswordSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordSecret field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithPasswordSecret(value *corev1.LocalObjectReferenceApplyConfiguration) *RoleConfigurationApplyConfiguration {
	b.PasswordSecret = value
	return b
}

// WithConnectionLimit sets the ConnectionLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionLimit field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithConnectionLimit(value int64) *RoleConfigurationApplyConfiguration {
	b.ConnectionLimit = &value
	return b
}

// WithValidUntil sets the ValidUntil field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValidUntil field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithValidUntil(value metav1.Time) *RoleConfigurationApplyConfiguration {
	b.ValidUntil = &value
	return b
}

// WithInRoles adds the given value to the InRoles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InRoles field.
func (b *RoleConfigurationApplyConfiguration) WithInRoles(values ...string) *RoleConfigurationApplyConfiguration {
	for i := range values {
		b.InRoles = append(b.InRoles, values[i])
	}
	return b
}

// WithInherit sets the Inherit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inherit field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithInherit(value bool) *RoleConfigurationApplyConfiguration {
	b.Inherit = &value
	return b
}

// WithDisablePassword sets the DisablePassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisablePassword field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithDisablePassword(value bool) *RoleConfigurationApplyConfiguration {
	b.DisablePassword = &value
	return b
}

// WithSuperuser sets the Superuser field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Superuser field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithSuperuser(value bool) *RoleConfigurationApplyConfiguration {
	b.Superuser = &value
	return b
}

// WithCreateDB sets the CreateDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateDB field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithCreateDB(value bool) *RoleConfigurationApplyConfiguration {
	b.CreateDB = &value
	return b
}

// WithCreateRole sets the CreateRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateRole field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithCreateRole(value bool) *RoleConfigurationApplyConfiguration {
	b.CreateRole = &value
	return b
}

// WithLogin sets the Login field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Login field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithLogin(value bool) *RoleConfigurationApplyConfiguration {
	b.Login = &value
	return b
}

// WithReplication sets the Replication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replication field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithReplication(value bool) *RoleConfigurationApplyConfiguration {
	b.Replication = &value
	return b
}

// WithBypassRLS sets the BypassRLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BypassRLS field is set to the value of the last call.
func (b *RoleConfigurationApplyConfiguration) WithBypassRLS(value bool) *RoleConfigurationApplyConfiguration {
	b.BypassRLS = &value
	return b
}
