// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ScheduledBackupStatusApplyConfiguration represents a declarative configuration of the ScheduledBackupStatus type for use
// with apply.
//
// ScheduledBackupStatus defines the observed state of ScheduledBackup
type ScheduledBackupStatusApplyConfiguration struct {
	// The latest time the schedule
	LastCheckTime *metav1.Time `json:"lastCheckTime,omitempty"`
	// Information when was the last time that backup was successfully scheduled.
	LastScheduleTime *metav1.Time `json:"lastScheduleTime,omitempty"`
	// Next time we will run a backup
	NextScheduleTime *metav1.Time `json:"nextScheduleTime,omitempty"`
}

// ScheduledBackupStatusApplyConfiguration constructs a declarative configuration of the ScheduledBackupStatus type for use with
// apply.
func ScheduledBackupStatus() *ScheduledBackupStatusApplyConfiguration {
	return &ScheduledBackupStatusApplyConfiguration{}
}

// WithLastCheckTime sets the LastCheckTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastCheckTime field is set to the value of the last call.
func (b *ScheduledBackupStatusApplyConfiguration) WithLastCheckTime(value metav1.Time) *ScheduledBackupStatusApplyConfiguration {
	b.LastCheckTime = &value
	return b
}

// WithLastScheduleTime sets the LastScheduleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduleTime field is set to the value of the last call.
func (b *ScheduledBackupStatusApplyConfiguration) WithLastScheduleTime(value metav1.Time) *ScheduledBackupStatusApplyConfiguration {
	b.LastScheduleTime = &value
	return b
}

// WithNextScheduleTime sets the NextScheduleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextScheduleTime field is set to the value of the last call.
func (b *ScheduledBackupStatusApplyConfiguration) WithNextScheduleTime(value metav1.Time) *ScheduledBackupStatusApplyConfiguration {
	b.NextScheduleTime = &value
	return b
}
