// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// SchemaSpecApplyConfiguration represents a declarative configuration of the SchemaSpec type for use
// with apply.
//
// SchemaSpec configures a schema in a database
type SchemaSpecApplyConfiguration struct {
	// Common fields
	DatabaseObjectSpecApplyConfiguration `json:",inline"`
	// The role name of the user who owns the schema inside PostgreSQL.
	// It maps to the `AUTHORIZATION` parameter of `CREATE SCHEMA` and the
	// `OWNER TO` command of `ALTER SCHEMA`.
	Owner *string `json:"owner,omitempty"`
}

// SchemaSpecApplyConfiguration constructs a declarative configuration of the SchemaSpec type for use with
// apply.
func SchemaSpec() *SchemaSpecApplyConfiguration {
	return &SchemaSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SchemaSpecApplyConfiguration) WithName(value string) *SchemaSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Name = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *SchemaSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *SchemaSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Ensure = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *SchemaSpecApplyConfiguration) WithOwner(value string) *SchemaSpecApplyConfiguration {
	b.Owner = &value
	return b
}
