// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ScheduledBackupSpecApplyConfiguration represents a declarative configuration of the ScheduledBackupSpec type for use
// with apply.
//
// ScheduledBackupSpec defines the desired state of ScheduledBackup
type ScheduledBackupSpecApplyConfiguration struct {
	// If this backup is suspended or not
	Suspend *bool `json:"suspend,omitempty"`
	// If the first backup has to be immediately start after creation or not
	Immediate *bool `json:"immediate,omitempty"`
	// The schedule does not follow the same format used in Kubernetes CronJobs
	// as it includes an additional seconds specifier,
	// see https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
	Schedule *string `json:"schedule,omitempty"`
	// The cluster to backup
	Cluster *corev1.LocalObjectReferenceApplyConfiguration `json:"cluster,omitempty"`
	// Indicates which ownerReference should be put inside the created backup resources.<br />
	// - none: no owner reference for created backup objects (same behavior as before the field was introduced)<br />
	// - self: sets the Scheduled backup object as owner of the backup<br />
	// - cluster: set the cluster as owner of the backup<br />
	BackupOwnerReference *string `json:"backupOwnerReference,omitempty"`
	// The policy to decide which instance should perform this backup. If empty,
	// it defaults to `cluster.spec.backup.target`.
	// Available options are empty string, `primary` and `prefer-standby`.
	// `primary` to have backups run always on primary instances,
	// `prefer-standby` to have backups run preferably on the most updated
	// standby, if available.
	Target *apiv1.BackupTarget `json:"target,omitempty"`
	// The backup method to be used, possible options are `barmanObjectStore`, `pgBackRest`
	// `volumeSnapshot` or `plugin`. Defaults to: `pgBackRest`.
	Method *apiv1.BackupMethod `json:"method,omitempty"`
	// The pgBackRest backup type. Possible values are `full`, `diff` (differential),
	// or `incr` (incremental). Defaults to `full`. Only used when method is `pgBackRest`.
	PgBackRestBackupType *apiv1.PgBackRestBackupType `json:"pgBackRestBackupType,omitempty"`
	// Configuration parameters passed to the plugin managing this backup
	PluginConfiguration *BackupPluginConfigurationApplyConfiguration `json:"pluginConfiguration,omitempty"`
	// Whether the default type of backup with volume snapshots is
	// online/hot (`true`, default) or offline/cold (`false`)
	// Overrides the default setting specified in the cluster field '.spec.backup.volumeSnapshot.online'
	Online *bool `json:"online,omitempty"`
	// Configuration parameters to control the online/hot backup with volume snapshots
	// Overrides the default settings specified in the cluster '.backup.volumeSnapshot.onlineConfiguration' stanza
	OnlineConfiguration *OnlineConfigurationApplyConfiguration `json:"onlineConfiguration,omitempty"`
}

// ScheduledBackupSpecApplyConfiguration constructs a declarative configuration of the ScheduledBackupSpec type for use with
// apply.
func ScheduledBackupSpec() *ScheduledBackupSpecApplyConfiguration {
	return &ScheduledBackupSpecApplyConfiguration{}
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithSuspend(value bool) *ScheduledBackupSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithImmediate sets the Immediate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Immediate field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithImmediate(value bool) *ScheduledBackupSpecApplyConfiguration {
	b.Immediate = &value
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithSchedule(value string) *ScheduledBackupSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithCluster(value *corev1.LocalObjectReferenceApplyConfiguration) *ScheduledBackupSpecApplyConfiguration {
	b.Cluster = value
	return b
}

// WithBackupOwnerReference sets the BackupOwnerReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupOwnerReference field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithBackupOwnerReference(value string) *ScheduledBackupSpecApplyConfiguration {
	b.BackupOwnerReference = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithTarget(value apiv1.BackupTarget) *ScheduledBackupSpecApplyConfiguration {
	b.Target = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithMethod(value apiv1.BackupMethod) *ScheduledBackupSpecApplyConfiguration {
	b.Method = &value
	return b
}

// WithPgBackRestBackupType sets the PgBackRestBackupType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PgBackRestBackupType field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithPgBackRestBackupType(value apiv1.PgBackRestBackupType) *ScheduledBackupSpecApplyConfiguration {
	b.PgBackRestBackupType = &value
	return b
}

// WithPluginConfiguration sets the PluginConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PluginConfiguration field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithPluginConfiguration(value *BackupPluginConfigurationApplyConfiguration) *ScheduledBackupSpecApplyConfiguration {
	b.PluginConfiguration = value
	return b
}

// WithOnline sets the Online field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Online field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithOnline(value bool) *ScheduledBackupSpecApplyConfiguration {
	b.Online = &value
	return b
}

// WithOnlineConfiguration sets the OnlineConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnlineConfiguration field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithOnlineConfiguration(value *OnlineConfigurationApplyConfiguration) *ScheduledBackupSpecApplyConfiguration {
	b.OnlineConfiguration = value
	return b
}
