// Code generated by controller-gen. DO NOT EDIT.

package v1

// SecretsResourceVersionApplyConfiguration represents a declarative configuration of the SecretsResourceVersion type for use
// with apply.
//
// SecretsResourceVersion is the resource versions of the secrets
// managed by the operator
type SecretsResourceVersionApplyConfiguration struct {
	// The resource version of the "postgres" user secret
	SuperuserSecretVersion *string `json:"superuserSecretVersion,omitempty"`
	// The resource version of the "streaming_replica" user secret
	ReplicationSecretVersion *string `json:"replicationSecretVersion,omitempty"`
	// The resource version of the "app" user secret
	ApplicationSecretVersion *string `json:"applicationSecretVersion,omitempty"`
	// The resource versions of the managed roles secrets
	ManagedRoleSecretVersions map[string]string `json:"managedRoleSecretVersion,omitempty"`
	// Unused. Retained for compatibility with old versions.
	CASecretVersion *string `json:"caSecretVersion,omitempty"`
	// The resource version of the PostgreSQL client-side CA secret version
	ClientCASecretVersion *string `json:"clientCaSecretVersion,omitempty"`
	// The resource version of the PostgreSQL server-side CA secret version
	ServerCASecretVersion *string `json:"serverCaSecretVersion,omitempty"`
	// The resource version of the PostgreSQL server-side secret version
	ServerSecretVersion *string `json:"serverSecretVersion,omitempty"`
	// The resource version of the Barman Endpoint CA if provided
	BarmanEndpointCA *string `json:"barmanEndpointCA,omitempty"`
	// The resource versions of the external cluster secrets
	ExternalClusterSecretVersions map[string]string `json:"externalClusterSecretVersion,omitempty"`
	// A map with the versions of all the secrets used to pass metrics.
	// Map keys are the secret names, map values are the versions
	Metrics map[string]string `json:"metrics,omitempty"`
}

// SecretsResourceVersionApplyConfiguration constructs a declarative configuration of the SecretsResourceVersion type for use with
// apply.
func SecretsResourceVersion() *SecretsResourceVersionApplyConfiguration {
	return &SecretsResourceVersionApplyConfiguration{}
}

// WithSuperuserSecretVersion sets the SuperuserSecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuperuserSecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithSuperuserSecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.SuperuserSecretVersion = &value
	return b
}

// WithReplicationSecretVersion sets the ReplicationSecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicationSecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithReplicationSecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.ReplicationSecretVersion = &value
	return b
}

// WithApplicationSecretVersion sets the ApplicationSecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApplicationSecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithApplicationSecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.ApplicationSecretVersion = &value
	return b
}

// WithManagedRoleSecretVersions puts the entries into the ManagedRoleSecretVersions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ManagedRoleSecretVersions field,
// overwriting an existing map entries in ManagedRoleSecretVersions field with the same key.
func (b *SecretsResourceVersionApplyConfiguration) WithManagedRoleSecretVersions(entries map[string]string) *SecretsResourceVersionApplyConfiguration {
	if b.ManagedRoleSecretVersions == nil && len(entries) > 0 {
		b.ManagedRoleSecretVersions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ManagedRoleSecretVersions[k] = v
	}
	return b
}

// WithCASecretVersion sets the CASecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CASecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithCASecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.CASecretVersion = &value
	return b
}

// WithClientCASecretVersion sets the ClientCASecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCASecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithClientCASecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.ClientCASecretVersion = &value
	return b
}

// WithServerCASecretVersion sets the ServerCASecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerCASecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithServerCASecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.ServerCASecretVersion = &value
	return b
}

// WithServerSecretVersion sets the ServerSecretVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerSecretVersion field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithServerSecretVersion(value string) *SecretsResourceVersionApplyConfiguration {
	b.ServerSecretVersion = &value
	return b
}

// WithBarmanEndpointCA sets the BarmanEndpointCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BarmanEndpointCA field is set to the value of the last call.
func (b *SecretsResourceVersionApplyConfiguration) WithBarmanEndpointCA(value string) *SecretsResourceVersionApplyConfiguration {
	b.BarmanEndpointCA = &value
	return b
}

// WithExternalClusterSecretVersions puts the entries into the ExternalClusterSecretVersions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExternalClusterSecretVersions field,
// overwriting an existing map entries in ExternalClusterSecretVersions field with the same key.
func (b *SecretsResourceVersionApplyConfiguration) WithExternalClusterSecretVersions(entries map[string]string) *SecretsResourceVersionApplyConfiguration {
	if b.ExternalClusterSecretVersions == nil && len(entries) > 0 {
		b.ExternalClusterSecretVersions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExternalClusterSecretVersions[k] = v
	}
	return b
}

// WithMetrics puts the entries into the Metrics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Metrics field,
// overwriting an existing map entries in Metrics field with the same key.
func (b *SecretsResourceVersionApplyConfiguration) WithMetrics(entries map[string]string) *SecretsResourceVersionApplyConfiguration {
	if b.Metrics == nil && len(entries) > 0 {
		b.Metrics = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Metrics[k] = v
	}
	return b
}
