// Code generated by controller-gen. DO NOT EDIT.

package v1

// SecretVersionApplyConfiguration represents a declarative configuration of the SecretVersion type for use
// with apply.
//
// SecretVersion contains a secret name and its ResourceVersion
type SecretVersionApplyConfiguration struct {
	// The name of the secret
	Name *string `json:"name,omitempty"`
	// The ResourceVersion of the secret
	Version *string `json:"version,omitempty"`
}

// SecretVersionApplyConfiguration constructs a declarative configuration of the SecretVersion type for use with
// apply.
func SecretVersion() *SecretVersionApplyConfiguration {
	return &SecretVersionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecretVersionApplyConfiguration) WithName(value string) *SecretVersionApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *SecretVersionApplyConfiguration) WithVersion(value string) *SecretVersionApplyConfiguration {
	b.Version = &value
	return b
}
