// Code generated by controller-gen. DO NOT EDIT.

package v1

// ServiceAccountTemplateApplyConfiguration represents a declarative configuration of the ServiceAccountTemplate type for use
// with apply.
//
// ServiceAccountTemplate contains the template needed to generate the service accounts
type ServiceAccountTemplateApplyConfiguration struct {
	// Metadata are the metadata to be used for the generated
	// service account
	Metadata *MetadataApplyConfiguration `json:"metadata,omitempty"`
}

// ServiceAccountTemplateApplyConfiguration constructs a declarative configuration of the ServiceAccountTemplate type for use with
// apply.
func ServiceAccountTemplate() *ServiceAccountTemplateApplyConfiguration {
	return &ServiceAccountTemplateApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ServiceAccountTemplateApplyConfiguration) WithMetadata(value *MetadataApplyConfiguration) *ServiceAccountTemplateApplyConfiguration {
	b.Metadata = value
	return b
}
