// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// ServiceTemplateSpecApplyConfiguration represents a declarative configuration of the ServiceTemplateSpec type for use
// with apply.
//
// ServiceTemplateSpec is a structure allowing the user to set
// a template for Service generation.
type ServiceTemplateSpecApplyConfiguration struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	ObjectMeta *MetadataApplyConfiguration `json:"metadata,omitempty"`
	// Specification of the desired behavior of the service.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
	Spec *corev1.ServiceSpec `json:"spec,omitempty"`
}

// ServiceTemplateSpecApplyConfiguration constructs a declarative configuration of the ServiceTemplateSpec type for use with
// apply.
func ServiceTemplateSpec() *ServiceTemplateSpecApplyConfiguration {
	return &ServiceTemplateSpecApplyConfiguration{}
}

// WithObjectMeta sets the ObjectMeta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectMeta field is set to the value of the last call.
func (b *ServiceTemplateSpecApplyConfiguration) WithObjectMeta(value *MetadataApplyConfiguration) *ServiceTemplateSpecApplyConfiguration {
	b.ObjectMeta = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ServiceTemplateSpecApplyConfiguration) WithSpec(value corev1.ServiceSpec) *ServiceTemplateSpecApplyConfiguration {
	b.Spec = &value
	return b
}
