// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// ServerSpecApplyConfiguration represents a declarative configuration of the ServerSpec type for use
// with apply.
//
// ServerSpec configures a server of a foreign data wrapper
type ServerSpecApplyConfiguration struct {
	// Common fields
	DatabaseObjectSpecApplyConfiguration `json:",inline"`
	// The name of the Foreign Data Wrapper (FDW)
	FdwName *string `json:"fdw,omitempty"`
	// Options specifies the configuration options for the server
	// (key is the option name, value is the option value).
	Options []OptionSpecApplyConfiguration `json:"options,omitempty"`
	// List of roles for which `USAGE` privileges on the server are granted or revoked.
	Usages []UsageSpecApplyConfiguration `json:"usage,omitempty"`
}

// ServerSpecApplyConfiguration constructs a declarative configuration of the ServerSpec type for use with
// apply.
func ServerSpec() *ServerSpecApplyConfiguration {
	return &ServerSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithName(value string) *ServerSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Name = &value
	return b
}

// WithEnsure sets the Ensure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ensure field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithEnsure(value apiv1.EnsureOption) *ServerSpecApplyConfiguration {
	b.DatabaseObjectSpecApplyConfiguration.Ensure = &value
	return b
}

// WithFdwName sets the FdwName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FdwName field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithFdwName(value string) *ServerSpecApplyConfiguration {
	b.FdwName = &value
	return b
}

// WithOptions adds the given value to the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Options field.
func (b *ServerSpecApplyConfiguration) WithOptions(values ...*OptionSpecApplyConfiguration) *ServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOptions")
		}
		b.Options = append(b.Options, *values[i])
	}
	return b
}

// WithUsages adds the given value to the Usages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Usages field.
func (b *ServerSpecApplyConfiguration) WithUsages(values ...*UsageSpecApplyConfiguration) *ServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUsages")
		}
		b.Usages = append(b.Usages, *values[i])
	}
	return b
}
