// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/cloudnative-pg/machinery/pkg/api"
)

// SQLRefsApplyConfiguration represents a declarative configuration of the SQLRefs type for use
// with apply.
//
// SQLRefs holds references to ConfigMaps or Secrets
// containing SQL files. The references are processed in a specific order:
// first, all Secrets are processed, followed by all ConfigMaps.
// Within each group, the processing order follows the sequence specified
// in their respective arrays.
type SQLRefsApplyConfiguration struct {
	// SecretRefs holds a list of references to Secrets
	SecretRefs []api.SecretKeySelector `json:"secretRefs,omitempty"`
	// ConfigMapRefs holds a list of references to ConfigMaps
	ConfigMapRefs []api.ConfigMapKeySelector `json:"configMapRefs,omitempty"`
}

// SQLRefsApplyConfiguration constructs a declarative configuration of the SQLRefs type for use with
// apply.
func SQLRefs() *SQLRefsApplyConfiguration {
	return &SQLRefsApplyConfiguration{}
}

// WithSecretRefs adds the given value to the SecretRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecretRefs field.
func (b *SQLRefsApplyConfiguration) WithSecretRefs(values ...api.SecretKeySelector) *SQLRefsApplyConfiguration {
	for i := range values {
		b.SecretRefs = append(b.SecretRefs, values[i])
	}
	return b
}

// WithConfigMapRefs adds the given value to the ConfigMapRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ConfigMapRefs field.
func (b *SQLRefsApplyConfiguration) WithConfigMapRefs(values ...api.ConfigMapKeySelector) *SQLRefsApplyConfiguration {
	for i := range values {
		b.ConfigMapRefs = append(b.ConfigMapRefs, values[i])
	}
	return b
}
