// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// StorageConfigurationApplyConfiguration represents a declarative configuration of the StorageConfiguration type for use
// with apply.
//
// StorageConfiguration is the configuration used to create and reconcile PVCs,
// usable for WAL volumes, PGDATA volumes, or tablespaces
type StorageConfigurationApplyConfiguration struct {
	// StorageClass to use for PVCs. Applied after
	// evaluating the PVC template, if available.
	// If not specified, the generated PVCs will use the
	// default storage class
	StorageClass *string `json:"storageClass,omitempty"`
	// Size of the storage. Required if not already specified in the PVC template.
	// Changes to this field are automatically reapplied to the created PVCs.
	// Size cannot be decreased.
	Size *string `json:"size,omitempty"`
	// Resize existent PVCs, defaults to true
	ResizeInUseVolumes *bool `json:"resizeInUseVolumes,omitempty"`
	// Template to be used to generate the Persistent Volume Claim
	PersistentVolumeClaimTemplate *corev1.PersistentVolumeClaimSpec `json:"pvcTemplate,omitempty"`
	// MountPropagation allows configuring the mount propagation mode for the volume.
	// When set to "HostToContainer", mounts made on the host after the container
	// starts will be visible inside the container (e.g. for NVMe-oF external mounts).
	// If not set, Kubernetes defaults to "None".
	MountPropagation *corev1.MountPropagationMode `json:"mountPropagation,omitempty"`
}

// StorageConfigurationApplyConfiguration constructs a declarative configuration of the StorageConfiguration type for use with
// apply.
func StorageConfiguration() *StorageConfigurationApplyConfiguration {
	return &StorageConfigurationApplyConfiguration{}
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *StorageConfigurationApplyConfiguration) WithStorageClass(value string) *StorageConfigurationApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *StorageConfigurationApplyConfiguration) WithSize(value string) *StorageConfigurationApplyConfiguration {
	b.Size = &value
	return b
}

// WithResizeInUseVolumes sets the ResizeInUseVolumes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResizeInUseVolumes field is set to the value of the last call.
func (b *StorageConfigurationApplyConfiguration) WithResizeInUseVolumes(value bool) *StorageConfigurationApplyConfiguration {
	b.ResizeInUseVolumes = &value
	return b
}

// WithPersistentVolumeClaimTemplate sets the PersistentVolumeClaimTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentVolumeClaimTemplate field is set to the value of the last call.
func (b *StorageConfigurationApplyConfiguration) WithPersistentVolumeClaimTemplate(value corev1.PersistentVolumeClaimSpec) *StorageConfigurationApplyConfiguration {
	b.PersistentVolumeClaimTemplate = &value
	return b
}

// WithMountPropagation sets the MountPropagation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPropagation field is set to the value of the last call.
func (b *StorageConfigurationApplyConfiguration) WithMountPropagation(value corev1.MountPropagationMode) *StorageConfigurationApplyConfiguration {
	b.MountPropagation = &value
	return b
}
