// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
	corev1 "k8s.io/api/core/v1"
)

// SubscriptionSpecApplyConfiguration represents a declarative configuration of the SubscriptionSpec type for use
// with apply.
//
// SubscriptionSpec defines the desired state of Subscription
type SubscriptionSpecApplyConfiguration struct {
	// The name of the PostgreSQL cluster that identifies the "subscriber"
	ClusterRef *corev1.LocalObjectReference `json:"cluster,omitempty"`
	// The name of the subscription inside PostgreSQL
	Name *string `json:"name,omitempty"`
	// The name of the database where the publication will be installed in
	// the "subscriber" cluster
	DBName *string `json:"dbname,omitempty"`
	// Subscription parameters included in the `WITH` clause of the PostgreSQL
	// `CREATE SUBSCRIPTION` command. Most parameters cannot be changed
	// after the subscription is created and will be ignored if modified
	// later, except for a limited set documented at:
	// https://www.postgresql.org/docs/current/sql-altersubscription.html#SQL-ALTERSUBSCRIPTION-PARAMS-SET
	Parameters map[string]string `json:"parameters,omitempty"`
	// The name of the publication inside the PostgreSQL database in the
	// "publisher"
	PublicationName *string `json:"publicationName,omitempty"`
	// The name of the database containing the publication on the external
	// cluster. Defaults to the one in the external cluster definition.
	PublicationDBName *string `json:"publicationDBName,omitempty"`
	// The name of the external cluster with the publication ("publisher")
	ExternalClusterName *string `json:"externalClusterName,omitempty"`
	// The policy for end-of-life maintenance of this subscription
	ReclaimPolicy *apiv1.SubscriptionReclaimPolicy `json:"subscriptionReclaimPolicy,omitempty"`
}

// SubscriptionSpecApplyConfiguration constructs a declarative configuration of the SubscriptionSpec type for use with
// apply.
func SubscriptionSpec() *SubscriptionSpecApplyConfiguration {
	return &SubscriptionSpecApplyConfiguration{}
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithClusterRef(value corev1.LocalObjectReference) *SubscriptionSpecApplyConfiguration {
	b.ClusterRef = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithName(value string) *SubscriptionSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDBName sets the DBName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DBName field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithDBName(value string) *SubscriptionSpecApplyConfiguration {
	b.DBName = &value
	return b
}

// WithParameters puts the entries into the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Parameters field,
// overwriting an existing map entries in Parameters field with the same key.
func (b *SubscriptionSpecApplyConfiguration) WithParameters(entries map[string]string) *SubscriptionSpecApplyConfiguration {
	if b.Parameters == nil && len(entries) > 0 {
		b.Parameters = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Parameters[k] = v
	}
	return b
}

// WithPublicationName sets the PublicationName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicationName field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithPublicationName(value string) *SubscriptionSpecApplyConfiguration {
	b.PublicationName = &value
	return b
}

// WithPublicationDBName sets the PublicationDBName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicationDBName field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithPublicationDBName(value string) *SubscriptionSpecApplyConfiguration {
	b.PublicationDBName = &value
	return b
}

// WithExternalClusterName sets the ExternalClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalClusterName field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithExternalClusterName(value string) *SubscriptionSpecApplyConfiguration {
	b.ExternalClusterName = &value
	return b
}

// WithReclaimPolicy sets the ReclaimPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReclaimPolicy field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithReclaimPolicy(value apiv1.SubscriptionReclaimPolicy) *SubscriptionSpecApplyConfiguration {
	b.ReclaimPolicy = &value
	return b
}
