// Code generated by controller-gen. DO NOT EDIT.

package v1

// SyncReplicaElectionConstraintsApplyConfiguration represents a declarative configuration of the SyncReplicaElectionConstraints type for use
// with apply.
//
// SyncReplicaElectionConstraints contains the constraints for sync replicas election.
//
// For anti-affinity parameters two instances are considered in the same location
// if all the labels values match.
//
// In future synchronous replica election restriction by name will be supported.
type SyncReplicaElectionConstraintsApplyConfiguration struct {
	// A list of node labels values to extract and compare to evaluate if the pods reside in the same topology or not
	NodeLabelsAntiAffinity []string `json:"nodeLabelsAntiAffinity,omitempty"`
	// This flag enables the constraints for sync replicas
	Enabled *bool `json:"enabled,omitempty"`
}

// SyncReplicaElectionConstraintsApplyConfiguration constructs a declarative configuration of the SyncReplicaElectionConstraints type for use with
// apply.
func SyncReplicaElectionConstraints() *SyncReplicaElectionConstraintsApplyConfiguration {
	return &SyncReplicaElectionConstraintsApplyConfiguration{}
}

// WithNodeLabelsAntiAffinity adds the given value to the NodeLabelsAntiAffinity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeLabelsAntiAffinity field.
func (b *SyncReplicaElectionConstraintsApplyConfiguration) WithNodeLabelsAntiAffinity(values ...string) *SyncReplicaElectionConstraintsApplyConfiguration {
	for i := range values {
		b.NodeLabelsAntiAffinity = append(b.NodeLabelsAntiAffinity, values[i])
	}
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SyncReplicaElectionConstraintsApplyConfiguration) WithEnabled(value bool) *SyncReplicaElectionConstraintsApplyConfiguration {
	b.Enabled = &value
	return b
}
