// Code generated by controller-gen. DO NOT EDIT.

package v1

// SynchronizeReplicasConfigurationApplyConfiguration represents a declarative configuration of the SynchronizeReplicasConfiguration type for use
// with apply.
//
// SynchronizeReplicasConfiguration contains the configuration for the synchronization of user defined
// physical replication slots
type SynchronizeReplicasConfigurationApplyConfiguration struct {
	// When set to true, every replication slot that is on the primary is synchronized on each standby
	Enabled *bool `json:"enabled,omitempty"`
	// List of regular expression patterns to match the names of replication slots to be excluded (by default empty)
	ExcludePatterns []string `json:"excludePatterns,omitempty"`
}

// SynchronizeReplicasConfigurationApplyConfiguration constructs a declarative configuration of the SynchronizeReplicasConfiguration type for use with
// apply.
func SynchronizeReplicasConfiguration() *SynchronizeReplicasConfigurationApplyConfiguration {
	return &SynchronizeReplicasConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SynchronizeReplicasConfigurationApplyConfiguration) WithEnabled(value bool) *SynchronizeReplicasConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithExcludePatterns adds the given value to the ExcludePatterns field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludePatterns field.
func (b *SynchronizeReplicasConfigurationApplyConfiguration) WithExcludePatterns(values ...string) *SynchronizeReplicasConfigurationApplyConfiguration {
	for i := range values {
		b.ExcludePatterns = append(b.ExcludePatterns, values[i])
	}
	return b
}
