// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// SynchronousReplicaConfigurationApplyConfiguration represents a declarative configuration of the SynchronousReplicaConfiguration type for use
// with apply.
//
// SynchronousReplicaConfiguration contains the configuration of the
// PostgreSQL synchronous replication feature.
// Important: at this moment, also `.spec.minSyncReplicas` and `.spec.maxSyncReplicas`
// need to be considered.
type SynchronousReplicaConfigurationApplyConfiguration struct {
	// Method to select synchronous replication standbys from the listed
	// servers, accepting 'any' (quorum-based synchronous replication) or
	// 'first' (priority-based synchronous replication) as values.
	Method *apiv1.SynchronousReplicaConfigurationMethod `json:"method,omitempty"`
	// Specifies the number of synchronous standby servers that
	// transactions must wait for responses from.
	Number *int `json:"number,omitempty"`
	// Specifies the maximum number of local cluster pods that can be
	// automatically included in the `synchronous_standby_names` option in
	// PostgreSQL.
	MaxStandbyNamesFromCluster *int `json:"maxStandbyNamesFromCluster,omitempty"`
	// A user-defined list of application names to be added to
	// `synchronous_standby_names` before local cluster pods (the order is
	// only useful for priority-based synchronous replication).
	StandbyNamesPre []string `json:"standbyNamesPre,omitempty"`
	// A user-defined list of application names to be added to
	// `synchronous_standby_names` after local cluster pods (the order is
	// only useful for priority-based synchronous replication).
	StandbyNamesPost []string `json:"standbyNamesPost,omitempty"`
	// If set to "required", data durability is strictly enforced. Write operations
	// with synchronous commit settings (`on`, `remote_write`, or `remote_apply`) will
	// block if there are insufficient healthy replicas, ensuring data persistence.
	// If set to "preferred", data durability is maintained when healthy replicas
	// are available, but the required number of instances will adjust dynamically
	// if replicas become unavailable. This setting relaxes strict durability enforcement
	// to allow for operational continuity. This setting is only applicable if both
	// `standbyNamesPre` and `standbyNamesPost` are unset (empty).
	DataDurability *apiv1.DataDurabilityLevel `json:"dataDurability,omitempty"`
	// FailoverQuorum enables a quorum-based check before failover, improving
	// data durability and safety during failover events in CloudNativePG-managed
	// PostgreSQL clusters.
	FailoverQuorum *bool `json:"failoverQuorum,omitempty"`
}

// SynchronousReplicaConfigurationApplyConfiguration constructs a declarative configuration of the SynchronousReplicaConfiguration type for use with
// apply.
func SynchronousReplicaConfiguration() *SynchronousReplicaConfigurationApplyConfiguration {
	return &SynchronousReplicaConfigurationApplyConfiguration{}
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithMethod(value apiv1.SynchronousReplicaConfigurationMethod) *SynchronousReplicaConfigurationApplyConfiguration {
	b.Method = &value
	return b
}

// WithNumber sets the Number field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Number field is set to the value of the last call.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithNumber(value int) *SynchronousReplicaConfigurationApplyConfiguration {
	b.Number = &value
	return b
}

// WithMaxStandbyNamesFromCluster sets the MaxStandbyNamesFromCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStandbyNamesFromCluster field is set to the value of the last call.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithMaxStandbyNamesFromCluster(value int) *SynchronousReplicaConfigurationApplyConfiguration {
	b.MaxStandbyNamesFromCluster = &value
	return b
}

// WithStandbyNamesPre adds the given value to the StandbyNamesPre field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StandbyNamesPre field.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithStandbyNamesPre(values ...string) *SynchronousReplicaConfigurationApplyConfiguration {
	for i := range values {
		b.StandbyNamesPre = append(b.StandbyNamesPre, values[i])
	}
	return b
}

// WithStandbyNamesPost adds the given value to the StandbyNamesPost field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StandbyNamesPost field.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithStandbyNamesPost(values ...string) *SynchronousReplicaConfigurationApplyConfiguration {
	for i := range values {
		b.StandbyNamesPost = append(b.StandbyNamesPost, values[i])
	}
	return b
}

// WithDataDurability sets the DataDurability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDurability field is set to the value of the last call.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithDataDurability(value apiv1.DataDurabilityLevel) *SynchronousReplicaConfigurationApplyConfiguration {
	b.DataDurability = &value
	return b
}

// WithFailoverQuorum sets the FailoverQuorum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailoverQuorum field is set to the value of the last call.
func (b *SynchronousReplicaConfigurationApplyConfiguration) WithFailoverQuorum(value bool) *SynchronousReplicaConfigurationApplyConfiguration {
	b.FailoverQuorum = &value
	return b
}
