// Code generated by controller-gen. DO NOT EDIT.

package v1

// TablespaceConfigurationApplyConfiguration represents a declarative configuration of the TablespaceConfiguration type for use
// with apply.
//
// TablespaceConfiguration is the configuration of a tablespace, and includes
// the storage specification for the tablespace
type TablespaceConfigurationApplyConfiguration struct {
	// The name of the tablespace
	Name *string `json:"name,omitempty"`
	// The storage configuration for the tablespace
	Storage *StorageConfigurationApplyConfiguration `json:"storage,omitempty"`
	// Owner is the PostgreSQL user owning the tablespace
	Owner *DatabaseRoleRefApplyConfiguration `json:"owner,omitempty"`
	// When set to true, the tablespace will be added as a `temp_tablespaces`
	// entry in PostgreSQL, and will be available to automatically house temp
	// database objects, or other temporary files. Please refer to PostgreSQL
	// documentation for more information on the `temp_tablespaces` GUC.
	Temporary *bool `json:"temporary,omitempty"`
}

// TablespaceConfigurationApplyConfiguration constructs a declarative configuration of the TablespaceConfiguration type for use with
// apply.
func TablespaceConfiguration() *TablespaceConfigurationApplyConfiguration {
	return &TablespaceConfigurationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TablespaceConfigurationApplyConfiguration) WithName(value string) *TablespaceConfigurationApplyConfiguration {
	b.Name = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *TablespaceConfigurationApplyConfiguration) WithStorage(value *StorageConfigurationApplyConfiguration) *TablespaceConfigurationApplyConfiguration {
	b.Storage = value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *TablespaceConfigurationApplyConfiguration) WithOwner(value *DatabaseRoleRefApplyConfiguration) *TablespaceConfigurationApplyConfiguration {
	b.Owner = value
	return b
}

// WithTemporary sets the Temporary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Temporary field is set to the value of the last call.
func (b *TablespaceConfigurationApplyConfiguration) WithTemporary(value bool) *TablespaceConfigurationApplyConfiguration {
	b.Temporary = &value
	return b
}
