// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// TablespaceStateApplyConfiguration represents a declarative configuration of the TablespaceState type for use
// with apply.
//
// TablespaceState represents the state of a tablespace in a cluster
type TablespaceStateApplyConfiguration struct {
	// Name is the name of the tablespace
	Name *string `json:"name,omitempty"`
	// Owner is the PostgreSQL user owning the tablespace
	Owner *string `json:"owner,omitempty"`
	// State is the latest reconciliation state
	State *apiv1.TablespaceStatus `json:"state,omitempty"`
	// Error is the reconciliation error, if any
	Error *string `json:"error,omitempty"`
}

// TablespaceStateApplyConfiguration constructs a declarative configuration of the TablespaceState type for use with
// apply.
func TablespaceState() *TablespaceStateApplyConfiguration {
	return &TablespaceStateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TablespaceStateApplyConfiguration) WithName(value string) *TablespaceStateApplyConfiguration {
	b.Name = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *TablespaceStateApplyConfiguration) WithOwner(value string) *TablespaceStateApplyConfiguration {
	b.Owner = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *TablespaceStateApplyConfiguration) WithState(value apiv1.TablespaceStatus) *TablespaceStateApplyConfiguration {
	b.State = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *TablespaceStateApplyConfiguration) WithError(value string) *TablespaceStateApplyConfiguration {
	b.Error = &value
	return b
}
