// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// TopologyApplyConfiguration represents a declarative configuration of the Topology type for use
// with apply.
//
// Topology contains the cluster topology
type TopologyApplyConfiguration struct {
	// Instances contains the pod topology of the instances
	Instances map[apiv1.PodName]apiv1.PodTopologyLabels `json:"instances,omitempty"`
	// NodesUsed represents the count of distinct nodes accommodating the instances.
	// A value of '1' suggests that all instances are hosted on a single node,
	// implying the absence of High Availability (HA). Ideally, this value should
	// be the same as the number of instances in the Postgres HA cluster, implying
	// shared nothing architecture on the compute side.
	NodesUsed *int32 `json:"nodesUsed,omitempty"`
	// SuccessfullyExtracted indicates if the topology data was extract. It is useful to enact fallback behaviors
	// in synchronous replica election in case of failures
	SuccessfullyExtracted *bool `json:"successfullyExtracted,omitempty"`
}

// TopologyApplyConfiguration constructs a declarative configuration of the Topology type for use with
// apply.
func Topology() *TopologyApplyConfiguration {
	return &TopologyApplyConfiguration{}
}

// WithInstances puts the entries into the Instances field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Instances field,
// overwriting an existing map entries in Instances field with the same key.
func (b *TopologyApplyConfiguration) WithInstances(entries map[apiv1.PodName]apiv1.PodTopologyLabels) *TopologyApplyConfiguration {
	if b.Instances == nil && len(entries) > 0 {
		b.Instances = make(map[apiv1.PodName]apiv1.PodTopologyLabels, len(entries))
	}
	for k, v := range entries {
		b.Instances[k] = v
	}
	return b
}

// WithNodesUsed sets the NodesUsed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodesUsed field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithNodesUsed(value int32) *TopologyApplyConfiguration {
	b.NodesUsed = &value
	return b
}

// WithSuccessfullyExtracted sets the SuccessfullyExtracted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessfullyExtracted field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithSuccessfullyExtracted(value bool) *TopologyApplyConfiguration {
	b.SuccessfullyExtracted = &value
	return b
}
