// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// UsageSpecApplyConfiguration represents a declarative configuration of the UsageSpec type for use
// with apply.
//
// UsageSpec configures a usage for a foreign data wrapper
type UsageSpecApplyConfiguration struct {
	// Name of the usage
	Name *string `json:"name,omitempty"`
	// The type of usage
	Type *apiv1.UsageSpecType `json:"type,omitempty"`
}

// UsageSpecApplyConfiguration constructs a declarative configuration of the UsageSpec type for use with
// apply.
func UsageSpec() *UsageSpecApplyConfiguration {
	return &UsageSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UsageSpecApplyConfiguration) WithName(value string) *UsageSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *UsageSpecApplyConfiguration) WithType(value apiv1.UsageSpecType) *UsageSpecApplyConfiguration {
	b.Type = &value
	return b
}
