// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/xataio/xata-cnpg/api/v1"
)

// VolumeSnapshotConfigurationApplyConfiguration represents a declarative configuration of the VolumeSnapshotConfiguration type for use
// with apply.
//
// VolumeSnapshotConfiguration represents the configuration for the execution of snapshot backups.
type VolumeSnapshotConfigurationApplyConfiguration struct {
	// Labels are key-value pairs that will be added to .metadata.labels snapshot resources.
	Labels map[string]string `json:"labels,omitempty"`
	// Annotations key-value pairs that will be added to .metadata.annotations snapshot resources.
	Annotations map[string]string `json:"annotations,omitempty"`
	// ClassName specifies the Snapshot Class to be used for PG_DATA PersistentVolumeClaim.
	// It is the default class for the other types if no specific class is present
	ClassName *string `json:"className,omitempty"`
	// WalClassName specifies the Snapshot Class to be used for the PG_WAL PersistentVolumeClaim.
	WalClassName *string `json:"walClassName,omitempty"`
	// TablespaceClassName specifies the Snapshot Class to be used for the tablespaces.
	// defaults to the PGDATA Snapshot Class, if set
	TablespaceClassName map[string]string `json:"tablespaceClassName,omitempty"`
	// SnapshotOwnerReference indicates the type of owner reference the snapshot should have
	SnapshotOwnerReference *apiv1.SnapshotOwnerReference `json:"snapshotOwnerReference,omitempty"`
	// Whether the default type of backup with volume snapshots is
	// online/hot (`true`, default) or offline/cold (`false`)
	Online *bool `json:"online,omitempty"`
	// Configuration parameters to control the online/hot backup with volume snapshots
	OnlineConfiguration *OnlineConfigurationApplyConfiguration `json:"onlineConfiguration,omitempty"`
}

// VolumeSnapshotConfigurationApplyConfiguration constructs a declarative configuration of the VolumeSnapshotConfiguration type for use with
// apply.
func VolumeSnapshotConfiguration() *VolumeSnapshotConfigurationApplyConfiguration {
	return &VolumeSnapshotConfigurationApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithLabels(entries map[string]string) *VolumeSnapshotConfigurationApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithAnnotations(entries map[string]string) *VolumeSnapshotConfigurationApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithClassName sets the ClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClassName field is set to the value of the last call.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithClassName(value string) *VolumeSnapshotConfigurationApplyConfiguration {
	b.ClassName = &value
	return b
}

// WithWalClassName sets the WalClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WalClassName field is set to the value of the last call.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithWalClassName(value string) *VolumeSnapshotConfigurationApplyConfiguration {
	b.WalClassName = &value
	return b
}

// WithTablespaceClassName puts the entries into the TablespaceClassName field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the TablespaceClassName field,
// overwriting an existing map entries in TablespaceClassName field with the same key.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithTablespaceClassName(entries map[string]string) *VolumeSnapshotConfigurationApplyConfiguration {
	if b.TablespaceClassName == nil && len(entries) > 0 {
		b.TablespaceClassName = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.TablespaceClassName[k] = v
	}
	return b
}

// WithSnapshotOwnerReference sets the SnapshotOwnerReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotOwnerReference field is set to the value of the last call.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithSnapshotOwnerReference(value apiv1.SnapshotOwnerReference) *VolumeSnapshotConfigurationApplyConfiguration {
	b.SnapshotOwnerReference = &value
	return b
}

// WithOnline sets the Online field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Online field is set to the value of the last call.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithOnline(value bool) *VolumeSnapshotConfigurationApplyConfiguration {
	b.Online = &value
	return b
}

// WithOnlineConfiguration sets the OnlineConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnlineConfiguration field is set to the value of the last call.
func (b *VolumeSnapshotConfigurationApplyConfiguration) WithOnlineConfiguration(value *OnlineConfigurationApplyConfiguration) *VolumeSnapshotConfigurationApplyConfiguration {
	b.OnlineConfiguration = value
	return b
}
